### ISSUE TITLE
@vite() with ngrok doesn't work

### ISSUE THREAD

**Issue by eminos** [laravel/vite-plugin#100]
- Laravel Version: 9.21.0
- PHP Version: 8.1.6

### Description:

The `@vite()` directive generates js and css URLs with the `asset()` URL helper, which generates "full URLs".
This doesn't really work when using ngrok or similar tunneling tools.
Shouldn't these URLs be relative per default, for example if no `ASSET_URL`  is set in `.env`?

A workaround seems to be to set `ASSET_URL=.` in `.env`

**Comment by jessarcher** [comment]
Hi @eminos, do you have a proposed solution that still supports the `ASSET_URL` for things like Vapor?

**Comment by eminos** [comment]
Maybe something like this?
Pass the asset path through `makeAssetUrl` that only uses `asset()` if `config('app.asset_url')` is set.

```php
    public function __invoke($entrypoints, $buildDirectory = 'build')
    {
        // ...

        foreach ($entrypoints as $entrypoint) {
            if (! isset($manifest[$entrypoint])) {
                throw new Exception("Unable to locate file in Vite manifest: {$entrypoint}.");
            }

            $tags->push($this->makeTag($this->makeAssetUrl("{$buildDirectory}/{$manifest[$entrypoint]['file']}")));

            if (isset($manifest[$entrypoint]['css'])) {
                foreach ($manifest[$entrypoint]['css'] as $css) {
                    $tags->push($this->makeStylesheetTag($this->makeAssetUrl("{$buildDirectory}/{$css}")));
                }
            }

            if (isset($manifest[$entrypoint]['imports'])) {
                foreach ($manifest[$entrypoint]['imports'] as $import) {
                    if (isset($manifest[$import]['css'])) {
                        foreach ($manifest[$import]['css'] as $css) {
                            $tags->push($this->makeStylesheetTag($this->makeAssetUrl("{$buildDirectory}/{$css}")));
                        }
                    }
                }
            }
        }

        // ...
    }

    protected function makeAssetUrl($path)
    {
        return (config('app.asset_url')) ? asset($path) : $path;
    }
```

This works for my use case (ngrok needs relative paths), but I really don't know if it breaks anything else by not using the `asset()` helper.

**Comment by timacdonald** [comment]
@eminos could you not just set the `ASSET_URL` to the appropriate URL when sharing?

**Comment by driesvints** [comment]
> could you not set the ASSET_URL to the appropriate URL when sharing?

Think this is a good intermediate solution here.

**Comment by ruttydm** [comment]
For default laravel installations the valet share command using ngrok doesn't load the js/css.

Is there a workaround for this?

I've been trying to make it work but to no avail.
