### ISSUE TITLE
Unmet peer dependencies for vite-plugin-full-reload

### ISSUE THREAD

**Issue by bcorcoran** [laravel/vite-plugin#104]
- Laravel Vite Plugin Version: 0.5.0

### Description:

Laravel vite plugin currently requires vite-plugin-full-reload 1.0.1 as a dev dependency but 1.0.1 requires vite ^2.7.10

Please update dependency to 1.0.2

### Steps To Reproduce:

```
pnpm update
Already up-to-date
Progress: resolved 263, reused 231, downloaded 0, added 0, done
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ laravel-vite-plugin
  └─┬ vite-plugin-full-reload
    └── ✕ unmet peer vite@2: found 3.0.2
```

**Comment by timacdonald** [comment]
This has been addressed in the upstream package.
