### ISSUE TITLE
Plugin is rewriting forward slashes to backslashes in Manifest on NPM Run Build

### ISSUE THREAD

**Issue by liambhc** [laravel/vite-plugin#105]
- Laravel Vite Plugin Version: 0.5.0
- Laravel Version: 9.21.5
- Node Version: 16.15.1
- NPM Version: 8.13.1
- Vite Version: 3.0.2
- Host operating system: Windows 10 21H2 19044.1826
- Web Browser & Version: N/A
- Running in Sail / Docker: Homestead

### Description:
Npm Run Dev is serving my JS and CSS files as expected.
But on running Npm Run Build, I get errors for files defined in my plugin input array (besides app.js) and looking in the manifest.json, all the filenames and srcs have the last directory set to "\\" rather than "/" and therefore do not resolve correctly.

### Steps To Reproduce:
Update to latest plugin and Vite Version. Run Npm Install, then Npm Run Build

vite.config.js
``` javascript
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
                'resources/fontawesome/css/fontawesome.min.css',
                'resources/fontawesome/css/solid.min.css',
                'vendor/spatie/laravel-dashboard/resources/dist/dashboard.min.css'
            ],
            refresh: true,
        }),
    ],
});
```

Snippet of manifest.json
``` json
"resources/css\\app.css": {
    "file": "assets/app.60269cff.css",
    "src": "resources/css\\app.css"
  },
  "resources/js\\app.css": {
    "file": "assets/app.71986987.css",
    "src": "resources/js\\app.css"
  },
  "resources/fontawesome/css\\solid.min.css": {
    "file": "assets/solid.min.5e686ca9.css",
    "src": "resources/fontawesome/css\\solid.min.css"
  },
  "resources/fontawesome/css\\fontawesome.min.css": {
    "file": "assets/fontawesome.min.d0fc1daf.css",
    "src": "resources/fontawesome/css\\fontawesome.min.css"
  },
  "vendor/spatie/laravel-dashboard/resources/dist\\dashboard.min.css": {
    "file": "assets/dashboard.min.4a38dae5.css",
    "src": "vendor/spatie/laravel-dashboard/resources/dist\\dashboard.min.css"
  }
```

**Comment by driesvints** [comment]
Heya, please see many previous closed issues before opening new ones.

**Comment by timacdonald** [comment]
Duplicate: https://github.com/laravel/vite-plugin/issues/101
