### ISSUE TITLE
Websocket fails using VSCode port forwarding.

### ISSUE THREAD

**Issue by sunscreem** [laravel/vite-plugin#109]
- Laravel Vite Plugin Version: 0.5.2
- Laravel Version: 3.0.0
- Node Version: 16.16.0
- NPM Version: 8.11.0
- Host operating system: Windows 10
- Web Browser & Version: Chrome 103
- Running in Sail / Docker: No - Running in VS Code remote WSL

### Description:

As above I'm using VS Code on Windows, remotely connected to a forge linux server.
VS Code is handling the port forwarding (proxying?) and after a bunch of trial and error and installing ssl certs I've got Vite to load in correctly in a fresh laravel install.

The problem is the websocket connection. I've spent around 3-4 hours now trying every possible config option I can think of but it point blank refuses to connect or just time's out:

![image](https://user-images.githubusercontent.com/7523595/181355219-05cb95ca-4673-4ca0-aa55-d62070fe7b6c.png)

It would seem to me that the websocket connection is failing but I'm not getting any information on why? Everything is using SSL, so I'm guessing it might be because localhost doesn't have a valid certificate. 

If I change the HMR host:

```
 server: {
      https: true,
        hmr: {
            host: "fl.sunscreem.xyz",
        },
   }
```

... then the js refuses to load. It just times out after 30 seconds (or in some trials of the config it returns a 404):

![image](https://user-images.githubusercontent.com/7523595/181356306-6f1c29b5-d956-457c-adbc-6330197a2889.png)

There's a bunch of conflicting advise on if this should work at all - why would VSCode not forward on WSS connections since they use the same port (443?)  I'm drawing a total blank on what to try next. 

I understand this might not be a bug but I'm now hoping it is - at least I'd feel I'm not losing my marbles lol. I really don't want to go back to mix as vite seems so much faster but this has me completely stumped and I'd be super grateful if you someone can help diagnose where the problem lies, or if this is indeed a bug.

If this is out of scope, is it possible to set up some sort of refresh that doesn't use websockets? I can see reference to `usePolling` but that seems to be an older version?

**Comment by sunscreem** [comment]
Hey all - is there any extra info I could provide?

**Comment by jessarcher** [comment]
Hi @sunscreem, I'm not too familiar with VS Code or Windows and I didn't even know VS Code could remotely connect to a server! Seems cool though.

Are you able to verify whether this works with a [standard Vite project](https://vitejs.dev/guide/#scaffolding-your-first-vite-project) I.e. without a backend server?

If so, are you able to get this working with Laravel without using this plugin, by manually configuring the [backend integration](https://vitejs.dev/guide/backend-integration.html) yourself?

**Comment by sunscreem** [comment]
Hey @jessarcher - Thank you for taking the time to help. 

I created a clean (vanilla js) vite project as you suggested and everything seems to be working great. I notice that the websocket connection is also there and working fine, so that would hint that it's something in the config vs VS code itself. 

I'm going to try setting up the backend integration in a clean Laravel project next and I'll report back.

**Comment by sunscreem** [comment]
Hey again @jessarcher. I've been trying this on and off for the last 2 days and I've not made much progress.

If I follow the instructions on on the backend integration you linked to, I can start the vite server but when I click the link to open the page it returns a 404 no matter what port its on. 

Another confusion is that the standard vite project (the one I managed to get working no problem) seems to use vite 2 where `laravel new` seems to install vite 3?

I'll keep trying things but I'm pretty much going to have to give up soon as I've now been about 6 hours trying to get this to work :( A real shame as I was really excited for this.

**Comment by jessarcher** [comment]
Hey @sunscreem, sorry to hear that. Thanks a lot for trying!

I'm going to close this for now as I'm not really set up to experiment with it myself. If you or someone else figures it out, and there's something we can do in this plugin, feel free to open a PR.
