### ISSUE TITLE
Laravel plugin keeps full refreshing the page when refresh is disabled

### ISSUE THREAD

**Issue by fabio-ivona** [laravel/vite-plugin#111]
- Laravel Vite Plugin Version: 0.5.2
- Laravel Version: 9.19.0
- Node Version: 16.15.0
- NPM Version: 8.11.0
- Host operating system: Linux
- Web Browser & Version: Chrome 103.0.5060.134 
- Running in Sail / Docker: Docker

### Description:

It seems that setting `refresh: false` doesn't disable full reloads on blade files changes

### Steps To Reproduce:

this is my vite.config.js

```javascript
import {defineConfig} from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    server: {
        host: '0.0.0.0',
        port: 3000,
    },
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
            ],
            refresh: false,
        })
    ],
});
```

and this is the result if I change one of my blade files:

https://user-images.githubusercontent.com/8792274/182189388-7cbde9b6-64f3-4cc2-9c56-e2d0ea10e841.mp4

am I missing something in the configuration?

**Comment by jessarcher** [comment]
Hey @fabio-ivona, thanks for reporting this.

I've been able to replicate the issue starting from version `0.5.0` onward when we switched to Vite 3.

I'll see if I can figure out what's going on.

**Comment by fabio-ivona** [comment]
@jessarcher if it is useful for debugging:

when `refresh = false;` , full refreshes are triggered only by `resources/views/**` changes, 

`app/View/Components/**` and `routes/**` are (correctly) excluded from full reload.

**Comment by fabio-ivona** [comment]
the full reload seems triggered by tailwind

if I disable tailwind in `postcss.config.js` no full refresh are triggered

also, dull refresh is triggered in Vite `updateModules` function ([ref](https://github.com/vitejs/vite/blob/1983cf43d4da92d40b1f96dff0a44def044f9130/packages/vite/src/node/server/hmr.ts#L148)) because `propagateUpdate` returns true [here](https://github.com/vitejs/vite/blob/1983cf43d4da92d40b1f96dff0a44def044f9130/packages/vite/src/node/server/hmr.ts#L276)  when app.css is updated by tailwind

hope this can help

**Comment by jessarcher** [comment]
Good find @fabio-ivona! I've also confirmed that the issue exists even when the code for the refresh feature in this plugin is completely removed.

I don't think there's anything we can do in this plugin to resolve it, and I see that you've raised the issue upstream, so I'm going to close this one. All the best in getting it resolved!

**Comment by fabio-ivona** [comment]
Yep, I'll try to sort it out with Vite team, also will share the issue here so anyone can help with the solution

This new vite "feature" not only completely broke our vite livewire plugin, but also makes livewire development more difficult than before, compelling you to refresh the page (and resetting components) even when changing some minor code

**Comment by fabio-ivona** [comment]
Just opened an issue https://github.com/vitejs/vite/issues/9512

@jessarcher as this issue is detrimental for laravel-vite too, if you could have a look and add any information you find useful, will be great :heart:

**Comment by fabio-ivona** [comment]
@jessarcher one last update

it seems that the issue can be solved inside `handleHotUpdate` method, my plugin is fixed with these lines of code, just in case you want to fix the `refresh=false` behaviour of the laravel-plugin:

```javascript
 handleHotUpdate(ctx) {
            if (minimatch(ctx.file, '**/storage/framework/views/**/*.php')) {
                return [];
            }

            for (const pattern of pluginConfig.watch) {
                if (minimatch(ctx.file, pattern)) {
                    refresh(ctx, pluginConfig)
                    return [];
                }
            }
        }
```

**Comment by timacdonald** [comment]
Thanks @fabio-ivona I've made a note of this and will take a look shortly.

**Comment by fabio-ivona** [comment]
Looking forward to see your code, keep me updated so I can adapt my plugin to not interfere with the laravel one

**Comment by fabio-ivona** [comment]
Looking forward to see your code, keep me updated so I can adapt my plugin to not interfere with the laravel one

**Comment by timacdonald** [comment]
After seeing the the response (https://github.com/vitejs/vite/issues/9512#issuecomment-1208133617) I'm not entirely sure we should attempt to "fix" the behaviour.

This is in place so that Tailwind JIT works - and if the browser doesn't do a refresh it seems like others things will break. Kinda just thinking we mark this one up as "expected behaviour" for the Laravel plugin at least.

Thoughts?
