### ISSUE TITLE
Compatibility with @vite/plugin-legacy

### ISSUE THREAD

**Issue by vilbergs** [laravel/vite-plugin#114]
Hello!

I've had fantastic success using this plugin so far, thanks for making our migration to Vite a breeze.

I've been trying to get [@vite/plugin-legacy](https://github.com/vitejs/vite/tree/main/packages/plugin-legacy) to work alongside this plugin, but the automatic code injection does not seem to take effect, I'm assuming that is for similar reasons that the legacy plugin does not work with the `lib` entry options in the Vite config (see https://github.com/vitejs/vite/issues/1639).

So far I've gotten Safari 11 to work by manually including the "polyfills" chunk generated by the build, but in order to support Edge 18 I believe I need the runtime check for dynamic import support to run. 

Any help towards a solution would be deeply appreciated, if this plugin uses the `lib` option for entry points I assume we'll just have to hope that https://github.com/vitejs/vite/issues/1639 gets solved, but until then I'll explore workarounds.

**Comment by driesvints** [comment]
Right now, we don't aim to be compatible with this library, sorry.

**Comment by tbruckmaier** [comment]
For reference, @kitro suggested a workaround here: https://github.com/laravel/framework/pull/42785#issuecomment-1203317575

**Comment by kyselberg** [comment]
hi!
could you tell if there are any updates on plans?
