### ISSUE TITLE
Event after npm run build page look for the resource/css/app.css but not to the public/build/assets

### ISSUE THREAD

**Issue by GrytsenkoAndrey** [laravel/vite-plugin#115]
- Laravel Vite Plugin Version: 0.5.0
- Laravel Version: 9.23
- Node Version: 16.15.1
- NPM Version: 8.11
- Host operating system:  Linux 21.10
- Web Browser : Chrome 102.0.5005.115 (Official Build) (64-bit) || Firefox 103.0.1 (64-bit)

### Description:
Event after npm run build page look for the resource/css/app.css but not to the public/build/assets

### Steps To Reproduce:
The project repository https://github.com/GrytsenkoAndrey/mytest-vite.local
Fresh Laravel project with installed Laravel UI Vue, Tailwind Css and Vue

package.json
```
{
    "private": true,
    "scripts": {
        "dev": "vite",
        "build": "vite build"
    },
    "devDependencies": {
        "@popperjs/core": "^2.10.2",
        "@vitejs/plugin-vue": "^3.0.1",
        "autoprefixer": "^10.4.8",
        "axios": "^0.27",
        "bootstrap": "^5.1.3",
        "laravel-vite-plugin": "^0.5.0",
        "lodash": "^4.17.19",
        "postcss": "^8.4.16",
        "sass": "^1.32.11",
        "tailwindcss": "^3.1.8",
        "vite": "^3.0.0",
        "vue": "^3.2.37"
    }
}
```
vite.config.js
```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
            ],
            refresh: true,
        }),
        vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false,
                },
            },
        }),
    ],
    resolve: {
        alias: {
            vue: 'vue/dist/vue.esm-bundler.js',
        },
    },
});
```
and the problem is - when I run
```
npm run dev
```
the styles & scripts work properly!

But when I run npm run build and load the page - it's awful

**Comment by jessarcher** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by jessarcher** [comment]
I had a look at your project to ensure it's not an issue with Laravel UI.

Your project has a mixture of CSS and SCSS. The `welcome.blade.php` view is loading `resources/css/app.css` but the `app.blade.php` layout is loading `resources/scss/app.scss`.

Your `vite.config.js` is only compiling `resources/css/app.css`, so the pages that load `resources/scss/app.scss` will fail in build mode.
