### ISSUE TITLE
"Too much recursion" with AlpineJs and  Laravel Jetstream on browser sync

### ISSUE THREAD

**Issue by LuanHimmlisch** [laravel/vite-plugin#117]
- Laravel Vite Plugin Version: 0.5.0
- Laravel Version: 9.23.0
- Node Version: 18.6.0
- NPM Version: 8.14.0
- Host operating system: Manjaro
- Web Browser & Version: Mozilla Firefox 102.0.1
- Running in Sail / Docker: No

### Description:

The browser sync seems to have some troubles with Alpine. When building the application with `vite build` it doesn't give any problems, but when running solely `vite` to start a browser sync server, it throws a "too much recursion" error and many more relating Alpine.

### Steps To Reproduce:

1. Scaffold a new Laravel project with Jetstream
2. Run `npm run dev` or `yarn dev`

### Screenshots:

![Screenshot from 2022-08-08 12-32-53](https://user-images.githubusercontent.com/46875694/183478770-3ad2db03-cf85-4d6c-834b-98cbcc2e3c9f.png)

![Screenshot from 2022-08-08 12-33-07](https://user-images.githubusercontent.com/46875694/183478812-ceb46125-0959-4ef9-872a-62df08124446.png)

![Screenshot from 2022-08-08 12-33-25](https://user-images.githubusercontent.com/46875694/183478831-2b64491e-6ef1-45f2-932f-1c11ad94cc07.png)

**Comment by timacdonald** [comment]
I'm unable to reproduce this with the following steps:

```
composer create-project laravel/laravel recursion-test \
  && cd recursion-test \
  && composer require laravel/jetstream \
  && php artisan jetstream:install livewire \
  && npm install \
  && sed -i 's/SESSION_DRIVER=database/SESSION_DRIVER=file/' .env \
  && yarn dev

# another tab
php artisan serve

# navigate to /login
```

Everything is working as expected for me.

If you could produce a minimal reproduction case in a repository or as a shell script, that would be great and we can take a better look.
