### ISSUE TITLE
`withoutMix()` helper

### ISSUE THREAD

**Issue by plakhin** [laravel/vite-plugin#120]
We're using `$this->withoutMix();` helper in our `Tests\TestCase::setUp()` so we can run some tests with CI pipeline without having compiled assets. It would be nice to have something similar for Vite.

**Comment by jessarcher** [comment]
`$this->withoutVite()` already exists :slightly_smiling_face:

https://github.com/laravel/framework/blob/9a6bfc46593cc1cf262d7495c63c484111880cd5/src/Illuminate/Foundation/Testing/Concerns/InteractsWithContainer.php#L106

**Comment by plakhin** [comment]
Cool! @jessarcher thanks for pointing out!

May be it makes sense to mention it somewhere in the documentation.

**Comment by jessarcher** [comment]
Done :slightly_smiling_face: 

https://github.com/laravel/docs/pull/8122
