### ISSUE TITLE
refresh option not working after the upgrade

### ISSUE THREAD

**Issue by rushi7997** [laravel/vite-plugin#122]
- Laravel Vite Plugin Version: 0.5.4
- Laravel Version: 9.25.1
- Node Version: 16.13.2
- NPM Version: 8.1.2
- Host operating system: Windows 11
- Web Browser & Version: ? Chrome
- Running in Sail / Docker: No
- Vite Version: 3.0.8

### Description:
I was using Laravel Vite with an older plugin version (0.4.0), and I was following this guide by freek.dev to have my app work with hot reload [guide](https://freek.dev/2277-using-laravel-vite-to-automatically-refresh-your-browser-when-changing-a-blade-file)
it was working fine. Then I did go through laravel docs recently and tried to upgrade the Laravel and Vite plugin to the latest version, which has a refresh option. I tried this in my `vite.config.js` file, and it's not working for some reason.

``` js
import {defineConfig} from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/web.scss',
                'resources/js/web.js',
            ],
            refresh: {
                paths: [
                    'resources/css/**',
                    'resources/js/**',
                    'resources/views/**',
                ]
            },
        }),
    ],
});

```

The steps from the blog mentioned earlier still work well with hot reload. Just the refresh option is not working as expected

**Comment by timacdonald** [comment]
Hey @rushi7997,

Looks like you just have specified your paths incorrectly.

```js
import {defineConfig} from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/web.scss',
                'resources/js/web.js',
            ],
            refresh: [
                'resources/css/**',
                'resources/js/**',
                'resources/views/**',
            ],
        }),
    ],
});
```

See the [Laravel Vite: Refreshing on Save](https://laravel.com/docs/9.x/vite#blade-refreshing-on-save) documentation for more info.

Just note that I wouldn't recommend adding the `resources/css/**` and `resources/js/**` paths into the refresh option. This will mean you lose the benefit of the HMR server as the browser will refresh instead of hot reload.

If you don't need these paths, you can also just use the default paths...

```js
import {defineConfig} from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/web.scss',
                'resources/js/web.js',
            ],
            refresh: true,
        }),
    ],
});
```

Which will watch for view changes and refresh when they change.

**Comment by rushi7997** [comment]
@timacdonald I have tried the solution you gave it is not working on my machine.
I have no idea how the hot reload/refresh works but what's strange in my case is it's not establishing this WS connection to the Vite dev server 
![image](https://user-images.githubusercontent.com/29655727/185440120-858095e9-c5f6-4ed3-8d13-94c8ddd81722.png)

I think it has something to do with HMR/refresh

**Comment by timacdonald** [comment]
No troubles.

So it is working on a fresh install, which means it isn't you computer. So there must be something in your setup for the specific project.

Can you ensure that you have run each of these steps in order from the [official upgrade guide](https://github.com/laravel/vite-plugin/blob/main/UPGRADE.md).the order matters).

If this are still not working, try running:

```
composer require laravel/framework:^9.25.1
npm install --save-dev vite@^3.0.8 laravel-vite-plugin@^0.5.4
```

and ensure that they run successfully.


Finally, if it still is not working, can you please provide your `vite.config.js` file.

Another question for you: I can see you are running on Windows. Are you running things in WSL2?
