### ISSUE TITLE
Call to undefined method Illuminate\Foundation\Vite::asset()

### ISSUE THREAD

**Issue by renky** [laravel/vite-plugin#124]
- Laravel Vite Plugin Version: 0.5.0
- Laravel Version: 9.25.1
- Node Version: v16.14.0
- NPM Version: 8.3.1
- Host operating system: Windows WSL2 (Ubuntu)
- Web Browser & Version: doesn't matter
- Running in Sail / Docker: Docker

### Description:
First to my apology - I'm not quite sure if the issue is placed in the right repository but since it happens after following the vite-plugin docs on laravel.com I placed it here.

I tried to follow the guide:
https://laravel.com/docs/9.x/vite#blade-processing-static-assets
and it seems the part 
```
import.meta.glob([
  '../images/**',
  '../fonts/**',
]);
```
works fine since my images are all copied to public/build/assets by vite.

But then trying to use this assets in the blade-files like showed in the docs:
```
<img src="{{ Vite::asset('resources/images/logo.png') }}">
```
I get this error: 
`Call to undefined method Illuminate\Foundation\Vite::asset()`

so it seems to be correct - there is no asset-method in my Vite-Facade - but what does this mean?

Is it an error in the docs? is it an error in Laravels Vite-Facade? Or does vite do something strange?

**Comment by driesvints** [comment]
Hi there. This was merged before it's released. Please wait until next release day Tuesday before using this.

**Comment by renky** [comment]
Nevermind - just found the reason when I cloned current master branch of laravel framework - this docs-info is really really new and the corresponding code in Facades is not yet published in a version of the framework - so sorry for that...
