### ISSUE TITLE
Use functions defined in javascript in blade files

### ISSUE THREAD

**Issue by nathanaelhoun** [laravel/vite-plugin#126]
Currently, when creating a function in `resources/js/app.js`, like this
```js
// import './bootstrap';
function helloWorld() {
    console.log('Hello world');
}
```

This function is not in the generated `public/build/assets/app.XXXXXX.js` file, because it is unused and excluded from the build.
But I want to use it in a blade file, for example by adding add the end of `welcome.blade.php` a reference to the function `<script>helloWorld();</script>`.

I can trick it by using the function somewhere in `app.js`, and then modify the `vite.config.js` file to prevent the renaming of identifiers (which make the output file way bigger, because it doesn't minify local identifiers as well), but I can't find a way of preserving the "unused" function.

<details><summary><code>vite.config.js</code></summary>

```javascript
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    esbuild: {
        minifyIdentifiers: false,
    },
    plugins: [
        laravel({
            input: ['resources/css/app.css', 'resources/js/app.js'],
            refresh: true,
        }),
    ],
});
```

</details>

Is there any way of doing this cleanly with Vite?

**Comment by timacdonald** [comment]
Hey!

You can see a few examples of this in the `bootstrap.js` file. What you will want to do is assign things to the window.

```js
window.helloWorld = () => {
    console.log('Hello world')
}
```

This will then  result in the following `app.js` file.

```js
window.helloWorld=()=>{console.log("Hello world")};
```

If you introduced the `minifyIdentifiers` to try and help with this issue, you should be able to remove it...but you might also just like to actually be able to read JavaScript errors hahaha...ahhh JavaScript "v was not defined on Gs" does not help!!! hehe

Hope that gets you back on track.

**Comment by nathanaelhoun** [comment]
Thanks @timacdonald for the answer, it works by assigning things to the `window`, haven't though of this. Thanks!

I removed `minifyIdentifiers `, because in developement with hot-reload (which is awesome), JS is not minified so errors are readable 😉

**Comment by timacdonald** [comment]
oh nice!
