### ISSUE TITLE
TypeError: laravel is not a function

### ISSUE THREAD

**Issue by pepijndik** [laravel/vite-plugin#130]
- Laravel Vite Plugin Version: 0.5.4
- Laravel Version: 9.19
- Node Version: v18.5.0
- NPM Version: 8.18.0
- Host operating system: macOS 
- Web Browser & Version: ?
- Running in Sail / Docker: No

### Description:
Can't run the NPM run dev,  vite throws a error that Laravel is not a function although 
I have imported the Plugin and installed it. 

 installed packages:
```json
"devDependencies": {
  "axios": "^0.25",
  "lodash": "^4.17.19",
  "postcss": "^8.4.16",
  "tailwindcss": "^3.1.8",
  "@tailwindcss/forms": "^0.5.2",
  "@tailwindcss/typography": "^0.5.0",
  "@vitejs/plugin-basic-ssl": "^0.1.2",
  "laravel-vite-plugin": "^0.5.4",
  "vite": "^3.0.9"
}
```
My vite config file,
```js
import { defineConfig } from 'vite';
import basicSsl from '@vitejs/plugin-basic-ssl'
import laravel from "laravel-vite-plugin"
export default defineConfig({
    server: {
        https: true,
        host: 'mobox.test',
    },
    plugins: [
        basicSsl(),
        laravel([
            'resources/css/app.css',
            'resources/js/app.js',
        ]),
    ],
    resolve: {
        alias: {
            '@': '/resources/js',
        },
    },
});

```

 
### Steps To Reproduce:
Just a normal Vite setup? getting this error on also on my windows dev machine which is also running the latest version of Node

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by pepijndik** [comment]
Already tried on the discord channel but nobody knows whats wrong.

**Comment by lrfahmi** [comment]
How to solve this issue?

**Comment by pepijndik** [comment]
Unfortunately not yet,

**Comment by fpolli** [comment]
Another dude asked the same exact question on StackOverflow two weeks ago and nobody has answered him either.
