### ISSUE TITLE
Gets killed on build

### ISSUE THREAD

**Issue by ignacio-dev** [laravel/vite-plugin#133]
- Laravel Vite Plugin Version: 3.0.9
- Laravel Version: 9.19.0
- Node Version: 16.17.0
- NPM Version: 8.18.0
- Host operating system: macOS 12.1
- Web Browser & Version: Chrome 104.0.5112.101 
- Running in Sail / Docker: Sail

### Description:
Processed get killed when running `./vendor/bin/sail npm run build`. This is the terminal output:

```
> build
> vite build

vite v3.0.9 building for production...
✓ 1239 modules transformed.
rendering chunks (72)...Killed
```

Works fine when running  `./vendor/bin/sail npm run dev`.

This issue happens randomly, but 75% of the times it fails.

### Steps To Reproduce:
- Follow migration steps
- Run ./vendor/bin/sail npm run build

**Comment by ignacio-dev** [comment]
This is the last thing it says when I run on verbose:

```
Killed.............] / : timing npm:load Completed in 30ms
npm timing command:run Completed in 44124ms
npm verb exit 137
npm timing npm Completed in 44163ms
npm verb code 137
```

**Comment by jessarcher** [comment]
Hi @ignacio-dev,

I've never seen this one before, but it sounds more like a Vite issue than an issue with this plugin.

* Does the build work if you run it _outside_ of the Sail container?
* What does your `vite.config.js` file look like?
* Do you have multiple entry points? If so, can you try with one at a time and see if one, in particular, is causing it?
* If you've narrowed it to down to one entry point (or only have one entry point) are you able to comment out all of the code in the entry point and see if it works, then start uncommenting sections until it breaks?

**Comment by driesvints** [comment]
@ignacio-dev feel free to comment when you can and we'll re-open
