### ISSUE TITLE
Vite is refreshing always in windows

### ISSUE THREAD

**Issue by davidjr82** [laravel/vite-plugin#137]
- Laravel Version: 9.27.0
- PHP Version: 8.1.2
- Database Driver & Version: NA
- OS: Windows 11, execute directly (no docker, no sail, no WSL)

### Description:
When using `refresh: false` in `vite.config.js`, the browser is still hot reloaded as soon as a file is saved.

### Steps To Reproduce:

Using this `vite.config.js` config file, execute `npm run dev` and `serve` to see the website in the browser. Make a change in a file, save, and the browser is reloaded, although there is `refresh: false` in the config file.

```js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
            ],
            refresh: false,
        }),
    ],
});
```

**Comment by driesvints** [comment]
Transferred to `vite-plugin` repo.

**Comment by davidjr82** [comment]
- Tailwind version: tailwindcss@3.1.8
- Also using [hotwired turbo](https://github.com/hotwired/turbo): @hotwired/turbo@7.2.0-beta.2

The refresh happens when modifying and saving, for example, the app.js file, or the login.blade.php file (using breeze).

`npm run dev`
![imagen](https://user-images.githubusercontent.com/4275886/188400347-3ce951e5-0a61-4d91-85c6-16d6c163e24b.png)


`php artisan serve`
![imagen](https://user-images.githubusercontent.com/4275886/188400104-8e6279dc-6ce8-4bef-8a20-aa253cc2cb11.png)


`tailwind.config.js`
```js
const defaultTheme = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Nunito', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [require('@tailwindcss/forms')],
};
```

**Comment by timacdonald** [comment]
Does `hotwired.js` import any CSS?

**Comment by timacdonald** [comment]
I should clarify - does any of your JS import CSS? be that `hotwired.js` or your `app.js`. Basically anything in your entrypoint that also includes hotwired.

**Comment by davidjr82** [comment]
No, if I comment everything in my app.js file and modify/save login.blade.php, the refresh is still happening. Attached log of npm run dev with that case:

![imagen](https://user-images.githubusercontent.com/4275886/188403829-719c87e0-a30f-4645-9377-ae183f4ebe8d.png)

**Comment by davidjr82** [comment]
If I comment the content of app.css, the refresh stop happening:

`app.css`
![imagen](https://user-images.githubusercontent.com/4275886/188404760-320312bd-d475-4853-ad5a-ad08392de1f6.png)

**Comment by timacdonald** [comment]
This behaviour is expected and is not introduced by the Laravel plugin.

See: https://github.com/vitejs/vite/issues/9512#issuecomment-1208133617

Vite has to do a refresh as there are circular dependencies when using Tailwind.

**Comment by davidjr82** [comment]
Thanks for looking into it! @timacdonald

**Comment by timacdonald** [comment]
no troubles
