### ISSUE TITLE
Vite won't work if public folder is outside of laravel folder structure 

### ISSUE THREAD

**Issue by Sebastiangperez** [laravel/vite-plugin#142]
- Laravel Vite Plugin Version: 0.6.0
- Laravel Version: 9.19
- Node Version: v14.18.2
- NPM Version: 8.19.0
- Host operating system: Windows / Linux / macOS Linux
- Web Browser & Version: Chorme
- Running in Sail / Docker: No

### Description:
I came across with an issue where i need to separate all laravel core framework except public folder and his files , 
i made a directory same level a public called laravel, all files are in there. 
i have my public folder , in this case , public_html , with all php files that came in the public laravel folder .
I made the changes so i can use the public folder as my document root. 
the problem is that when i run , npm vite o npm vite build , and use the @vite directive , Vite manifest is not found , seems that is not possible to look up one level up like this : 
Laravel <- laravel framework 
Public <- public files from laravel framework 
### Steps To Reproduce:
Download the laravel framework , install all dependencies, split laravel framework and public folder in separates directories and try to compile or run the build command also using the vite directive.

**Comment by timacdonald** [comment]
You may need to specify the [`publicDirectory` configuration option](https://github.com/laravel/vite-plugin/blob/main/src/index.ts#L14-L19) in your Laravel Vite plugin config.

However, keep in mind that [Laravel doesn't support changing the public path](https://github.com/laravel/framework/issues/44001#issuecomment-1236656300).

**Comment by Sebastiangperez** [comment]
Sorry , but is not working , i tried to do this , but keeps pointing /Laravel/../public/build/manifest.json where laravel is the framework folder and the public is where the index.php and all other files are. 
Laravel and Public folder are in the same level.
i change the name  "build" folder for "assets" and all files are in /public/assets/ and there is the manifest.json.

About changing public path , worked for me and for many other projects that i did , also the storage link command maybe do not work but you can simply try to do an ln command and that's it.

**Comment by Sebastiangperez** [comment]
I don't wanna say anything but i did it .. it worked ..
