### ISSUE TITLE
Laravel Vite plugin breaks Vite's publicDir option

### ISSUE THREAD

**Issue by julien-fontaine** [laravel/vite-plugin#144]
- Laravel Vite Plugin Version: 0.6.0
- Laravel Version: 9.30.0
- Node Version: 16.17.0
- PNPM Version: 7.9.5
- Host operating system: Linux
- Running in Sail / Docker: Docker

### Description:

The Laravel Vite plugin breaks Vite's `publicDir` option, causing the missing feature described in [Laravel documentation](https://laravel.com/docs/9.x/vite#vite-or-mix).

```javascript
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    publicDir: __dirname + '/resources/non_compiled_files',
    plugins: [
        laravel({
            input: [],
            refresh: true,
        }),
    ],
});
```

### Steps To Reproduce:

1. Create a Laravel project via the Composer.
2. Create/edit the `vite.config.js` to have the previous configuration.
3. Create the directory `non_compiled_files` inside the `resources` directory.
4. Create a file that should not be transformed by Vite inside this directory.
5. Run `pnpm install` and `pnpm build`.
6. The file created inside `non_compiled_files` is not present in the `public` directory nor in its children.

Note that it works as expected when removing the Laravel Vite plugin from `vite.config.js`, with some additional configuration that is normally added by the plugin, such as `build.outDir`.

**Comment by innocenzi** [comment]
Is there anything that prevents you from putting these files in `public` directly?

**Comment by julien-fontaine** [comment]
In our team we usually put every assets inside the resources directory to avoid misleading and forgetting when something must be updated. If we put them directly inside the public directory, they would be also mixed with compiled assets, which would increase mistakes.

**Comment by innocenzi** [comment]
Setting `publidDir` would mean assets in that directory would be served from the Vite server, but not from your actual web server.

eg. 
You have `/resources/non-compiled-files/image.png`
In dev, you use `/image.png` from `http://localhost` -> `http://localhost/image.png` is generated but it will 404

A better option would be to just put files in `/public` (or somewhere in the storage that you'd link). As for being mixed with compiled assets, Vite uses the `assets` subdirectory anyway. Unless you are committing compiled assets (which you shouldn't), this shouldn't be an issue. 

I don't really see an issue with PRing `laravel-vite-plugin` to allow userland `publicDir`, but that would most likely not behave like you'd expect.

**Comment by driesvints** [comment]
Please see the above. 

Thanks @innocenzi

**Comment by julien-fontaine** [comment]
@innocenzi I don't get your point, I don't get a 404 when doing this using Vite, without Laravel Vite plugin. It works as expected and compiled files are indeed served by the web server, as it would also work if I stop the Vite server, once files are compiled.

Compiled assets are not versioned, but if we follow your advise, in development environment they would be mixed with uncompiled assets, which would mislead on which files should be committed or not.

Never mind, we will use Vite without Laravel Vite plugin or get back to Laravel mix which works as expected.
Thank you for your reply.

**Comment by innocenzi** [comment]
@julien-fontaine Can you show me with code how you create a url to this `/resources/non-compiled-files/image.png` that works in both development and production?

**Comment by julien-fontaine** [comment]
I use `php asset('/image.png')` and cannot use `php Vite::asset('/image.png')`, because Laravel only looks for files listed in the `manifest.json`, and this kind of files are not listed in. Furthermore, Laravel expects this file to be inside the build directory, which is not the case according to the [Vite documentation](https://vitejs.dev/guide/assets.html#the-public-directory).
However, this is another issue which is not related to the build process.

**Comment by innocenzi** [comment]
Yes that's what I meant and that's what I explained in the first message. I still don't get how you'd get the compiled assets and other stuff mixed up since everything is inside `public/assets`:

```
resources/
├── js/app.js
└── css/app.css
public/
├── .htaccess
├── index.php
├── robots.txt
├── your-custom-image.png
├── assets/
│   ├── app.123456.js
│   ├── whatever.123456.js
│   └── something.123456.css
└── manifest.json
```

You can even configure Vite to use a sub-directory, so `manifest.json` could be in `public/build` and assets would be in `public/build/assets` for instance. 

Further, you could just link the storage and have your assets in `public/storage/` directly (which I recommend anyway). 

So to me, there is really no point in depending on Vite to copy these assets.

**Comment by vfiruz97** [comment]
Here the example of changed outDir 

```javascript
import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";
import vue from "@vitejs/plugin-vue";
// const path = require('path')

export default defineConfig({
  build: {
    outDir: "public/js/js/app",
  },
  server: {
    watch: {
      usePolling: true,
    },
    host: "0.0.0.0",
    port: 3011,
    hmr: {
      port: 3011,
      host: "localhost",
      protocol: "ws",
    },
  },
  // resolve:{
  //     alias:{
  //         '@' : path.resolve('./resource/js')
  //     },
  // },
  plugins: [
    laravel({
      input: "resources/js/app.js",
      buildDirectory: "js/js/app",
      refresh: true,
    }),
    vue({
      template: {
        transformAssetUrls: {
          base: null,
          includeAbsolute: false,
        },
      },
    }),
  ],
});

and you put 
 @vite('resources/js/app.js', 'js/js/app')
 in the app.blade.php
 
 I hope it helps anyone
```
