### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by webparadoxer** [laravel/vite-plugin#145]
- Laravel Vite Plugin Version: #.#.#
- Laravel Version: #.#.#
 9.30.1 
- Node Version: #.#.#
v18.8.0
- NPM Version: #.#.#
 8.18.0
- Host operating system: Windows / Linux / macOS #.#.#
macOS
- Web Browser & Version: ?
- Running in Valet

### Description:

The resource is not copied during the build: Unable to locate file in Vite manifest: resources/us/images/favicon.svg.

But everything works when assembling dev: [http://[::1]:5173/../resources/us/images/favicon.svg](http://[::1]:5173/resources/us/images/favicon.svg)

And I have another question, is it possible to make aliases for the blade to specify the path so` <link rel="icon" href="{{ Vite::asset('@alias/images/favicon.svg') }}" sizes="any">`

```

ls -la resources
total 16
drwxr-xr-x   5 vid  staff   160 15 сен 16:10 .
drwxr-xr-x  29 vid  staff   928 16 сен 13:45 ..
-rw-r--r--@  1 vid  staff  6148 15 сен 15:39 .DS_Store
drwxr-xr-x   6 vid  staff   192 15 сен 15:39 us
drwxr-xr-x   4 vid  staff   128 16 сен 13:38 views

```

### Steps To Reproduce:

```
import.meta.glob([
    '../us/images/**',
]);
```

```import {defineConfig, loadEnv} from 'vite';
import laravel from 'laravel-vite-plugin';

const path = require('path')

process.env = {...process.env, ...loadEnv('dev', process.cwd())};
const SHOP_LANG = process.env.VITE_SHOP_LANG


export default defineConfig({
    plugins: [
        laravel({
            input: ['resources/' + SHOP_LANG + '/js/app.js'],
            buildDirectory: 'build/' + SHOP_LANG,
            refresh: true,
        }),
    ],

});
```

```
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {{ Vite::useBuildDirectory('build/us')  }}

    <link rel="icon" href="{{ Vite::asset('../resources/us/images/favicon.svg') }}" sizes="any">

</head>
<body>

</body>
</html>
```

**Comment by timacdonald** [comment]
I think you just have the path wrong. The path is relative to current file.

```
resources/
  us/
    js/
      app.js
    images/
      favicon.svg
```

So you need the following path:

```js
// file: resources/us/js/app.js

import.meta.glob([
    '../images/**',
]);
```

**Comment by timacdonald** [comment]
Re aliases: https://github.com/laravel/framework/pull/44198
