### ISSUE TITLE
Laravel Vite: Assets blocked/Mixed Content issues in production environment

### ISSUE THREAD

**Issue by bblumenfelder** [laravel/vite-plugin#147]
- Laravel Vite Plugin Version: 0.6.0
- Laravel Version: 9.2.9
- Node Version: 14.18.0
- NPM Version: 8.51
- Host operating system: Ubuntu 20.04
- Web Browser & Version: Chrome 105.0.5195.127; Firefox 105.0
- Running in Sail / Docker: No

### Description:
I'm hosting my App on an EC2-instance behind an Elastic Load Balancer which manages my SSL-Certificate. On this EC2-Instance my nginx-configuration is redirecting all http-Requests to https.
I recently switched to Vite which caused me a lot of trouble. When I push my app to the server after calling `npm run build` my assets are blocked. In the browser console I get:

```
Mixed Content: The page at 'domain.com' was loaded over HTTPS, but requested an insecure ...
```

# My Setup:

*vite.config.js*
```
export default defineConfig({
    server: {
        host: 'localhost',
    },
    plugins: [
        laravel([
            'resources/assets/sass/app.sass',
            // etc...
        ]),
        vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false,
                },
            },
        }),
    ],
});
```

Setting "https: true" in the server-block didn't help me.

*.env*
```
APP_ENV=production
APP_URL=https://domain.com
ASSET_URL=https://domain.com
```

In my blade template I'm using the Vite-directive:
```
@vite('resources/assets/sass/app.sass')
```

I tried the following solutions:
* Setting `$proxies = '*'` in TrustProxies.php, which doesn't have any effect.
* Setting `URL::forceScheme('https');` in AppServiceProvider.php, which will load the assets but lead to a lot of other issues.

Somehow the @vite-directive is not resolving my assets as secure assets. With Laravel Mix I could just call `secure_asset`.

### Steps To Reproduce:
- Switch from Laravel Mix to Vite
- Run `npm run build` on local development server
- Push new app version to ec2-instance with git

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
