### ISSUE TITLE
Not able to load background images from CSS in vite

### ISSUE THREAD

**Issue by rakeshappycodes** [laravel/vite-plugin#148]
- Laravel Vite Plugin Version: 0.6.0
- Laravel Version: 9.19
- Node Version: v18.5.0
- NPM Version: 8.12.1
- Host operating system: Linux
- Web Browser & Version: Chrome
- Running in Sail / Docker: No

### Description:
Not able to load background images from css when using vite [example](https://laravel-vite.dev/guide/essentials/working-with-assets.html#references-in-code)  during `npm run dev`

```
.is-wave-navy:after{
    content: '';
    background-image: url(@/resources/images/wave.svg);
    background-position: center bottom;
    background-size: 101%;
    background-repeat: no-repeat;
    width: 100%;
    height: 110px;
    position: absolute;
    bottom: -1px;
    left: 0;
}
```

CSS : https://i.imgur.com/zJsQzFf.png
Html and Css output: https://i.imgur.com/VpMABCl.png

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by timacdonald** [comment]
@rakeshappycodes try using relative URL paths e.g. `../images/wave.svg`

```
resources/
    images/
        wave.svg
    css/
        app.css
```

```
// file: resources/css/app.css
.is-wave-navy:after{
    background-image: url('../images/wave.svg');
}
```
