### ISSUE TITLE
Generate custom manifest.json file name

### ISSUE THREAD

**Issue by kitro** [laravel/vite-plugin#149]
Vite provides [a way to specify](https://vitejs.dev/config/build-options.html#build-manifest) the name of the `manifest.json`, many Laravel projects using a modular structure inside each module have their own `vite.config.js` file. Currently, [the default file name is `manifest.json` ](https://github.com/laravel/vite-plugin/blob/main/src/index.ts#L127) I think it will be nice to get the file name from `userConfig.build?.manifest?` .

For the Vite facade need to specify the `manifest.json` file name if it's different from `manifest.json`. 

_the Laravel mix has a plugin `laravel-mix-merge-manifest` to merge bundled files into one `manifest.json`._

**Comment by jessarcher** [comment]
I've created https://github.com/laravel/vite-plugin/pull/150 that will respect the manifest config if provided :+1:

For the Vite facade, you can extend it and override the `manifestPath` method.
