### ISSUE TITLE
Vite build requires composer install which requires Vite build

### ISSUE THREAD

**Issue by michaellindahl** [laravel/vite-plugin#155]
- Laravel Vite Plugin Version: 0.5.3
- Laravel Version: v9.25.1
- Node Version: v18.7.0
- NPM Version: 8.15.0

### Description:

When attempting to build and run Vite & Composer from a new repository, where the build process previously hasn't been run a circular dependency is hit. Running `composer install` triggers `Vite.php:139` which expects a build manifest in `public/build/manifest.json`. However, `npm run build` hasn't yet run. When attempting to run `npm run build` first, it fails to complete as it requires resources from composer. `[vite:css] Failed to find '../../vendor/filament/filament/resources/css/app.css'`.

### Possible Resolution:

Prior to the package discovery step in `composer.json`, add two lines to install and build the javascript dependencies. Being a hobbyist web developer, I'm wondering if this is the best resolution to this issue? Was there something that I setup incorrectly that is requiring this change? Thanks.

```
        "post-autoload-dump": [
            "npm ci",
            "npm run build",
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
```

### Steps To Reproduce:

1. Include third party css files in the vendor folder within the vite config.
2. Attempt to build the repository from scratch.

`vite.config.js`:
```
export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
                'resources/css/filament.css',
            ],
            refresh: [
                ...refreshPaths,
                'app/Http/Livewire/**',
            ],
        }),
    ],
});

```

`resources/css/filament.css`:
```
@import '../../vendor/filament/filament/resources/css/app.css';
```

**Comment by timacdonald** [comment]
It sounds like this might be a project specific issue.

The Laravel skeleton and the starter kits don't have any circular dependencies like this, so I would recommend addressing this one in your local setup.
