### ISSUE TITLE
Make HMR client protocol better configurable

### ISSUE THREAD

**Issue by Mtillmann** [laravel/vite-plugin#156]
https://github.com/laravel/vite-plugin/blob/2abd0b510b43061fab0027d5492547ce9a91dcad/src/index.ts#L393

I'm working with DDEV and spend some time today getting the HMR working. It'd be great if I could simply set the client protocol to `https` and have it take effect. At the moment I have to set it to `wss` in order to have my _hot_ dev server frontend URLs written with appropriate protocol.

Since I can't make a PR, here's my proposal:

```javascript
//OLD: const clientProtocol = configHmrProtocol ? (configHmrProtocol === 'wss' ? 'https' : 'http') : null
const clientProtocol = ['https','wss'].includes(configHmrProtocol) ? 'https' : (configHmrProtocol === 'http' ? 'http' : null)
```

Thanks for considering it!

**Comment by timacdonald** [comment]
@Mtillmann can you do this already via Vite itself with the [`server.hmr.protocol` option](https://vitejs.dev/config/server-options.html#server-hmr)?

**Comment by Mtillmann** [comment]
In a regular vite setup this might work but in this codebase the protocol is only set to `https` when the `server.hmr.protocol` is set to `wss`. It's used to derive the `viteServerDevUrl`, which is then written into `public/hot` where it's picked up and used in the blade output to reference the HMR assets.

When I use DDEV, the regular exposed URL of my web container will be something like `https://myproject.ddev.site`. Using the current feature together with `server.hrm` I can get `viteServerDevUrl` to be `http://myproject.ddev.site:5173` _unless_ I set `server.hmr.protocol` to `wss`. 

I think [resolveDevServerUrl](https://github.com/laravel/vite-plugin/blob/2abd0b510b43061fab0027d5492547ce9a91dcad/src/index.ts#L391) should honor the given (valid) protocol string.

cheers

**Comment by timacdonald** [comment]
@Mtillmann sorry for the slow reply on this one.

Although the `https` is a valid protocol in general, I'm not sure it makes sense for the HMR server, as it does not run over HTTPS, and runs over websockets via `wss`.

- [`server.https`](https://vitejs.dev/config/server-options.html#server-https) can be used to make the server (HTTP interface) listen on `https`.
- [`server.hmr.protocol`](https://vitejs.dev/config/server-options.html#server-hmr) can be used to make the HMR server (websocket interface) listen on `wss`.

I'm really sorry if I'm missing something. If this still doesn't resolve the issue, can you let me know what your goal state is? I'm know you have written this above, but I'm still not clear what we are trying to achieve sorry.

**Comment by Mtillmann** [comment]
No worries, I know it's an edge case. 

In my environment (ddev) the dev site runs on https so I need the HMR URL to be https as well, otherwise HMR won't work. 

I thought this would be a more common issue with others who work with docker but apparently it's very specific to ddev.

I've written a small [middleware that lets one change the content of the public/hot file](https://gist.github.com/Mtillmann/ea4d3c0e24f30d1bc9504f1151d2d941), so that the HMR URL in the document no longer depends on the configuration of this plugin

**Comment by timacdonald** [comment]
Hey @Mtillmann I'm gonna close this one as I'm unable to replicate the issue.

If I do the following, for example...

```php
composer create-project laravel/laravel vite-test \
  && cd vite-test \
  && npm install \
  && echo "import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: ['resources/css/app.css', 'resources/js/app.js'],
            refresh: true,
        }),
    ],
    server: {
        https: true
    }
});" > vite.config.js \
  && npm run dev
```

The server is running on HTTPS.

<img width="419" alt="Screen Shot 2022-11-15 at 9 54 10 am" src="https://user-images.githubusercontent.com/24803032/201785050-d6b47084-f19a-4ae3-950a-415cbe0410a1.png">


Contents of the hot file...

```
https://[::1]:5173
```

If you can create a bare-bones reproduction repo showing the issue, we can re-open and consider the issue further.
