### ISSUE TITLE
New installation of WSL2, Docker and Laravel returning 404 on assets

### ISSUE THREAD

**Issue by lewislarsen** [laravel/vite-plugin#158]
- Laravel Vite Plugin Version: v0.6.0
- Laravel Version: v9.19
- Node Version: v16.18.0
- NPM Version: v8.19.2
- Host operating system: Windows
- Web Browser & Version: Firefox 106.0.2 (64-bit)
- Running in Sail / Docker: Sail
- Docker Desktop Version: 4.13.1 (90346)
- Windows Version:  Version 2H12 (OS Build 22000.1098)
- Ubuntu Version: Ubuntu 22.04.1 LTS

### Description:
My typical development environment is using macOS with Valet but I wanted to try out Sail on my Windows machine, however, after installing Breeze on a brand new installation of Laravel and running `sail npm run dev` I received a 404 in the browser for `http://localhost/css/app.css` and `http://localhost/js/app.js` when navigating to `http://localhost/login` on my Windows host.

I am able to navigate to `http://localhost:5173/` in the browser which displays the informative message, so we know that it is working. When using inspect element on the `/login` page the following URLs are returned as a 404: `http://localhost/css/app.css` & `http://localhost/js/app.js`.

In previous attempts I did try adding the following snippet to my `vite.config.js` file, however, it made no difference and the problem persisted.
```
  server: {
        hmr: {
            host: 'localhost',
        },
    },
```

Here is a repository of a recently created Sail laravel application that has broken asset rendering on my machine - https://github.com/lewislarsen/example-app.

Please let me know if you need any more additional information, it would be awesome if we could get this working. This is a fresh install of Docker, WSL2 and Laravel so in theory, it should all be working, but clearly, something is awry. 

### Steps To Reproduce:

(These steps reproduce the issue on my machine, I included every tiny step!)

1. Navigate to WSL in the terminal and install a copy of Laravel: `curl -s https://laravel.build/example-app | bash`
2. Ran commands to navigate to directory and build the container: `cd example-app && ./vendor/bin/sail up -d`
3. Ran migrations: `sail php artisan migrate`
4. Installed breeze: `sail composer require laravel/breeze:1.9.2` + `sail php artisan breeze:install` + `sail npm install` + `sail npm run dev`
5. Visited `http://localhost/login` in Firefox browser on Windows host to see the broken page.

The result is seeing this: https://i.imgur.com/FUZsIYh.png

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
