### ISSUE TITLE
`valetTls` should not be an option, certificates should be inferred from the environment

### ISSUE THREAD

**Issue by innocenzi** [laravel/vite-plugin#162]
## Discussion

I'm opening this issue to find a truly environment-agnostic solution to loading certificates. For reference, my implementation works in all three of the situations described in the context below.

https://github.com/innocenzi/laravel-vite/blob/main/vite-plugin-laravel/src/config.ts#L245

I think this should be implemented this way in this plugin, but that would be a breaking change ~~and I don't want to PR something that will not get merged~~ (I PR'd anyway lol).

The solution in my eyes would be to remove `valetTls`, and try to find the certificates from the environment: 
- If `VITE_DEV_SERVER_KEY`/`VITE_DEV_SERVER_CERT` is provided, use that
- If not, try to load Valet certificates (from `APP_URL` and not from the current working directory)
- If none of the above, do not throw an error

## Context

We have a team where two developers are using macOS and one is using Windows. We used my own Vite integration, but going forward I'd like to use the official one. 

My integration is environment-agnostic and has the ability to detect certificates from both Valet and Laragon. To work around this missing feature, I PR'd https://github.com/laravel/vite-plugin/pull/151, which introduces support for loading certificates through environment variables. 

But today, when the other macOS developer tried to start the server, he got an exception (Valet certificates not found), and we realized his project directory was not the same as his app URL (which makes sense in our context, the project powers two different apps).

When trying to solve this issue, we simply realized `valetTls` should not be an option because it's not environment-agnostic. Worse than that, my previous PR only works if `valetTls` is not set to `true`, because otherwise an exception will be thrown when its certificates will not be found, regardless of the existence of the certificates provided by the `.env`.

**Comment by driesvints** [comment]
Hey there. I see you've already opened a PR so let's see how that goes.
