### ISSUE TITLE
NPM Package laravel-vite-plugin files are inconsistent with this repo

### ISSUE THREAD

**Issue by ngstwr** [laravel/vite-plugin#168]
- Laravel Vite Plugin Version: 0.7.0
- Laravel Version: 9.32
- Node Version: 17.4.1
- NPM Version: 8.19.2
- Host operating system: macOS 
- Web Browser & Version: Chrome

### Description:

The package installed via npm command doesn't have the latest version changes. 

The added laravel-vite-plugin have the compiled index.js, which has following instead of what is supposed to be according to new version changelog:
`manifest: !ssr`

"Vite build" should create a custom-manifest.json file inside build directory, but it's still creating manifest.json. 

This is the PR that was merged with the latest version:
https://github.com/laravel/vite-plugin/pull/150

I checked the 'node_modules/laravel-vite-plugin/dist/index.js' inside my project directory, and found that it still has the old code:
`manifest: !ssr`

According to above PR and 'vite-plugin/blob/main/src/index.ts' file line number 127, 
the compiled index.js is supposed to have following:
`manifest: userConfig.build?.manifest ?? !ssr`

### Steps To Reproduce:
1. Install laravel-vite-plugin on your project:
yarn add laravel-vite-plugin -D

2. On vite.config.js, change manifest file name to 'custom-manifest.json'
build: {
    manifest: 'custom-manifest.json',
}

3. Build the application
yarn prod

**Comment by driesvints** [comment]
Okay I see it now. @jessarcher @timacdonald do you have any idea why the latest release doesn't have the correct files?

**Comment by ngstwr** [comment]
Is there any update on this? 

People must have been getting the stale index.js for the last 25 days!

If someone can point out the cause, perhaps I can contribute!

**Comment by timacdonald** [comment]
@ngstwr we are looking at it internally and will hopefully have it resolved shortly.

**Comment by timacdonald** [comment]
We've just pushed a new version and my testing is now showing me that the expected files are on NPM. Closing this one, but let us know if you are still having issues.
