### ISSUE TITLE
Run command after watching

### ISSUE THREAD

**Issue by ibnu-ja** [laravel/vite-plugin#172]
I export my ziggy route to JSON because I write my own ziggy-js plugin

But I want laravel to run artisan command when file is watched. Is it possible to do something like this?

```js
export default defineConfig({
  plugins: [
    //....
    laravel({
      refresh: [
        {
          condition: (file) => file.includes('routes/'),
          handle: () =>  //... do stuff
        }
      ]
    })
  ]
})
```

here's example from [innocenzi/laravel-vite](https://laravel-vite.dev/configuration/vite-plugin.html#example) plugin

example for [mix](https://github.com/tighten/ziggy/blob/main/README.md?plain=1#L537)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
