### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by usmanfarooqch** [laravel/vite-plugin#174]
- Laravel Vite Plugin Version: 0.6.1
- Laravel Version: ^9.19
- Node Version: 18.12.1
- NPM Version: 8.19.2
- Host operating system: Windows 10 Pro
- Web Browser & Version: Firefox version 107.6 (64bit)
- Running in Sail / Docker: No

### Description:
Package update issue

### Steps To Reproduce:
When I run command "npm outdated" it gives this. Even though i have run the command npm update
![image](https://user-images.githubusercontent.com/24714610/203938656-5713dbf8-8743-4767-9cce-720c397d2546.png)

**Comment by driesvints** [comment]
Hi there. Because you're working with 0.x versions the "x" is treated as a major version. You'll manually need to update your package.json to get the latest version.

**Comment by usmanfarooqch** [comment]
thanks @driesvints done updating
