### ISSUE TITLE
Type error TS2322(`resolvePageComponent` + `vite`'s `import.meta.glob`)

### ISSUE THREAD

**Issue by mt-u** [laravel/vite-plugin#177]
- Laravel Vite Plugin Version: 0.6.1
- Laravel Version: 9.39.0
- Node Version: 16.17.0
- NPM Version: 8.19.1
- Host operating system: Ubuntu22.04(Laravel Sail 8.1) on Docker on Ubuntu20.04(WSL2)
- Web Browser & Version: no relation
- Running in Sail / Docker: Sail

### Description:

I consulted on Discord about an issue #161 I created earlier, and got [a reply saying it might be a bug](https://discord.com/channels/297040613688475649/1041960162145079386/1042373675820781629), so I created this new one.

I think the cause of the error is that the type of the second arg of `resolvePageComponent` of `laravel-vite-plugin` and the return type of `import.meta.glob` of `vite` do not match.
Because if I use `import.meta.globEager` instead of `import.meta.glob` I get no error. (Unfortunately using `import.meta.globEager` causes no code-splitting for the pages, so this is not a workaround)

Currently I avoid type errors by calling `resolvePageComponent` on the javascript file, but hopefully the `laravel-vite-plugin` will fix it.
Thank you.

```typescript
// laravel-vite-plugin/inertia-helpers/index.d.ts
export declare function resolvePageComponent<T>(path: string, pages: Record<string, Promise<T> | (() => Promise<T>)>): Promise<T>;
```

```typescript
// vite/types/importGlob.d.ts
// https://github.com/vitejs/vite/blob/v3.2.4/packages/vite/types/importGlob.d.ts#L39

・・・

export interface ImportGlobFunction {
  /**
   * Import a list of files with a glob pattern.
   *
   * Overload 1: No generic provided, infer the type from `eager` and `as`
   */
  <
    Eager extends boolean,
    As extends string,
    T = As extends keyof KnownAsTypeMap ? KnownAsTypeMap[As] : unknown
  >(
    glob: string | string[],
    options?: ImportGlobOptions<Eager, As>
  ): (Eager extends true ? true : false) extends true
    ? Record<string, T>
    : Record<string, () => Promise<T>>
  /**
   * Import a list of files with a glob pattern.
   *
   * Overload 2: Module generic provided, infer the type from `eager: false`
   */
  <M>(
    glob: string | string[],
    options?: ImportGlobOptions<false, string>
  ): Record<string, () => Promise<M>>
  /**
   * Import a list of files with a glob pattern.
   *
   * Overload 3: Module generic provided, infer the type from `eager: true`
   */
  <M>(
    glob: string | string[],
    options: ImportGlobOptions<true, string>
  ): Record<string, M>
}

・・・

```

### Steps To Reproduce:
See #161.

**Comment by mt-u** [comment]
In addition to treating `resolvePageComponent` as JavaScript, I also avoid the error in the following way.

```typescript 
// app.ts

・・・

// impot DefineComponent type
import { createApp, h, type DefineComponent } from 'vue';

・・・

createInertiaApp({
    // specify the DefineComponent type to import.meta.glob
    resolve: name => resolvePageComponent(`../ts/Pages/${ name }.vue`, import.meta.glob<DefineComponent>('../ts/Pages/**/*.vue')),

・・・

});
```

**Comment by HaneulChile** [comment]
If I want to solve in react, what I need to use??

**Comment by timacdonald** [comment]
Hi folks, this function is generic so you can specify whatever you need.

```ts
// Lazy globing...

resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob<DefineComponent>('./Pages/**/*.vue')),

// Eager globing...

resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob<Promise<DefineComponent>>('./Pages/**/*.vue', { eager: true })),
```

**Comment by mt-u** [comment]
@timacdonald Thank you for your reply.
As I also mentioned above, I see that your solution avoids type errors.
However, this method is not documented. If this method is Laravel's official solution, I think it would be useful for many people to mention it in the docs.

By the way, when I use `import.meta.globEager`, Typescript's type inference works and I don't get an error even if I don't explicitly specify the type.
I think this is the result of the type definition of `resolvePageComponent` being properly adapted to Vite's `import.meta.globEager`.
Is it difficult to make type inference work for `import.meta.glob` as well?

**Comment by mt-u** [comment]
@HaneulChile Hi.
In the `inertia-react` type definition, `options.resolve` passed to `createInertiaApp` is [described as follows](https://github.com/inertiajs/inertia/blob/inertia-react%400.8.1/packages/inertia-react/index.d.ts).
```typescript
// node_modules/@inertiajs/inertia-react/index.d.ts

・・・

export type ReactComponent = React.ReactNode;

export type PageResolver = (name: string) => ReactComponent|Promise<ReactComponent>|NodeRequire // TODO: When shipped, replace with: Inertia.PageResolver<ReactComponent>

・・・

export type BaseInertiaAppOptions = {
    title?: HeadManagerTitleCallback,
    resolve: PageResolver,
}

・・・

export type InertiaAppOptionsForSSR<SharedProps> = BaseInertiaAppOptions & {
    id?: undefined,
    page: Inertia.Page|string,
    render: typeof renderToString,
    setup(options: SetupOptions<null, SharedProps>): ReactInstance
}

export function createInertiaApp<SharedProps = Inertia.PageProps>(options: InertiaAppOptionsForCSR<SharedProps>): Promise<CreateInertiaAppSetupReturnType>
export function createInertiaApp<SharedProps = Inertia.PageProps>(options: InertiaAppOptionsForSSR<SharedProps>): Promise<CreateInertiaAppSSRContent>

・・・
```
And the `PageResolver` is a `Promise` that returns a `ReactComponent` or a `ReactComponent` itself , which is also defined in `inertia-react`.
So if you use React, I guess you can solve it by using `ReactComponent`. (Like Vue3's `DefineComponent`)
Like this:
```typescript
// app.ts

・・・

// import ReactComponent type
import { createInertiaApp, type ReactComponent } from '@inertiajs/inertia-react';

・・・

createInertiaApp({

・・・

    // specify the ReactComponent type to import.meta.glob
    resolve: name => resolvePageComponent(`../ts/Pages/${ name }.tsx`, import.meta.glob<ReactComponent>('../ts/Pages/**/*.tsx')),

・・・

});
```

Please try it if you don't mind.
If you get good results, it would be helpful for everyone if you could let us know here.

**Comment by timacdonald** [comment]
@mt-u both of these functions are generic, so you have complete control over them. Without testing, i  would assume that the following would work without issue...

```
// Lazy globing...

resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob<ReactComponent>('./Pages/**/*.vue')),

// Eager globing...

resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob<Promise<ReactComponent>>('./Pages/**/*.vue', { eager: true })),
```

**Comment by mt-u** [comment]
@timacdonald Yes. You are completely right.
And I think it would be helpful for all users if your solution was featured in the Laravel docs.

Alternatively, I would be happy if the `resolvePageComponent` type definition was changed to work with Typescript's type inference, similar to the eager version of `import.meta.glob` (I mean `import.meta.globEager`, not `import.meta.glob('', { eager: true })`)

```typescript
// In this case you have to specify the type.
resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob<Promise<DefineComponent>>('./Pages/**/*.vue', { eager: true })),

// Not necessary in this case (Type Inference works)
resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.globEager('./Pages/**/*.vue')),
```

Thank you.

**Comment by timacdonald** [comment]
Laravel does not officially support Typescript, so we won't document that.

If you feel there is an improvement to be made, we would welcome a PR to improve the types.

**Comment by HaneulChile** [comment]
> @HaneulChile Hi. In the `inertia-react` type definition, `options.resolve` passed to `createInertiaApp` is [described as follows](https://github.com/inertiajs/inertia/blob/inertia-react%400.8.1/packages/inertia-react/index.d.ts).
> 
> ```ts
> // node_modules/@inertiajs/inertia-react/index.d.ts
> 
> ・・・
> 
> export type ReactComponent = React.ReactNode;
> 
> export type PageResolver = (name: string) => ReactComponent|Promise<ReactComponent>|NodeRequire // TODO: When shipped, replace with: Inertia.PageResolver<ReactComponent>
> 
> ・・・
> 
> export type BaseInertiaAppOptions = {
>     title?: HeadManagerTitleCallback,
>     resolve: PageResolver,
> }
> 
> ・・・
> 
> export type InertiaAppOptionsForSSR<SharedProps> = BaseInertiaAppOptions & {
>     id?: undefined,
>     page: Inertia.Page|string,
>     render: typeof renderToString,
>     setup(options: SetupOptions<null, SharedProps>): ReactInstance
> }
> 
> export function createInertiaApp<SharedProps = Inertia.PageProps>(options: InertiaAppOptionsForCSR<SharedProps>): Promise<CreateInertiaAppSetupReturnType>
> export function createInertiaApp<SharedProps = Inertia.PageProps>(options: InertiaAppOptionsForSSR<SharedProps>): Promise<CreateInertiaAppSSRContent>
> 
> ・・・
> ```
> 
> And the `PageResolver` is a `Promise` that returns a `ReactComponent` or a `ReactComponent` itself , which is also defined in `inertia-react`. So if you use React, I'm not familiar with React so I haven't been able to try it, but I guess you can solve it by using `ReactComponent`. (Like Vue3's `DefineComponent`) Like this:
> 
> ```ts
> // app.ts
> 
> ・・・
> 
> // import ReactComponent type
> import { createInertiaApp, type ReactComponent } from '@inertiajs/inertia-react';
> 
> ・・・
> 
> createInertiaApp({
> 
> ・・・
> 
>     // specify the ReactComponent type to import.meta.glob
>     resolve: name => resolvePageComponent(`../ts/Pages/${ name }.tsx`, import.meta.glob<ReactComponent>('../ts/Pages/**/*.tsx')),
> 
> ・・・
> 
> });
> ```
> 
> Please try it if you don't mind. If you get good results, it would be helpful for everyone if you could let us know here.

Worked perfect!!!. Thanks so much.
