### ISSUE TITLE
Cannot set baseUrl in development

### ISSUE THREAD

**Issue by lmiller1990** [laravel/vite-plugin#185]
- Laravel Vite Plugin Version: ^0.7.1
- Laravel Version: Not using Laravel
- Node Version: 16.x
- NPM Version: 7.x
- Host operating system: Linux and macOS
- Web Browser & Version: Chrome 106
- Running in Sail / Docker: No

### Description:

Cannot override `baseUrl` in development mode.

### Steps To Reproduce:

I'm having this issue when using this plugin with Cypress Component Testing. Discussion here: https://github.com/cypress-io/cypress/issues/22505#issuecomment-1339501748

The Cypress Vite Dev Server expects assets to be using the baseUrl of `/`. [Code here](https://github.com/cypress-io/cypress/blob/develop/npm/vite-dev-server/src/plugins/cypress.ts#L31).

I tried configuring this in my `vite.config.ts` but Laravel Vite defaults to `''` in non-build environments: https://github.com/laravel/vite-plugin/blob/5ec3ad4d8c2a33cde00b9bb36264fbef2fc3ea17/src/index.ts#L124

Can we change this to 

```js
base: userConfig.base ?? command === 'build' ? resolveBase(pluginConfig, assetUrl) : userConfig.base
```

Or will this break things?

**Comment by xsjcTony** [comment]
Not sure if I'm dumb, and I have no idea what's happening under the hood, but if I just look into the code:

Assuming you have configured `baseUrl`, then `userConfig.base` will have some string value that's not empty, thus the RHS of `??` won't be executed at all. So what's the difference of `: ''` and `: userConfig.base` in your proposed fix?

**Comment by lmiller1990** [comment]
Huh, I think you are right - this should be working. I'm not sure why it's not - I wonder if the `base` is overridden somewhere, after this is set. Let me take a look.

**Comment by lmiller1990** [comment]
Config:

```ts
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import laravel from 'laravel-vite-plugin'

// https://vitejs.dev/config/
export default defineConfig({
  base: '/',
  plugins: [react(), laravel.default([])],
})
```

I logged the `base`:

```
Base is  /build/
```

Without `base`:

```
Base is  /build/
```

The compiled code of

```js
userConfig.base ?? command === 'build' ? resolveBase(pluginConfig, assetUrl) : userConfig.base
```

is

```js
const base = ((_d = userConfig.base) !== null && _d !== void 0 ? _d : command === 'build') ? resolveBase(pluginConfig, assetUrl) : ''
```

Hard to grok. I replaced with

```js
const base = userConfig.base ? userConfig.base : command === 'build' ? resolveBase(pluginConfig, assetUrl) : userConfig.base
```

Now it works. So my question is, is there a bug due to the how the original code is written, or is that intended behavior? I suspect the former?

**Comment by xsjcTony** [comment]
Well, that's definitely something wrong with the `base`, I was originally set it to `/` but it results in `****/build/` in development. After I remove `base`, it results to `***/` which is I wanted, but it's true that no matter what you define, it will results in `***/build/`

**Comment by timacdonald** [comment]
I've just created a PR that should address this issue: https://github.com/laravel/vite-plugin/pull/188

Will close this and we can track the conversation in the PR.
