### ISSUE TITLE
You should not run the Vite HMR server in CI environments (in Github action)

### ISSUE THREAD

**Issue by sebsobseb** [laravel/vite-plugin#190]
- Laravel Vite Plugin Version: 0.7.3
- Laravel Version: 9.45.0
- Node Version: 16.x
- NPM Version: ~not sure, it's inside Github action
- Host operating system: `ubuntu-latest` (Github action)
- Web Browser & Version: N/A
- Running in Sail / Docker: No
- Vitest Version: 0.25.8

### Description:
I have a Github action which runs `npm run test:ci` (which runs `vitest run`). From what I understand in the Vitest docs, running `vitest run` will explicitly instruct Vitest to run once and not in 'watch mode': https://vitest.dev/guide/features.html#watch-mode.
But, `vite-plugin` triggers the following error:

```
Error: You should not run the Vite HMR server in CI environments. You should build your assets for production instead. To disable this ENV check you may set LARAVEL_BYPASS_ENV_CHECK=1
```
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/3526974/208932104-98ab0cba-8bbc-4b55-be11-d3d117f89d14.png">

I have no special vitest plugins or whatsoever. 

### Steps To Reproduce:

Just want to make sure: Is adding
```
env:
  LARAVEL_BYPASS_ENV_CHECK: 1
```
in the github action the only way of solving this?

**Comment by timacdonald** [comment]
@sebsobseb that is correct. You may set that env value if you would like that check to be skipped and allow npm run dev in CI environments.
