### ISSUE TITLE
Possibility to rename a file during the build

### ISSUE THREAD

**Issue by Buroob** [laravel/vite-plugin#191]
Hello !

I am updating my laravel 8 to version 9.
At the same time I replace Mix by ViteJs.

With Mix, I could rename a JS file (fingerprint.js to tools.js):

```javascript
mix.js('resources/js/app.js', 'public/js')
   .js('resources/js/fingerprint.js', 'public/js/tools.js')
   .version();`
```

After several searches and tries I did not manage to do the same with ViteJS

Is it possible please ?

Thanks for your help

**Comment by timacdonald** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
