### ISSUE TITLE
Random "No database selected" or "Your app key is missing" when using the devserver

### ISSUE THREAD

**Issue by MirazMac** [laravel/vite-plugin#192]
- Laravel Vite Plugin Version: 0.7.3
- Laravel Version: 9.48.0
- Node Version: 8.4.1
- NPM Version: 8.4.1
- Host operating system: Windows 10 21H2
- Web Browser & Version: Google Chrome 109.0.5414.75
- Running in Sail / Docker: No

### Description:
This is super strange. Whenever I use the dev server, randomly one of the following two error pops up:

**"No application encryption key has been specified"**

or
 
**SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected**

Or sometimes both of them together.

![image](https://user-images.githubusercontent.com/13865787/213909468-ef8cb360-c69e-4119-b087-ae8c83d94bef.png)

These error never occurs when I'm not using the dev server. 

Here's a screen recording of how it occurs.

https://user-images.githubusercontent.com/13865787/213909984-e18e81a7-e324-443b-b5f9-617a971578eb.mp4

### Steps To Reproduce:

I don't know how to reproduce this. For me, running "**vite**" and then browsing the site would do it. Mostly it occurs when I'm submitting a form. I haven't encountered the error without vite server yet.

For reference here's my vite.config.js
```JS

import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";
import mkcert from "vite-plugin-mkcert";
import legacy from "@vitejs/plugin-legacy";
import StimulusHMR from "vite-plugin-stimulus-hmr";
import * as path from "path";

export default defineConfig({
    plugins: [
        laravel({
            input: ["assets/javascript/app.js", "assets/sass/styles.scss"],
            refresh: [
                "resources/routes/**",
                "routes/**",
                "resources/views/**",
                "app/View/Components/**",
                "modules/**/Resources/views/**",
            ],
        }),
        mkcert(),
        StimulusHMR(),
        legacy({
            targets: ["defaults", "not IE 11"],
        }),
    ],
    css: {
        devSourcemap: true,
    },
    server: {
        https: true,
        host: "sai.local.site",
        open: "https://sai.local.site",
    },

    resolve: {
        alias: {
            "~bootstrap": path.resolve(__dirname, "node_modules/bootstrap"),
        },
    },
});

```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by MirazMac** [comment]
> Hi there,
> 
> Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
> 
> However, this issue will not be locked and everyone is still free to discuss solutions to your problem!
> 
> Thanks.

I'm fully aware of the nature of the issue. The only reason I have decided to post this here, because it only occurs while using this plugin. Thanks anyway.

**Comment by MirazMac** [comment]
I've figured out the 'cause of the issue. The issue is Laravel by default stores the loaded environment values using ``putenv()`` /``apache_setenv`` function which is not thread-safe.
When there's multiple requests are sent to the server, what happens is the following:

1st request: variables are not there -> load
2nd request: variables are there -> do not load
1st request: ends, cleans up variables
2nd request: use variable -> does not exist anymore, cleaned up by 1st request.

To fix this all you need to do is add the following in Laravel's
**bootstrap/app.php** (before initializing the app)

```php
Illuminate\Support\Env::disablePutenv();
```




This is was only occurring while using Vite because it sends a lot of ajax requests to the server.
