### ISSUE TITLE
Laravel vite with vite-pwa-plugin

### ISSUE THREAD

**Issue by LCD344** [laravel/vite-plugin#193]
- Laravel Vite Plugin Version: 0.7.3
- Laravel Version: 9.19
- Node Version: 18.12.1
- NPM Version: 9.2.0
- Host operating system:  Ubuntu 22.04.1 LTS
- Web Browser & Version: All
- Running in Sail / Docker: No

### Description:

I just finished converting a PWA from laravel mix to the vite plugin - everything was pretty straightforward, but the pwa isn't caching for offline use. 

you can see the vite setup here https://github.com/el-coop/app/blob/master/vite.config.js
the reason I'm making it build into the public directory and not into the build directory is because the pwa plugin doesn't include the "build" prefix in the cache manifest  (so it shows:  ```` re([{"revision":null,"url":"assets/_commonjsHelpers-edff4021.js"},{"revision":null,"url":"assets/_plugin-vue_export-helper-9d2f2293.js"},```` 

anyway, now the service worker works, but it never caches for offline use - I recently updated a different app similarly (but non-laravel app) and there the caching works...

### Steps To Reproduce:

Create a laravel/vue app and copy the next files

viteconfig:
https://github.com/el-coop/app/blob/master/vite.config.js
serviceWorker:
https://github.com/el-coop/app/blob/master/resources/js/serviceWorker/serviceWorker.js
registerServiceWorker:
https://github.com/el-coop/app/blob/master/resources/js/serviceWorker/registerServiceWorker.js
view:
https://github.com/el-coop/app/blob/master/resources/views/layouts/plain.blade.php

make some entry point for the app and include the registerServiceWorker file in it
You will see there is no "Content has been cached for offline use." console log - and no way to load the app when offline...
Also you can see this console log doesnt appear on the following url app.elcoop.io

thanks!

**Comment by Froxz** [comment]
@LCD344 what was the solution for the issue?

**Comment by LCD344** [comment]
> @LCD344 what was the solution for the issue?

I disabled the build folder - you can see in the files I linked - specifically in thee vite.config.js - for a working version.

**Comment by Froxz** [comment]
> > @LCD344 what was the solution for the issue?
> 
> I disabled the build folder - you can see in the files I linked - specifically in thee vite.config.js - for a working version.

Thanks
