### ISSUE TITLE
Quasar: [Vue warn]: Failed to resolve component: [Quasar component name]

### ISSUE THREAD

**Issue by 0x00A1FA** [laravel/vite-plugin#196]
- Laravel Vite Plugin Version: 0.7.3
- Laravel Version: 9.48
- Node Version: 18.12.1
- **PNPM** Version: 7.26.1
- Host operating system: Windows 10
- Web Browser & Version: Chromium 109
- Running in Sail / Docker: No

### Description:
I just migrated from the community plugin and I am getting errors in the console from Vue, in the form of:
```
[Vue warn]: Failed to resolve component: QLayout
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[stack trace goes here]
```

Note that after running `pnpm build`, it works (although the CSS is messed up).

It used to work before, but it's now broken. Does anyone know what's up?

### Steps To Reproduce:
`vite.config.ts`
```ts
import inertia from './resources/client/plugins/inertia-layout'
import laravel from 'laravel-vite-plugin'
import vue from '@vitejs/plugin-vue'
import { defineConfig } from 'vitest/config'
import { quasar, transformAssetUrls } from '@quasar/vite-plugin'

export default defineConfig({
  test: {
    include: ['resources/client/**/*.test.ts'],
  },
  plugins: [
    inertia(),
    quasar({
      autoImportComponentCase: 'pascal',
    }),
    vue({
      template: { transformAssetUrls },
    }),
    laravel({ input: 'resources/client/main.ts', refresh: true }),
  ],
  resolve: {
    alias: {
      '@': '/resources/client',
    },
  },
})
```

Simple Vue component:
```vue
<script setup lang="ts">
import type { QBtnProps } from 'quasar'

interface TooltipButtonProps extends QBtnProps {
  text: string
}

defineProps<TooltipButtonProps>()
</script>

<template>
  <QBtn color="deep-orange" push round>
    <QTooltip>
      {{ text }}
    </QTooltip>
  </QBtn>
</template>
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
