### ISSUE TITLE
@vite directive 

### ISSUE THREAD

**Issue by ebnibrahem** [laravel/vite-plugin#202]
when in change `outDir` in vite.config.js  defineConfig like below:

//vite.config.js
` import path from "path";
export default defineConfig({
    build: {
        outDir: path.join(__dirname, "/public/dashboards"),
    },
 plugins: [
        laravel({
            input: [
                'resources/js/app-admin.js',
],
            refresh: true,

        }),
... 
`

in blade page 
`@vite('resources/js/app-admin.js)`

in complied html code read from default public/build/assets/*  not as i adjust to read from path dashboards/assets/*

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
