### ISSUE TITLE
Initial page load fails when eager globing

### ISSUE THREAD

**Issue by Propaganistas** [laravel/vite-plugin#203]
- Laravel Vite Plugin Version: 0.7.4
- Laravel Version: 10.0.0
- Node Version: 19.2.0
- NPM Version: 8.19.3
- Host operating system: macOS 13.0.1
- Web Browser & Version: Firefox 109.0.1
- Running in Sail / Docker: No

### Description:

When instructing `import.meta.glob()` to eager load all modules, initial page loads fail because the `@vite()` Blade tag fails to locate the requested component path. The manifest's contents are generated differently: there are no entries for components individually anymore - only for entrypoints.

<img width="1495" alt="Scherm­afbeelding 2023-02-16 om 11 09 45" src="https://user-images.githubusercontent.com/6680176/219335286-a8268559-b630-46a3-adb0-1a7aab853d85.png">

See https://vitejs.dev/guide/features.html#glob-import

### Steps To Reproduce:

Install a fresh Laravel instance.
Install Laravel Breeze and the "Vue" stack

Change

```js
import.meta.glob('./Pages/**/*.vue')
```

to

```js
import.meta.glob('./Pages/**/*.vue', { eager: true })
```

Run `npm run build`

Open application in browser.

**Comment by driesvints** [comment]
Is this related to https://github.com/laravel/breeze/pull/258 ?

**Comment by Propaganistas** [comment]
It's related but approaches the subject from another angle.
Even though the code-splitting way is considered as current preference, the eager-load method (also supported by Vite) is currently broken.

**Comment by jessarcher** [comment]
Breeze comes with code splitting out of the box. If you change the page loading strategy in `app.js` to eager load, then you also need to change the `@vite` directive in `app.blade.php` to not separately load the `resources/js/{$page['component']}.vue` module.

**Comment by driesvints** [comment]
Thanks @jessarcher
