### ISSUE TITLE
Empty outDir on dev

### ISSUE THREAD

**Issue by jasonvarga** [laravel/vite-plugin#205]
When running `npm run dev`, is it possible to clear out the production build?

Here's my use case:

- Run `npm run build` to test that the production assets are used correctly.
- Laravel will use the production assets.
- Run `npm run dev` to do some dev work.
- Laravel notices the hot file, so it uses dev assets.
- Cancel the watcher (maybe accidentally)
- Laravel doesn't see the hot file, so it (correctly) serves the outdated production assets, and I get confused as to why things are acting weird.

If there was an option to empty the production build directory when we run `npm run dev`, that would solve this minor issue.

**Comment by timacdonald** [comment]
@jasonvarga we are aiming to keep the Laravel plugin as lightweight as possible and focused on making Vite work smoothly with Laravel. Although I can see that this feature being beneficial to some, it isn't directly related to Laravel and is more of a generic Vite plugin / feature - so leaning on composition of plugins is the way to go here I reckon.

One great thing about Vite is you can write tiny inline plugins for yourself. Here is a custom     plugin you can place in your `vite.config.js` file to achieve the functionality you are after. It essentially does an `rm -rf` on the build dir, so here is a big old disclaimer for anyone who sees this...

> **Warning** Use with extreme caution. This custom plugin will recursively delete directories on your machine which cannot be undone.


```js
import { defineConfig } from 'vite'
import fs from 'fs'
import laravel from 'laravel-vite-plugin'

export default defineConfig({
  plugins: [
    laravel({
      input: 'resources/js/app.js',
      ssr: 'resources/js/ssr.js',
    }),


    {
      configureServer() {
        process.on('exit', () => {
          console.log('Removing build directory.')

          if (fs.existsSync('public/build')) {
            fs.rmSync('public/build', {
              recursive: true,
              force: true
            })
          }
        })
      },
    },


  ],
})
```

**Comment by jessarcher** [comment]
You could also update the `dev` script in your `package.json` file if you want to clear any prod builds before starting the dev server.

```js
{
  "scripts": {
    "dev": "rm -rf public/build && vite",
    ...
  }
}
```

**Comment by jasonvarga** [comment]
Even simpler. Thanks!
