### ISSUE TITLE
Internal server error: Failed to resolve import "fsevents" from "node_modules/.vite/deps/laravel-vite-plugin.js?v=14d970e5". Does the file exist?

### ISSUE THREAD

**Issue by SylvanoTombo** [laravel/vite-plugin#206]
- Laravel Vite Plugin Version: "^0.7.4"
- Laravel Version: v9.41.0
- Node Version: v18.12.1
- NPM Version: 9.2.0
- Host operating system: Linux
- Web Browser & Version: ?
- Running in Sail / Docker: Sail|Docker

### Description:
When i run vite in dev, i got this message: "[vite] Internal server error: Failed to resolve import "fsevents" from "node_modules/.vite/deps/laravel-vite-plugin.js?v=14d970e5". Does the file exist?"
![Screenshot from 2023-03-13 16-48-31](https://user-images.githubusercontent.com/40351002/224721949-6e4b9624-59d8-414e-8273-cfebd6faa9ca.png)
![image](https://user-images.githubusercontent.com/40351002/224726685-b270de1e-2868-40d3-bd71-aa699fb1bae6.png)

### Steps To Reproduce:
Migrate laravel mix in to vite

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
