### ISSUE TITLE
Package development

### ISSUE THREAD

**Issue by dat-archielite** [laravel/vite-plugin#208]
Currently cannot use vite as package development

like:

```
laravel:
   packages:
       laravel-permissions:
           vite.config.js
vite.config.js
```

**Comment by timacdonald** [comment]
You'll need to provide more information for us to understand the bug.

This looks like some YAML, but we will need context. Feel free to provider more information and we can reopen the issue.

Also, remember that the Laravel vite plugin is meant for consumption by applications, not packages.
