### ISSUE TITLE
Refresh option disables HMR

### ISSUE THREAD

**Issue by PillFall** [laravel/vite-plugin#209]
- Laravel Vite Plugin Version: 0.7.4
- Laravel Version: 10.4.1
- Node Version: 19.6.0
- NPM Version: N/A
- Yarn Version: 1.22.10
- Host operating system: Manjaro 22.0.5 Linux 5.15.102
- Web Browser & Version: Chrome 111.0.5563.110
- Running in Sail / Docker: No

### Description:

If you activate the refresh option in the plugin, also using Vue. It deactivates the HMR for Vite, so if you change any file (e.g. resources/js/Pages/page.vue). Vite do not Hot Reload the page, and also do not compile when reload the page. For Vite to reload or recompile the missing module, you'll need to reload the server.

### Steps To Reproduce:

Create a new project with Vue, then create a page, activate refresh option, and modify the page (Not Blade).

**Comment by timacdonald** [comment]
@PillFall I'm unable to replicate this issue with a fresh installation of Laravel Breeze.

I am able to have both refresh for Blade files and HMR for Vue files working within the project.

Can you please create a minimal reproduction for this and we take a closer look?

```
laravel new bug-report --github="--public"
``` 

Ping me here and we will reopen the issue once we have a way to replicate the issue.

**Comment by timacdonald** [comment]
Hey, that is correct. You don't need to use that command specifically, it is just a shortcut.

**Comment by PillFall** [comment]
I created [https://github.com/PillFall/bug-report](this repo) which replicates the issue

**Comment by timacdonald** [comment]
I've just setup your repository. Made no changes. `yarn install` and `npm run dev` and can see that both refresh and HMR is working as expected.

I then commented out the refresh config and can see that refresh is no longer working but HMR is working.

I'm not entirely sure, but it seems this may be a issue with your setup.

**Comment by kfqr** [comment]
@PillFall is there any progress? I had the same issue on fresh install of laravel 10.5 node 16

**Comment by timacdonald** [comment]
@kfqr what operating system are you on? Could you fill out these details so we can see what matches up with @PillFall ?

```
- Laravel Vite Plugin Version: 
- Laravel Version: 
- Node Version: 
- NPM Version: 
- Yarn Version: 
- Host operating system: 
- Web Browser & Version: 
- Running in Sail / Docker: 
```

**Comment by kfqr** [comment]
- Laravel Vite Plugin Version: 0.7.4
- Laravel Version: 10.5.1
- Node Version: 16.16.0
- NPM Version: 8.11.0
- Yarn Version: 1.22.19
- Host operating system: Red Hat Enterprise Linux release 8.6 (VPS)
- Web Browser & Version: N/A
- Running in Sail / Docker: No

console 1
```
 composer create-project laravel/laravel testapp
 cd testapp/
 composer require laravel/breeze --dev
 php artisan breeze:install vue
 yarn
 yarn dev
```
console 2
`touch resources/views/app.blade.php` - _logs  at console 1 `[vite] page reload resources/views/app.blade.php`_
`touch resources/js/app.js` - _logs nothing_

**Comment by kfqr** [comment]
@timacdonald
just tested on 
- Node Version: 19.6.0
- Host operating system: Manjaro 22.0.5 
**no effect.**

And removing `refresh: true` not helps.

**Comment by PillFall** [comment]
> @PillFall is there any progress? I had the same issue on fresh install of laravel 10.5 node 16

I tested on Manjaro-ARM 23.02 Linux 5.15.92 and in Windows 10 22H2.

In Manjaro-ARM it doesn't work, and on Windows, it works sometimes. I still don't know why the issue arises, I believe it could be caused by the symlinks that I create in the repo.

But I don't know if @kfqr uses similar configuration to get the issue.
