### ISSUE TITLE
missing "/build" to background-image path after npm run build

### ISSUE THREAD

**Issue by yagogak** [laravel/vite-plugin#211]
### Vite Plugin Version

4.0.0

### Laravel Version

10.4.1

### Node Version

16.11.0

### NPM Version

8.1.4

### Operating System

macOS

### OS Version

12.6.3

### Web browser and version

Google Chrome Version 111.0.5563.146 (Build officiel) (x86_64)

### Running in Sail?

No

### Description

Hi, 

I use a secure valet environement for developpement. when i run the project locally everything is fine, path to css background image are resolved. But after a npm run build : 
 - css file is load from https://project.test/build/assets/app-377dcc0d.css
 but the image inside are loaded with the following path : 
` url(https://project.test/assets/header-landscape-dark-e7be311f.png)`
so i get a 404, because the vite build process put the file in /public/build/assets/ not /public/assets/

### Steps To Reproduce
- place an image in /resources/images
- add this image as a background-image in the main css file
- run npm run build

**Comment by hackel** [comment]
@yagogak What was your solution to this problem?

**Comment by yagogak** [comment]
mmm, a tricky ssl config in vite.config.js i rollback to the default config and this run perfetcly

**Comment by Rocketpilot** [comment]
@yagogak this solved a very similar issue I was having with web fonts, so thank you very much.
