### ISSUE TITLE
Vite not building manifest file properly during first deployment to production server

### ISSUE THREAD

**Issue by tanmoyfe** [laravel/vite-plugin#212]
### Vite Plugin Version

3.0.4

### Laravel Version

9.0

### Node Version

16.13.1

### NPM Version

8.1.2

### Operating System

Linux

### OS Version

Ubuntu 20.04 LTS

### Web browser and version

Google Chrome

### Running in Sail?

Sail

### Description

I migrated my laravel project from mix to vite. I'm using docker sail. I was able to migrate the project succesffuly. However, the problem occered when I deployed my changes to the AWS production server.
After the first time deployment. I received the error `Unable to locate file in Vite manifest: resources/css/base/pages/authentication.css`. This filepath is added in the **vite.config.js** file and after I redeployed, it's working without issue. 
After every change I deploy to the production server, the first deployment always has the issue of some css & js files being  missing in manifest. Second deployment usually fixes this issue.
***Please advice me on how to build vite manifest with single build command***

#### vite.config.js  
```javascript
import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";
import react from "@vitejs/plugin-react";
export default defineConfig({
    esbuild: {
        loader: "jsx",
    },
    optimizeDeps: {
        esbuildOptions: {
            loader: {
                ".js": "jsx",
            },
        },
    },
    plugins: [
        laravel({
            input: [
                "resources/css/pages/authentication.css",
                "resources/css/base/pages/authentication.css",
                "resources/css/app.css",
                "resources/js/core/app-root.js",
                // Other CSS & JSS files are here
            ],
            refresh: true,
        }),
        react(),
    ],
    build: {
       chunkSizeWarningLimit: 5120,
      },
    server: {
        hmr: {
            host: "localhost",
        },
    },
});
```

### Error Page 
![alt text][logo]

[logo]: https://i.ibb.co/mzVNmhw/vite-issue.png "Error message"

#### System configaration
 * PHP:  8.2
 * Vite :  3.0.4
 * Laravel:9 
 * Node.JS:-  16

### Steps To Reproduce

While I developing vite in local with **npm run dev** . This issue never happened. But this issue happened only with  **npm run build**
After run build command. Then it's worked. Sometimes it's also working fine. By single deploy

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
