### ISSUE TITLE
Undocumented `?direct` query string to make SASS work with `npm run dev`

### ISSUE THREAD

**Issue by uandco** [laravel/vite-plugin#213]
### Vite Plugin Version

0.7.4

### Laravel Version

10.8.0

### Node Version

18.14.2

### NPM Version

9.1.2

### Operating System

macOS

### OS Version

12.6.5

### Web browser and version

112.0.5615.49

### Running in Sail?

Custom Docker

### Description

Hi,

I struggled to find how to get SASS files accessed as CSS in dev mode.

In Blade:

```
@vite(['resources/js/app.js', 'resources/css/app.scss'])
```

In `vite.config.js`:

```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import fs from 'fs';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.scss',
                'resources/js/app.js'
            ],
            refresh: true,
        }),
    ],
    server: {
        https: {
            key: fs.readFileSync('./cert/key.pem'),
            cert: fs.readFileSync('./cert/cert.pem'),
        },
        host: '0.0.0.0',
        hmr: {
            host: 'droplets.docker.amazee.io'
        },
    },
});
```

When running `npm run dev`, Vite detects changes in the sass file and compiles it (I checked it was actually compiling OK by introducing syntax error in SASS `@extend` for example) but accessing `https://droplets.docker.amazee.io:5173/resources/css/app.scss` would just show the raw SASS file, not the compiled CSS.

Then I saw this in the npm log:
`2023-04-24 11:40:20 11:40:20 AM [vite] hmr update /resources/css/app.scss?direct`

And indeed, when accessing `https://droplets.docker.amazee.io:5173/resources/css/app.scss?direct` I get the compiled CSS.

Replacing the Blade `@vite` directive with this then works:

```
@vite(['resources/js/app.js', 'resources/css/app.scss?direct'])
```

I had a look at the documentation and I can't find anything mentioning you need that `?direct` query string to get the compiled version of the sass file when in dev mode. Am I missing something?

Thanks

### Steps To Reproduce

See above

**Comment by timacdonald** [comment]
Hi @uandco ,

We don't do anything specific for preprocessors such as SCSS. These features are Vite specific. I would refer to the Vite documentation for more information on using SCSS with Vite: https://vitejs.dev/guide/features.html#css-pre-processors

**Comment by uandco** [comment]
@timacdonald well, they just sent me back here… See https://github.com/vitejs/vite/issues/12967

**Comment by timacdonald** [comment]
Hey @uandco, reading over that thread it seems you are using an internal API by appending `?direct` to your entry point.

We don't intercept or do anything with `?direct`.

If you can create a bare bones reproduction repository of the issue, we can take a further look at the issue.

**Comment by uandco** [comment]
@timacdonald it's just a stock Laravel 10 install. If I don't add the `?direct` parameter to the `scss` entry in the `@vite` directive, it never loads the compiled sass.

**Comment by timacdonald** [comment]
@uandco I've just:

- Spun up a fresh breeze installation.
- Renamed `app.css` to `app.scss`.
- Installed sass via NPM.

Then while running NPM run dev, any changes I make in my `app.scss`, specifically using SASS syntax, is reflected instantly in the app via HMR.

Would need a reproduction repository to be able to dig in any further, I'm sorry.

**Comment by uandco** [comment]
thanks for looking into this @timacdonald .

I was looking at the source instead of actual changes in the page. I can see it updates the styles and changes the stylesheet's URL to something like `https://droplets.docker.amazee.io:5173/resources/css/app.scss?t=1682473348979`

Looking at the network tab, the preview of `app.scss?t=1682473348979` is correct and shows the compiled SASS, but opening this URL again shows the raw SASS code, which is very confusing.

I guess this is how the Vite server works, by creating throw away URLs?

Sorry about the confusion.

**Comment by timacdonald** [comment]
Something along those lines, yea. It replaces the URLs in the page, from memory.
