### ISSUE TITLE
Vite is very slow in window system. 

### ISSUE THREAD

**Issue by alokVishu** [laravel/vite-plugin#214]
### Vite Plugin Version

0.7.2

### Laravel Version

10.8

### Node Version

18.12.1

### NPM Version

8.19.2

### Operating System

Windows (WSL)

### OS Version

8.1.4

### Web browser and version

Version 112.0.5615.137 (Official Build) (arm64)

### Running in Sail?

No

### Description

My project is based on the Latest laravel and Vue 3. I'm running it on the Windows system. Vite takes almost 100x time to load the assets in the Windows system compare to MacOs.

Sometimes I cannot able to serve the build assets.

I have found a hack to serve it.

- first, run the generate build using yarn build
- now run yarn dev and php artisan serve
- and now change the URL with /build/
- and stop yarn dev in terminal

### Steps To Reproduce

Try to run a large project on a window system.

**Comment by driesvints** [comment]
> Try to run a large project on a window system.

Heya. This is pretty vague. What does "large" mean for you?

**Comment by alokVishu** [comment]
Hello @driesvints,

Thanks for the response.

I'm running this template: https://demos.pixinvent.com/vuexy-vuejs-laravel-admin-template/demo-1/dashboards/analytics

Thanks.

**Comment by ankurk91** [comment]
I believe you are running the npm command on Linux terminal.

WSL uses simulated file system which is slow

**Comment by timacdonald** [comment]
I would assume this is a underlying Vite issue, and unrelated to the Laravel plugin.

We'd need a reproduction repository that shows the issue only occurring when the Laravel plugin is installed to be able to look into this.

**Comment by timacdonald** [comment]
@alokVishu if you remove the Laravel plugin, does the build still take a long time?

**Comment by timacdonald** [comment]
Closing this one until we have more information. Feel free to let us know how you go.
