### ISSUE TITLE
Vite config file in TS format is no more supported by Vite plugin v0.7.5

### ISSUE THREAD

**Issue by daniser** [laravel/vite-plugin#218]
### Vite Plugin Version

0.7.5

### Laravel Version

10.10.0

### Node Version

18.16.0

### NPM Version

9.6.6

### Operating System

Windows (WSL)

### OS Version

10 Pro (22H2 19045.2965)

### Web browser and version

Google Chrome Version 113.0.5672.93 (Official Build) (x86-64)

### Running in Sail?

No

### Description

TypeScript throws following error for some reason:
![image](https://github.com/laravel/vite-plugin/assets/5169543/a9f1d747-92e4-4e52-8996-1daf77c06498)

### Steps To Reproduce

Use Laravel Vite plugin in Vite configuration file in TypeScript format (`vite.config.ts`).

**Comment by RobertBoes** [comment]
I've noticed the same issue, seems like the type exports have changed or are removed, this does work fine in a ts file:
```ts
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';
```
But importing the Vite plugin (`import laravel from 'laravel-vite-plugin';`) will throw errors in the IDE and tsc
```
Cannot find module 'laravel-vite-plugin' or its corresponding type declarations.
```

**Comment by timacdonald** [comment]
This this should get it sorted: https://github.com/laravel/vite-plugin/pull/220
