### ISSUE TITLE
some functions are missed in compiled files

### ISSUE THREAD

**Issue by wizard2000** [laravel/vite-plugin#222]
### Vite Plugin Version

1.6.1

### Laravel Version

10.4

### Node Version

10

### NPM Version

8

### Operating System

Windows (WSL)

### OS Version

10

### Web browser and version

google chrome 111

### Running in Sail?

No

### Description

In my project sometimes, I have to set a JS function for onclick or onchange  for an HTML elements or for an element created by JS functions. these functions are defined in JS files in assets directory.
if I run ' npm run build ' some of functions and variable would be missed during compiling process or their name would be changed (if i use these functions in the JS file that they are defined, they won't deleted from compiled files, but their name will be change) so my elements in html document cannot use these functions anymore by using onchange , onclick etc.

when i run ' npm run dev ' everything is ok but for production mode or when i want to deploy my project to a host i will faced to these problems.

so there are two problems:
1- functions which are only defined no used in the js file will be deleted in compiled files
2- name of function will be changed

### Steps To Reproduce

in vite.config i've set

`
minify: false,
or
minify: terser,
`
and change any other properties that i think they have effects on complied files in vite.config.

**Comment by nunomaduro** [comment]
You are using Node 8. You must ensure that Node.js 16+ and NPM are installed before running Vite and the Laravel plugin.

**Comment by wizard2000** [comment]
sorry 
i've used last version of npm node laravel php and etc

**Comment by timacdonald** [comment]
@wizard2000 you should assign the variables to the "window" object. I'm pretty sure this should preserve them and their original name.

```js
const myEventHandle = () => console.log('handled');

// assign to window to preserve them

window.myEventHandler;
```

**Comment by timacdonald** [comment]
Additionally, as this is not a bug within the Laravel integration itself I recommend asking for additional help in the following support channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks.
