### ISSUE TITLE
after build function will be missed

### ISSUE THREAD

**Issue by wizard2000** [laravel/vite-plugin#223]
### Vite Plugin Version

0.7.6

### Laravel Version

10.4.1

### Node Version

16.18

### NPM Version

8.19

### Operating System

Windows (WSL)

### OS Version

10

### Web browser and version

Google Chrome

### Running in Sail?

No

### Description

**I use last version of NPM NODE LARAVEL PHP and others**
As I said before functions that are not used in JS file  will be deleted also if these functions are used in the JS file (the file that function is defined) name of them will be change so I can not link element to these function by onclick and on change or etc.
please before close this topic check what i'm saying

example:
in app.js file:
`
function changeData(){
alert('any thing')
`

output file in build/assets/app-hashed.js:
`
//empty file ?!
`
nothing in output file

### Steps To Reproduce

by run 'npm run dev' everything is ok but in production mode for deploying on host or server we should use files which are created by 'build'
in vite.config i set:
`
build:{
minify:false
}
`
by setting minify to false , output file wont minified but unused function will deleted again

**Comment by timacdonald** [comment]
@wizard2000 I've replied to your original issue: https://github.com/laravel/vite-plugin/issues/222#issuecomment-1547018601
