### ISSUE TITLE
After version 0.7.4 Cannot find module 'laravel-vite-plugin' or its corresponding type declarations

### ISSUE THREAD

**Issue by iyashpal** [laravel/vite-plugin#225]
### Vite Plugin Version

0.7.6

### Laravel Version

10.8

### Node Version

18.14.2

### NPM Version

9.3.1

### Operating System

Windows (WSL)

### OS Version

11

### Web browser and version

Firefox Browser Developer V114.0b3

### Running in Sail?

No

### Description

Typescript is not able to find the type declarations after the version `0.7.4`

![image](https://github.com/laravel/vite-plugin/assets/19922707/ca71b0ff-b748-4f56-a1e8-3f69a374560e)

### Steps To Reproduce

- Change the `vite.config.js` to `vite.config.js`
- Install the any version after `0.7.4`
- On `vite.config.ts` file it will show red squiggly lines with message `Cannot find module 'laravel-vite-plugin' or its corresponding type declarations`

**Comment by timacdonald** [comment]
Please see https://github.com/laravel/vite-plugin/issues/218
