### ISSUE TITLE
Rollup Options in vite.config.js overrides settings for the laravel plugin

### ISSUE THREAD

**Issue by WordsofDefiance** [laravel/vite-plugin#226]
### Vite Plugin Version

^0.7.2

### Laravel Version

^10.8

### Node Version

16.13.0

### NPM Version

9.2.0

### Operating System

macOS

### OS Version

Ventura 13.1.1

### Web browser and version

Version 1.51.110 Chromium: 113.0.5672.77 (Official Build) (arm64)

### Running in Sail?

Custom Docker

### Description

I have an existing Laravel/Vue app that uses Vite for asset bundling. I need this app to also serve a library-style javascript file for people to load into their sites via `<script>` tags. 

The file needs to be available at a static URL that does not get a build-specific suffix. So `https://example.com/test.js` and not `https://example.com/build/assets/test-asdfsdf.js`.

I tried adding the following rollup options to my `vite.config.js` file:

```js
build: {
   rollupOptions: {
     input: [
       'resources/js/test.js',
     ],
     output: {
       dir: 'public',
       entryFileNames: 'test.js',
     },
   },
 },
```

This compiled the `test.js` file just fine, but it wipes out  the `public/build` directory. Commenting out the above code and running `npm run build` restores the expected `public/build` directory contents.

### Steps To Reproduce

1. New laravel installation
2. `$ echo "console.log('test');" > resources/js/test.js`
3. Add the following block to the vite config:

```js
 build: {
   rollupOptions: {
     input: [
       'resources/js/test.js',
     ],
     output: {
       dir: 'public',
       entryFileNames: 'test.js',
     },
   },
 },
```
4. `npm run build`

**Comment by WordsofDefiance** [comment]
It looks like this behavior might be defined [here](https://github.com/laravel/vite-plugin/blob/main/src/index.ts#L136).

I feel like this behavior is counter-intuitive and not documented. But we ended up solving the problem by adding a separate Vite config file and running two instead of one compilations. Note the `emptyOutDir` option:

```js
build: {
      emptyOutDir: false,
      rollupOptions: {
        input: [
          'test.js',
        ],
        output: {
          dir: 'public',
          entryFileNames: 'test.js',
        },
      },
    },
```

**Comment by jessarcher** [comment]
Originally, the Laravel plugin would enforce all of its own settings, however, some people needed to customise aspects of the configuration for various reasons. These days we respect any manual overrides from `vite.config.js`, but at the developer's risk.

In your case, a separate Vite config sounds like the only way to achieve what you need, and you probably don't even need the Laravel plugin in the second config.

Glad you got it sorted :+1:
