### ISSUE TITLE
`refresh` config overwritten by `server`

### ISSUE THREAD

**Issue by jeff-h** [laravel/vite-plugin#228]
### Vite Plugin Version

0.7.8

### Laravel Version

10.9.0

### Node Version

19.8.1

### NPM Version

9.5.1

### Operating System

macOS

### OS Version

13.3.1

### Web browser and version

Brave Version 1.51.114 Chromium: 113.0.5672.92 (Official Build) (arm64)

### Running in Sail?

No

### Description

I'm using [Indigo](https://indigostack.app) which generates an SSL cert for my site. I've followed the instructions at [Working With A Secure Development Server](https://laravel.com/docs/10.x/vite#working-with-a-secure-development-server) by adding a `server` section to my config, specifying the paths to my key and cert.

This works fine, but appears to have an unintended consequence causing Vite to watch the entire project, not just the [paths that it should](https://github.com/laravel/vite-plugin/blob/5da125928e760e7b7ed35b6ec34f154e3944219d/src/index.ts#L83-L88).

Any time a file is added/deleted (but not when a file is changed) in any directory of the entire project, Vite triggers a reload. Amongst other issues, this caused an infinite reload when my project wrote to `storage/debugbar`. 

I can fix that specifically by adding a `watch` config inside the server section like so:

```js
server: {
    ...
    watch: {
        ignored: [
        '**/storage/**',
    ],
},
```

but I'd much rather it just watch the proper paths.

Is this a one-off misconfiguration in my project, or is it a bug in how Vite-plugin merges its config?

<details><summary>My `vite.config.js`:</summary>
<p>

```js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import vuePlugin from '@vitejs/plugin-vue2';
import fs from 'fs';

const host = 'mysite.test';

export default defineConfig({
    server: {
        host,
        hmr: { host },
        https: {
            key: fs.readFileSync(`/Users/me/.indigo/ssl/key.pem`),
            cert: fs.readFileSync(`/Users/me/.indigo/ssl/cert.pem`),
        },
        watch: {
            ignored: [
              '**/storage/**',
            ],
        },
    },

    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
            ],
            refresh: true,
        }),
        vuePlugin({
            template: {
                transformAssetUrls: {
                    // The Vue plugin will re-write asset URLs, when referenced
                    // in Single File Components, to point to the Laravel web
                    // server. Setting this to `null` allows the Laravel plugin
                    // to instead re-write asset URLs to point to the Vite
                    // server instead.
                    base: null,

                    // The Vue plugin will parse absolute URLs and treat them
                    // as absolute paths to files on disk. Setting this to
                    // `false` will leave absolute URLs un-touched so they can
                    // reference assets in the public directory as expected.
                    includeAbsolute: false,
                },
            },
        }),
    ],

    resolve: {
        alias: {
            // '~bootstrap': path.resolve(__dirname, 'node_modules/bootstrap')
            vue: 'vue/dist/vue.esm.js',
        }
    },

});
```

</p>
</details>

### Steps To Reproduce

1. Ensure there's a key and cert file available for your site.
2. Configure Vite as specified.
3. Start Vite: `npm run dev`
4. add or delete a file anywhere in the project eg `cp README.md DUMMY.md`
5. Vite will trigger a page reload

**Comment by jeff-h** [comment]
Let me know what further info I should provide and I'll gladly add it.

**Comment by driesvints** [comment]
@jeff-h waiting on Jess and Tim to confirm and triage.

**Comment by timacdonald** [comment]
@jeff-h can you please set `refresh: false` and let us know if the issue occurs even when the refresh plugin is disabled?

I was unable to replicate the issue with a fresh installation and the following configuration. Editing the views refreshed the page as expected. `cp README.md DUMMY.md` did not trigger a refresh nor did editing files in `storage`.

```js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import fs from 'node:fs'

const host = 'vite-issue.test';

export default defineConfig({
    plugins: [
        laravel({
            input: ['resources/css/app.css', 'resources/js/app.js'],
            refresh: true,
        }),
    ],
    server: {
        host,
        hmr: { host },
        https: {
            key: fs.readFileSync(`/Users/tim/.config/valet/Certificates/vite-issue.test.key`),
            cert: fs.readFileSync(`/Users/tim/.config/valet/Certificates/vite-issue.test.crt`),
        },
    },
});
```

If you could provide a _minimum_ reproduction repository for us that replicates the issue, we can look into this further.

Thanks.

**Comment by timacdonald** [comment]
@jeff-h I've had a look at this one and I believe that this issue is actually related to a dependency loop caused by Tailwind CSS, rather than anything to do with you JS setup.

If you disable the `reload` option with `false`, the issue still occurs.

However, if I remove the Tailwind CSS classes in may `app.css` the issue disappears.

See this issue for more information: https://github.com/vitejs/vite/issues/9512#issuecomment-1208133617

**Comment by timacdonald** [comment]
I've also submitted a PR to the "Full Reload" plugin to help differentiate between a "Full Reload" triggered refresh and a Vite dependency refresh in the future: https://github.com/ElMassimo/vite-plugin-full-reload/pull/19/

**Comment by jeff-h** [comment]
Thanks @timacdonald — really appreciate your time digging into this!

**Comment by timacdonald** [comment]
No troubles at all.
