### ISSUE TITLE
After update laravel 9 to 10 version , the command npm run dev doesn't work and detect changes

### ISSUE THREAD

**Issue by TSerra-PT** [laravel/vite-plugin#229]
### Vite Plugin Version

4.3.9

### Laravel Version

10.13.2

### Node Version

20.2.0

### NPM Version

9.7.1

### Operating System

Windows (WSL)

### OS Version

10

### Web browser and version

Firefox 113.0.2

### Running in Sail?

No

### Description

Hi guys,

I started developing a project in laravel version 9. Then when Laravel released a new version (10) I updated my project to the new version.
After that, when I do "npm run dev" the project doesn't load and it doesn't detect any changes in the vue files.

![imagem](https://github.com/laravel/vite-plugin/assets/11211940/6d92472d-80cd-4626-ac40-9503a1ef1516)

This is my **vite.config.js** file

```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue';
import * as path from 'path';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/assets/js/app.js',
            ],
            refresh: true,
        }),
        vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false,
                },
            },
        }),
    ],
    css: {
        preprocessorOptions: {
            scss: {
                additionalData: `@import "./resources/assets/sass/_variables.scss";`
            }
        }
    },
    resolve: {
        alias: {
            vue: 'vue/dist/vue.esm-bundler.js',
            '~bootstrap': path.resolve(__dirname, 'node_modules/bootstrap'),
        },
    },
});
```
Can anyone help?

### Steps To Reproduce

Run the command "npm run dev"

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ArthurYdalgo** [comment]
any solution on this?

**Comment by ArthurYdalgo** [comment]
@TSerra-PT after a couple of hours struggling (5 to be more precise), I came up with a [response at Laracast](https://laracasts.com/discuss/channels/vite/no-hot-reload-with-new-laravel-vite?page=1&replyId=821030) and it finally hot reloaded (although it takes around 2 seconds for it to be detected).

The laravel was inside a 'back' directory in my repository, I'm not sure if it had anything to do with it.

- back
  - app/
  - config/
  - ...
  - resources/
  - ...
  - vite.config.js
 - other stuff

```
import { defineConfig } from 'vite';
import laravel, { refreshPaths } from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js', // In my case I'm using 'resources/js/app.jsx', but this is the original answer
            ],
            refresh: [
                ...refreshPaths,
                'app/Http/Livewire/**', // I changed this to 'resources/js/**', but this is the original answer
            ],
        }),
    ],
});
```
