### ISSUE TITLE
url stored in hot file does not follow vite conventions

### ISSUE THREAD

**Issue by hailwood** [laravel/vite-plugin#23]
- Laravel Vite Plugin Version: 0.2.2
- Laravel Version: 9.17.0
- Node Version: 18.0.0
- NPM Version: 8.6.0

### Description:
Right now we store the server IP in the hot file, either the IPV4 or the IPV6 variation.
This causes issues when using a self signed localhost valid certificate as we're telling the server to always load from 127.0.0.1.

Vite has [a resolveHostname method we should probably be using](https://github.com/vitejs/vite/blob/v2.9.12/packages/vite/src/node/utils.ts#L711). This will also ensure our loaded url matched the `dev server running at` output from vite.

### Steps To Reproduce:
1. Change the hostname via either `--host localhost` or `server.host`
2. Run `npm run hot`
3. Attempt to load a page using vite
4. Notice that it's requesting `127.0.0.1` instead

**Comment by jessarcher** [comment]
@hailwood That makes sense, I will have a look at this.

**Comment by hailwood** [comment]
@jessarcher I'll continue discussion directly on the PR :)

**Comment by driesvints** [comment]
Closing as a PR was opened.
