### ISSUE TITLE
npm run dev serves un-compiled javascript

### ISSUE THREAD

**Issue by Yannik** [laravel/vite-plugin#230]
### Vite Plugin Version

0.7.4

### Laravel Version

v10.13.5

### Node Version

18.16.0

### NPM Version

9.5.1

### Operating System

Linux

### OS Version

Fedora 38

### Web browser and version

Firefox 114.0

### Running in Sail?

Sail

### Description

I have an `resources/js/app.js` that looks like this:

```
import Swiper from 'swiper';
const swiper = new Swiper('.swiper', {
    loop: true
});
``` 

and `vite.config.js`:
```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    build: {
        sourcemap: true
    },
    plugins: [
        laravel({
            input: [
                'resources/sass/app.sass',
                'resources/js/app.js',
            ],
            refresh: true,
        }),
    ],
});
```

When running `npm run build`, the resulting `public/build/app-HASH.js` is correctly compiled and contains the code of the modules I have imported (e.g. swiper). 

However, when using `npm run build`, `resources/js/app.js` is served like this:
```
import Swiper from '/node_modules/.vite/deps/swiper.js?v=e222f854';
const swiper = new Swiper('.swiper', {
    loop: true
});
```

which results in the import not working. (`Uncaught SyntaxError: import declarations may only appear at top level of a module` error in console)

How can this be fixed so that the correct compiled javascript is served?

### Steps To Reproduce

see above

**Comment by Yannik** [comment]
@driesvints Sorry, but this is not helpful. I have already researched the problem and provided ample information about the issue in the OP. Please reopen.

**Comment by driesvints** [comment]
Please try a support channel first.

**Comment by driesvints** [comment]
Sorry misread this. @timacdonald do you have ideas here?

**Comment by Yannik** [comment]
I can add some additional information: Setting `type="module"` on the script tag circumvents the `Uncaught SyntaxError: import declarations may only appear at top level of a module` error mentioned in the OP. (The `@vite` directive uses `type=module` by default). 
However, that leads to its own problems. (i.e. if js must be loaded synchronously, as type=module is deferred by default, or if you are using global variables). 

I guess there must be some way to force *compiled* javascript to be delivered by `npm run dev`? (i.e. by using a special config option).

**Comment by driesvints** [comment]
Do you have this in your package.json?

https://github.com/laravel/laravel/blob/10.x/package.json#L3

**Comment by timacdonald** [comment]
@Yannik I'm unable to replicate this issue.

With a fresh install of Laravel Breeze, installing the "swiper" library, using Sail, and then copying your `vite.config.js` and `app.js` file, I see that the build is successful, as you have already stated, and the `npm run dev` version is working as expected.

As a heads up,  the dev server _never_ compiles the JS assets like the build command. So what you are seeing in the file is correct and is also what I see on my side, i.e.,

```js
import Swiper from '/node_modules/.vite/deps/swiper.js?v=e222f854';
const swiper = new Swiper('.swiper', {
    loop: true
});
```

This is how the dev server is supposed to work.

Lastly, the value of `"type"` in your `package.json` should not have any impact here. Vite assumes your project files is using MJS imports and exports.

If you could create a minimum reproduction project for us to verify the issue we will open this one back up and investigate the issue for you.
