### ISSUE TITLE
Dropping CJS support

### ISSUE THREAD

**Issue by benmccann** [laravel/vite-plugin#234]
Vite would like to drop CJS support, which means this project will need to. The documentation already uses ESM and I only found four projects that `require` the `laravel-vite-plugin`, so this should barely affect anyone. Is this a change we can go ahead and make or are there other things we should consider or that you have questions about?

I've sent PRs or files issues to migrate all the projects I could find:
- https://github.com/matteo-didone/laravel-comics/pull/1
- https://github.com/Jonathankli/laravel-cms/pull/1
- https://github.com/adityagus/alimenta-project/pull/1
- https://github.com/zordecmax/newcyweb/issues/5

**Comment by timacdonald** [comment]
Closing this and we can follow along with the PR. Thanks.
