### ISSUE TITLE
Vite v4 not compilating Tailwind classes with HMR

### ISSUE THREAD

**Issue by istratos** [laravel/vite-plugin#237]
### Vite Plugin Version

4.4.9

### Laravel Version

10.18.0

### Node Version

18.17.0

### NPM Version

9.6.7

### Operating System

Windows (WSL)

### OS Version

Windows 10 10.0.19045

### Web browser and version

Google Chrome Version 115.0.5790.171 (Official Build) (64 bits)

### Running in Sail?

No

### Description

I am doing a fresh installation of Laravel 10 along with Breeze (Blade stack) which comes with Vite v4 by default and already configured and ready to use. Just by going into any file while running `npm run dev` and adding a previously unused Tailwind class such as a background like `bg-orange-400` it will not compile the class and thus the styles won't be reflected in the view itself.

The HMR works fine. if I add a different class, change a text, add a HTML element or any other change it will automatically refresh the page and show me the changes, however as I explained, trying to utilize a Tailwind class that wasn't previously being compiled will result in the class not compiling and not showing (HMR will refresh as usual).

I found the following issue which is basically the same thing happening although this was on Vite v3:
https://github.com/vitejs/vite/issues/10677

### Steps To Reproduce

Execute `npm run dev`
Go into `resources/views/index.blade.php`
Swap `bg-orange-400` to any other bg class like `bg-cyan-400`
HMR will happen but it will not compile the class, resulting in no background.

https://github.com/istratos/vite-tailwind-issues

**Comment by timacdonald** [comment]
Hi @istratos, I've done the following:

```
git clone git@github.com:istratos/vite-tailwind-issues.git
cd vite-tailwind-issues
npm install
composer install
cp .env.example .env
php artisan key:generate
```

Then in 2 different tabs:

```
npm run dev
```

and 

```
php artisan serve
```

Then when opening the view and changing the class, the expected class is displayed.

https://github.com/laravel/vite-plugin/assets/24803032/fd8818ee-6349-4740-8df0-f28538ece24d


As you are on WSL, you may need to add the following server config:

<img width="709" alt="Screen Shot 2023-08-09 at 9 36 18 am" src="https://github.com/laravel/vite-plugin/assets/24803032/df6ecf10-6759-4cbd-85f2-33e0025851c1">

and if that still isn't working, you may need to look into the `server.watch.usePolling` option:

<img width="680" alt="Screen Shot 2023-08-09 at 9 37 00 am" src="https://github.com/laravel/vite-plugin/assets/24803032/729bc856-7eeb-4b0e-b11f-93a23e31c3f6">


Read more: https://laravel.com/docs/10.x/vite#configuring-hmr-in-sail-on-wsl2
