### ISSUE TITLE
add option to set subdomain

### ISSUE THREAD

**Issue by MordiSacks** [laravel/vite-plugin#240]
I have multiple vite configurations for different parts of my app.
this parts are seperated by subdomain e.g.
`example.com`
`mng.example.com`
`app.example.com`

when I run dev, it gives me the `APP_URL` value, it would be nice if the configuration would have an option to set a prefix or a custom function even
like this
```js
export default defineConfig({
    plugins: [
        laravel({
            url_prefix: 'mng.', // as prefix
            url: url => `mng.${url}`, // as function
            buildDirectory: 'build/mng',
            input: ['resources/builds/mng/js/app.js'],
            refresh: true,
        }),
    ]
});
```

**Comment by jessarcher** [comment]
Hi @MordiSacks,

The `APP_URL` environment variable is only used for the console output to remind developers that the Laravel dev server URL differs from the Vite dev server URL that is output above. I'm not sure it's worth adding extra configuration to customise this.

You can, however, modify the `APP_URL` environment variable when running the dev server, like this:

```sh
APP_URL=http://mng.example.com npm run dev
```

You could add this to the `scripts` section of your `package.json`:

```jsonc
  "scripts": {
    "dev": "APP_URL=http://mng.example.com vite",
    // ...
  }
```

**Comment by MordiSacks** [comment]
@jessarcher  Thank you for your answer.

My envs usually look like this
```env
APP_DOMAIN=example.test
APP_URL=https://${APP_DOMAIN}
```
I find this easy as I use the domain variable alot  

Would this work (as not sure when dotenv lib is engaged)
```json
  "scripts": {
    "dev": "APP_URL=https://mng.${APP_DOMAIN} vite",
    // ...
  }
```

**Comment by jessarcher** [comment]
I don't think that would work, as the variables from your `.env` file wouldn't be available to read (only set) at that point.

You could set `APP_URL` above the `defineConfig` function in your `vite.config.js` file, though:

```js
import { loadEnv } from 'vite'

const env = loadEnv('development', process.cwd(), ['APP_DOMAIN'])
process.env.APP_URL = `https://mng.${env.APP_DOMAIN}`
```

**Comment by MordiSacks** [comment]
Thank you!
