### ISSUE TITLE
duplicate stylesheet link

### ISSUE THREAD

**Issue by riazahmadshigri** [laravel/vite-plugin#242]
### Vite Plugin Version

0.7.2

### Laravel Version

10

### Node Version

1.1

### NPM Version

8.1.4

### Operating System

win

### OS Version

10

### Web browser and version

google chrome

### Running in Sail?

No

### Description

//vite.config.js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig( {
	plugins: [
		laravel( {
			input: [
				'resources/css/app.css',
				'resources/css/frontend.scss',
				'resources/js/app.js',
			],
			refresh: true,
		} ),
	],
} );

//header.blade.php

@vite('resources/css/frontend.scss')

///////its producing dublicate css

![Capture](https://github.com/laravel/vite-plugin/assets/73393691/867c49f1-96a7-4605-8540-a7d3421d63e0)

### Steps To Reproduce

unknown

**Comment by driesvints** [comment]
Does this also happen on v0.8.0?

**Comment by riazahmadshigri** [comment]
i don,t know my website is in production i realized it today and even i cannot test it with v8

**Comment by timacdonald** [comment]
@riazahmadshigri  on of these is a preload tag the other is a stylesheet tag. This is intentional.

See: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preload

**Comment by riazahmadshigri** [comment]
Yes I added custom attributes on stylesheet for better speed 

But the link with preload is duplicate it should not be there 

Because I added custom attributes following Laravel docs .....


Before adding those custom attributes  it was rendering two similar stylesheets links  with rel preload 

But now it is supposed to only render the link with custom attr which correct one
