### ISSUE TITLE
Vite refresh sometimes happens before `octane --watch`'s refresh

### ISSUE THREAD

**Issue by binaryfire** [laravel/vite-plugin#243]
### Vite Plugin Version

0.8.0

### Laravel Version

10.21.0

### Node Version

18.17.1

### NPM Version

9.6.7

### Operating System

Windows (WSL)

### OS Version

11

### Web browser and version

116.0.5845.141

### Running in Sail?

No

### Description

I'm running Octane / Swoole with `octane:start --watch` and Chokidar.

Both the Vite dev server and Octane correctly handle file changes. The problem is that it's always toss up as to which one will execute first. Which means that sometimes Vite refreshes before Octane and the latest changes aren't seen. I'm needing to save files twice to work around this.

It'd be good if we could add an optional delay to Vite to ensure Octane has a chance to reload its workers first.

### Steps To Reproduce

1. Create an Octane app and a Blade view that uses Vite
2. Install Chokidar and run `octane:start --watch`
3. Run `npm run dev`
4. Make changes to the Blade file and save. Check if the browser reflects those changes. Rinse and repeat. Eventually you'll be served stale content (i.e. content from before the Octane workers have restarted)

**Comment by jessarcher** [comment]
Hey @binaryfire,

The Laravel Vite plugin already supports this for refreshing on Blade changes. The docs are at https://laravel.com/docs/10.x/vite#blade-refreshing-on-save. Note that this doesn't apply to Vite's hot module replacement, but it sounds like you're specifically looking to delay the Blade refresh.
