### ISSUE TITLE
assets not loading in fresh laravel/sail project ubuntu 23.04

### ISSUE THREAD

**Issue by andriusgeci** [laravel/vite-plugin#244]
### Vite Plugin Version

4.0.0

### Laravel Version

10.4.1

### Node Version

18.13.0

### NPM Version

9.2.0

### Operating System

Linux

### OS Version

23.04

### Web browser and version

any browser

### Running in Sail?

Sail

### Description

Hi Im just learning laravel have setup a fresh project added some css and js but when I hit localhost no ccs or js is loaded everything else is working fine can some one please help here is my github  repo: https://github.com/andriusgeci/laracroft

### Steps To Reproduce

https://github.com/andriusgeci/laracroft

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
