### ISSUE TITLE
buildDirectory parameter doesn't work

### ISSUE THREAD

**Issue by xmoki** [laravel/vite-plugin#245]
### Vite Plugin Version

0.8.0

### Laravel Version

10.10

### Node Version

18.17.1

### NPM Version

10.1.0

### Operating System

Windows (WSL)

### OS Version

11

### Web browser and version

Edge 116.0.1938.81 (Official build) (64-bit)

### Running in Sail?

No

### Description

buildDirectory parameter in vite.config.js (laravel({ buildDirectory: 'assets', ...} ...) is ignored for manifest.json, when trying to access website, it searches for manifest.json in the wrong location, it still uses the default location which is 'build' ignoring the 'assets' i defined.

the only way i found for it to change default build location was changing it at app boot (AppServiceProvider):
public function boot(): void
{
    Vite::useBuildDirectory('assets');
}

### Steps To Reproduce

- change buildDirectory in vite laravel plugin / vite.config.js
- npm run build
- try to access website on a route which uses vite assets
- problem: server can't find manifest.json (wrong location)

**Comment by timacdonald** [comment]
@xmoki as you have already noted, if you customize the build directory in your config...

```
mport { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
 
export default defineConfig({
    plugins: [
        laravel({
            buildDirectory: 'assets', // Customize the build directory...
            // ...
        }),
    ],
});
```

You need to tell Vite in Laravel about the new build directory in a service provider...

```php
Illuminate\Support\Facades\Vite::useBuildDirectory('assets');
```

This is intentional behaviour and how we intend it to work.
