### ISSUE TITLE
Vite + Valet + Tailwind not working with HMR

### ISSUE THREAD

**Issue by Kazuto** [laravel/vite-plugin#248]
### Vite Plugin Version

0.8.1

### Laravel Version

10.25.1

### Node Version

17.9.1

### NPM Version

8.11.0

### Operating System

macOS

### OS Version

13.3.1 (22E261)

### Web browser and version

Brave Version 1.58.131 Chromium: 117.0.5938.92 (Official Build) (arm64)

### Running in Sail?

No

### Description

When running `yarn dev` the `app.css` is not processed and Tailwind classes are not being recognised, even though it's a completely new project.

![image](https://github.com/laravel/vite-plugin/assets/25435034/ea7de52b-d56b-42b5-a0d4-cc823fb93d2b)

![image](https://github.com/laravel/vite-plugin/assets/25435034/5c5d4fec-0371-4579-abdd-fc00ca47374e)

![image](https://github.com/laravel/vite-plugin/assets/25435034/8e23798f-3df0-41e7-935e-3e23fa877971)

`yarn build` on the other hand build the stylesheet file properly

### Steps To Reproduce

1. Create a new laravel project `laravel new project`
2. Link project with Valet `valet link project`
3. Install Tailwind according to https://tailwindcss.com/docs/guides/laravel
4. Remove default `<style></style>` from `welcome.blade.php`
5. Run `yarn dev`
6. Visit `project.test`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by timacdonald** [comment]
@Kazuto I see you are using the Brave browser. You might need to see this comment: https://github.com/laravel/vite-plugin/issues/47#issuecomment-1173198084
