### ISSUE TITLE
Need help to get a better solution for the build

### ISSUE THREAD

**Issue by khsuzan** [laravel/vite-plugin#250]
![image](https://github.com/laravel/vite-plugin/assets/59402978/89c90597-a692-4c9e-9ef7-e914554199c4)
I am using like this, I mean comment out to have build on root folder instead public. its just saves me to move the index.php file for single time. I always move index.php file from public to root public_html (shared hosting) folder. But
 before making dirty on the library code, it was  not possible to have index.php in the root, because styles and js was not loading on correct path. So is there any way to have both that I can move my index.php to any directory and no need to move the build folder from default location?

**Comment by timacdonald** [comment]
We don't support using the root directory as the build directory.
