### ISSUE TITLE
Vite 5.0 Support

### ISSUE THREAD

**Issue by gabrielrbarbosa** [laravel/vite-plugin#253]
```
$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: laravel-vite-plugin@0.8.0
npm ERR! Found: vite@5.0.0-beta.4
npm ERR! node_modules/vite
npm ERR!   dev vite@"^5.0.0-beta.4" from the root project
```

**Comment by driesvints** [comment]
No stable v5 has been released yet. I'm sure @jessarcher and @timacdonald are on this as soon this hits stable.

**Comment by driesvints** [comment]
Not yet. We've been too busy with other projects like Laravel Pulse. You'll see an update as soon as we have something to share.
