### ISSUE TITLE
putting files in input config as glob pattern works on ```npm run dev``` but fires an error on ```npm run build```

### ISSUE THREAD

**Issue by abdurrahmanseyidoglu** [laravel/vite-plugin#256]
### Vite Plugin Version

0.8.1

### Laravel Version

10.0

### Node Version

18.18.2

### NPM Version

9.8.1

### Operating System

Windows (WSL)

### OS Version

WSL 2 1.2.5 | Windows 10 Pro Version 21H2

### Web browser and version

Google Chrome Version 120.0.6073.0 (Official Build) dev (64-bit)

### Running in Sail?

No

### Description

inside ```input``` config "The path or paths of the entry points to compile" I want Vite to bundle my .scss or .js files and I have a lot of files to bundle so I use "glob pattern" to include them like this : 
``` 'resources/scss/**/*.scss' ```
and I link the styles in my pages like this : 
```@vite('resources/scss/pages/home-page.scss') ```
when I run Vite in development it runs and works without any problems ```npm run dev```

however when I want to build the assets with ```npm run build```
I get the following error message: ``` Could not resolve entry module "resources/scss/**/*.scss". ```

### Steps To Reproduce

``` 
import {defineConfig} from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/js/app.js',
                'resources/scss/**/*.scss',

            ],
            ssr: 'resources/js/ssr.js',
            refresh: true,
        }),
    ],
}); 
```

``` npm run build ```  will fire the error   ``` Could not resolve entry module "resources/scss/**/*.scss". ```

**Comment by jessarcher** [comment]
Hey @abdurrahmanseyidoglu,

The `input` property gets passed through to Vite's `build.rollupOptions.input` configuration option and is only used for the build, which would explain why it appears to work in dev mode. I'm guessing Rollup doesn't support glob patterns, presumably because they seem to have their own syntax that allows you to name the chunks.

https://vitejs.dev/config/build-options.html#build-rollupoptions
https://rollupjs.org/configuration-options/#input

You should be able to use the Node `glob` library directly in your config to resolve the files before passing them to the `input` option.

**Comment by abdurrahmanseyidoglu** [comment]
Thanks, I solve it like you said using ```glob``` like this : 

```
import {defineConfig} from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue';
import {glob, globSync, globStream, globStreamSync, Glob} from 'glob'

const patterns = [
    'resources/js/app.js',
    'public/assets/scss/**/*.scss',
    'public/assets/global_assets/js/index.js',
    'public/assets/js/**/*.js',
    'resources/global_scss/**/*.scss',
    'resources/js/app.js',
];
let filePaths = [];
for (const pattern of patterns) {
    const matches = await glob(pattern, {ignore: 'node_modules/**'});
    filePaths.push(...matches);
}
export default defineConfig({

    plugins: [
        laravel({
            input: filePaths,
            ssr: 'resources/js/ssr.js',
            refresh: true,
    }),
        vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false,
                },
            },
        }),
    ],
});

```
