### ISSUE TITLE
Not ready for Vite 5.0 (peer-dependency issue)

### ISSUE THREAD

**Issue by tobimori** [laravel/vite-plugin#261]
### Vite Plugin Version

0.8.1

### Laravel Version

-

### Node Version

21.1.0

### NPM Version

pnpm 8.10.2

### Operating System

macOS

### OS Version

/

### Web browser and version

/

### Running in Sail?

No

### Description

/	

### Steps To Reproduce

Install the plugin when vite 5.0 is installed

**Comment by gabrielrbarbosa** [comment]
#253

**Comment by driesvints** [comment]
We'll look into this soon.

**Comment by tobimori** [comment]
okay, why close the issue as completed then and not leave it open so other people know it's being worked on? 🤷🏿‍♂️

**Comment by benjivm** [comment]
driesvents: issue completed
the issue: ( ͡° ͜ʖ ͡°)
