### ISSUE TITLE
Support Vite `v5.0`

### ISSUE THREAD

**Issue by xsjcTony** [laravel/vite-plugin#262]
Please support Vite [`v5.0`](https://vitejs.dev/blog/announcing-vite5)

This [manifest breaking change](https://vitejs.dev/guide/migration.html#manifest-files-are-now-generated-in-vite-directory-by-default) may be worth a look.

**Comment by driesvints** [comment]
Please see previous issues. We'll work on this soon.

**Comment by xsjcTony** [comment]
@driesvints Thanks for the effort. I would like to suggest keep one of Vite 5.0 support issue open, so once anyone get here they'll notice that there is already an issue there for that, otherwise more duplicated issues are going to be created. Cheers
