### ISSUE TITLE
Support Vite.js v5

### ISSUE THREAD

**Issue by jimblue** [laravel/vite-plugin#264]
### Vite Plugin Version

0.8.1

### Laravel Version

10.32.1

### Node Version

20.8.1

### NPM Version

10.1.0

### Operating System

macOS

### OS Version

14.1.1

### Web browser and version

Firefox Developer Edition 120.0b9

### Running in Sail?

No

### Description

Vitejs 5 as been [release](https://vitejs.dev/blog/announcing-vite5.html) ! 🎉 

I've tested your plugin, and nothing is broken when using it with Vitejs 5.

It would be nice to update [peerDependencies in package.json](https://github.com/laravel/vite-plugin/blob/7abca675b82dd8a4fd23470f978110c3d083a0a1/package.json#L55) ! 😸 

### Steps To Reproduce

This is not really a bug...

**Comment by driesvints** [comment]
Heya thanks. Please see previous issues. We’re working on this and hoping to have something available soon

**Comment by pfuhrmann** [comment]
Maybe you could leave one issue open, that would prevent most people from opening duplicates.

**Comment by xsjcTony** [comment]
Exactly. Please keep one issue open

**Comment by jimblue** [comment]
> Heya thanks. Please see previous issues. We’re working on this and hoping to have something available soon

@driesvints, why do you close all issues. Imo you should keep one open issue, so people don't open new one...

**Comment by driesvints** [comment]
@jimblue there is an open issue right now
