### ISSUE TITLE
Server gives 404 for all routes

### ISSUE THREAD

**Issue by LowSociety** [laravel/vite-plugin#266]
### Vite Plugin Version

0.8.1

### Laravel Version

10.31.0

### Node Version

20.8.0

### NPM Version

10.2.4

### Operating System

macOS

### OS Version

Sonoma 14.1

### Web browser and version

Google Chrome Version 119.0.6045.105 (Official Build) (arm64)

### Running in Sail?

No

### Description

No matter what route I try to access, Vite + laravel-vite-plugin gives me a response status of 404 and the fallback page:

> This is the Vite development server that provides Hot Module Replacement for your Laravel application.

It seems like no matter what URL I pass to the app, it hits this line where `req.url === 'index.htm'` (unless I specify a file like http://localhost:5173/index2.htm):

https://github.com/laravel/vite-plugin/blob/7abca675b82dd8a4fd23470f978110c3d083a0a1/src/index.ts#L234

### Steps To Reproduce

```
composer create-project laravel/laravel example-app
cd example-app
yarn
yarn dev
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
