### ISSUE TITLE
Support for changing defaultAliases

### ISSUE THREAD

**Issue by 9x3l6** [laravel/vite-plugin#272]
Hi there, I'm working on ann app where my configuration requires me to update the alias value. My question is, Does the current codebase support modifying the values found in `defaultAliases` and how to do that? Would it be possible to pass in a config for multiple application aliases?

The values I need to update are here https://github.com/laravel/vite-plugin/blob/main/src/index.ts#L122 In case where I need to use `~` instead of `@` and another case where I need to use a custom path instead of `'resources/js` I need to set `/resources/react` or `/resources/vue`.

Please advise what is a key I can set in the config object used for `laravel()`

For a vue app this is the default:
```
laravel({
    input: 'resources/js/app.ts',
    ssr: 'resources/js/ssr.ts',
    refresh: true,
}),
```

I'd like to change it to be this:
```
laravel({
    input: 'resources/vue/app.ts',
    ssr: 'resources/vue/ssr.ts',
    refresh: true,
}),
```

Would it be possible config for multiple applications? I would like that very much.

I need this functionality very badly please advise. I've been looking at the code a little bit and am not sure if it's already doing this or if it still needs to be added and/or how to go about making that happen. Thank you for your help!

**Comment by timacdonald** [comment]
Please see the docs: https://laravel.com/docs/10.x/vite#aliases
