### ISSUE TITLE
The "code" argument must be of type number. Received type string ('SIGINT')

### ISSUE THREAD

**Issue by zunnur-trinovik** [laravel/vite-plugin#274]
### Vite Plugin Version

1.0.0

### Laravel Version

10.38.0

### Node Version

v20.10.0

### NPM Version

10.2.3

### Operating System

Windows (WSL)

### OS Version

11

### Web browser and version

Version 1.61.104 Chromium: 120.0.6099.115 (Official Build)  (64-bit)

### Running in Sail?

No

### Description

Type error shown when stopping the running `npm run dev` using `ctrl + c`
```
node:internal/validators:95
      throw new ERR_INVALID_ARG_TYPE(name, 'number', value);
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('SIGINT')
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at process.exit (node:internal/process/per_thread:188:24)
    at process.emit (node:events:514:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### Steps To Reproduce

1. Run `npm run dev` on terminal
2. Click `ctrl + c` on terminal.

**Comment by timacdonald** [comment]
Thanks! Fix for this coming with https://github.com/laravel/vite-plugin/pull/276
