### ISSUE TITLE
Vite 5 & `laravel-vite-plugin` v1 is exploding on build server

### ISSUE THREAD

**Issue by simonhamp** [laravel/vite-plugin#277]
### Vite Plugin Version

1.0.0

### Laravel Version

10.37.3

### Node Version

20.10.0

### NPM Version

10.2.5

### Operating System

Linux

### OS Version

Ubuntu 22.04.1 LTS

### Web browser and version

Irrelevant for this issue

### Running in Sail?

No

### Description

I've just deployed my upgraded app to the build server, newly with `vite@5.0.10` and `laravel-vite-plugin@1.0.0`, and am hitting the following:

```
✘ [ERROR] "laravel-vite-plugin" resolved to an ESM file. ESM file cannot be loaded by `require`. See https://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details. [plugin externalize-deps]
```

### Steps To Reproduce

Note this also happens locally (M1 Macbook Pro, Sonoma 14.1, node 20.8.1 and npm 10.1.0). So I'm not sure really sure how to reproduce.

All I did was upgrade Vite to the latest version along with its one main dependent, `laravel-vite-plugin`

**Comment by simonhamp** [comment]
In my case, renaming the Vite config file fixed it

```diff
- vite.config.js
+ vite.config.mjs
```

**Comment by timacdonald** [comment]
Hi @simonhamp,

Did you follow the steps outlined in the [Upgrade Guide](https://github.com/laravel/vite-plugin/blob/1.x/UPGRADE.md)?

Specifically:

> Ensure your package.json contains "type": "module".
>
> Run the following command in your project's root directory or anywhere you have your package.json files:

```
npm pkg set type=module
```
> You may also need to rename any *.js configuration files that contain CJS, which is the older-style Node-flavored var plugin = require('plugin') syntax, to filename.cjs after making this change.

**Comment by simonhamp** [comment]
Yep I tried just adding `"type": "module"` but bumped into some issue with PostCSS still using `require()` somewhere

Haven't debugged further but will. It's surely not a `laravel-vite-plugin` issue.

Felt it was worth recording though in case anyone else came across the issue and went hunting.

**Comment by timacdonald** [comment]
For sure. The whole migration from CJS to MJS in the JS ecosystem is a super painful.

Easy fix is to rename any files that use the `require` syntax to `{filename}.cjs`.

But I'd be pushing to just move everything over to JS import / export where you can and be done with it all (hopefully 🤞)

**Comment by simonhamp** [comment]
Totally. That's where I'm heading, just need to hunt that down.
