### ISSUE TITLE
v1 doesn't work with bun anymore

### ISSUE THREAD

**Issue by larskoole** [laravel/vite-plugin#278]
### Vite Plugin Version

1.0.0

### Laravel Version

10.38.0

### Node Version

bun 1.0.18

### NPM Version

bun 1.0.18

### Operating System

macOS

### OS Version

latest

### Web browser and version

chrome latest x86

### Running in Sail?

No

### Description

`bun run dev` used to work but now doesn't.

The error it throws is:
```
error when starting dev server:
NotImplementedError: node:http2 createSecureServer is not yet implemented in Bun. Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/887
```

I understand that it's a limitation in Bun but I'm wondering why it's not working anymore. It used to work like a charm before laravel-vite-plugin v1.

### Steps To Reproduce

Plain Laravel project using `bun run dev` instead of npm to build assets.

**Comment by driesvints** [comment]
I'm very sorry but I feel like this is out of scope for this project. It's best that you try a support channel and if you find a fix feel free to attempt a PR.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by larskoole** [comment]
For the people looking for a temp solution, add this to your vite config:
```
server: {
    proxy: {}
},
```

**Comment by timacdonald** [comment]
@larskoole this is because Vite 5 uses a function that Bun has not yet implemented, so it an issue upstream as we never call this method.

https://github.com/oven-sh/bun/issues/887

Hopefully once Bun implements that function, Vite and Bun will work together again.

You can always stay on the `0.x` version of the `laravel-vite-plugin` which uses Vite 4.
