### ISSUE TITLE
Issues Migrating from Webpack to Vite in a Laravel, Inertia, and Vue 2 Application

### ISSUE THREAD

**Issue by mandudeman** [laravel/vite-plugin#280]
### Vite Plugin Version

5.0.11

### Laravel Version

8.41.0

### Node Version

18.8.0

### NPM Version

8.18.0

### Operating System

Windows (WSL)

### OS Version

10

### Web browser and version

Google Chrome Version 120.0.6099.217 (Official Build) (64-bit)

### Running in Sail?

No

### Description

I'm currently working on migrating an existing application from Webpack to Vite. The application is built with Laravel, Inertia, and Vue 2. Following the official documentation, I successfully configured the `vite.config.mjs` file, updated the `app.js`, and modified the `app.blade.php`.

However, I've encountered a significant issue: after starting the development server with `npm run dev`, the application correctly renders the landing page. But when I attempt to navigate to other parts of the app, specifically by clicking the Login button or accessing different routes, the pages fail to load. Instead of rendering the requested content, the application only displays the text: **@vite('resources/js/app.js')**. This issue persists across all components and routes beyond the landing page.

I've double-checked my configurations and ensured that the Vite server is running, but the problem persists. I'm looking for insights or suggestions on what might be causing this issue and how to resolve it.

Any advice or guidance would be greatly appreciated. Thank you!

### Steps To Reproduce

`// vite.config.js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue2';
import path from 'path';
import postCssImport from 'postcss-import';
import tailwindcss from 'tailwindcss';
import autoprefixer from 'autoprefixer';

export default defineConfig({
  plugins: [
    laravel({
      input: ['resources/js/app.js', 'resources/js/app.jsx'],
      refresh: true,
      //detectTsl: 'ez-review.com',
    }),
    vue({
      template: {
          base: null,
          includeAbsolute: false,
      }     
    }),
    // Include additional plugins if needed
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'resources/js'),
    },
  },
  css: {
    postcss: {
      plugins: [
        postCssImport,
        tailwindcss,
        autoprefixer,
        // Add other PostCSS plugins here if needed
      ],
    },
  },
  // Additional configurations for production environment
  build: {
    // ... your production build specific configurations
    
    // generate .vite/manifest.json in outDir
    manifest: true,
    rollupOptions: {
      // overwrite default .html entry
      input: '/resources/js/app.js',
   },
  }
});
`

**Comment by mandudeman** [comment]
//app.js
require('./bootstrap');

// Import modules...
import Vue from 'vue';
import Vuex from 'vuex';
import NProgress from 'nprogress';
import { Inertia } from '@inertiajs/inertia';
import { App as InertiaApp, plugin as InertiaPlugin } from '@inertiajs/inertia-vue';
import PortalVue from 'portal-vue';
import PrimeVue from 'primevue/config';
import VueClipboard from 'vue-clipboard2';
import ToastService from 'primevue/toastservice';
import VueGoodTablePlugin from 'vue-good-table';
import ConfirmationService from 'primevue/confirmationservice';
import Vuelidate from 'vuelidate';
import VueMeta from 'vue-meta';
import store from './Store';
import VueCtkDateTimePicker from 'vue-ctk-date-time-picker';
import vSelect from 'vue-select';
import VueAwesomeSwiper from 'vue-awesome-swiper';
import VCalendar from 'v-calendar';
import VOffline from 'v-offline';
import VueSweetalert2 from 'vue-sweetalert2';
import './bootstrap';
import '../css/app.css'; 

Vue.use(VueSweetalert2);
Vue.use(VOffline);
Vue.component('v-select', vSelect)
Vue.component('VueCtkDateTimePicker', VueCtkDateTimePicker);
Vue.use(VueAwesomeSwiper);
Vue.use(Vuex);
Vue.use(InertiaPlugin);
Vue.use(PortalVue);
Vue.use(PrimeVue);
Vue.use(ToastService);
Vue.use(ConfirmationService);
Vue.use(VueGoodTablePlugin);
Vue.use(VueClipboard);
Vue.use(Vuelidate);
Vue.use(VCalendar);
Vue.use(VueMeta, {
    refreshOnceOnNavigation: true
});

Vue.config.productionTip = false;

Vue.mixin({ methods: { route } });

Vue.mixin(require('./Mixins/translate'));
Vue.mixin(require('./Mixins/hex2rgba'));

Vue.filter('convertToCharacter', function (value) {
    let characters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'];
    return characters[value];
});

NProgress.configure({
    template: '<div class="bar" role="bar"><div class="peg"></div></div>' +
        '<div class="spinner" role="spinner">' +
        '<div class="bg-green-700 rounded-sm shadow flex items-center justify-center gap-4 px-3 py-1">' +
        '<div class="spinner-icon"></div><div class="text-xs text-white">Loading</div>' +
        '</div></div>'
});

const app = document.getElementById('app');

let timeout = null;

Inertia.on('start', () => {
    timeout = setTimeout(() => NProgress.start(), 250)
});

Inertia.on('progress', (event) => {
    if (NProgress.isStarted() && event.detail.progress.percentage) {
        NProgress.set((event.detail.progress.percentage / 100) * 0.9)
    }
});

Inertia.on('finish', (event) => {
    clearTimeout(timeout)
    if (!NProgress.isStarted()) {
        return
    } else if (event.detail.visit.completed) {
        NProgress.done()
    } else if (event.detail.visit.interrupted) {
        NProgress.set(0)
    } else if (event.detail.visit.cancelled) {
        NProgress.done()
        NProgress.remove()
    }
});

window.App = new Vue({
    store,
    metaInfo: {
        title: '',
        titleTemplate: '%s'
    },
    render: (h) =>
        h(InertiaApp, {
            props: {
                initialPage: JSON.parse(app.dataset.page),
                // Change it to include the file extension, like .vue or .js:
                // import(`./Pages/${name}.vue`) // or .js, depending on your file type

                resolveComponent: async (name) => (await import(`./Pages/${name}.vue`)).default,
            },
        }),
}).$mount(app);

**Comment by mandudeman** [comment]
//app.blade.php
<!DOCTYPE html>
<html dir="{{ app(\App\Settings\LocalizationSettings::class)->default_direction }}" lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'EZReview') }}</title>
        <meta name="description" content="{{ app(\App\Settings\SiteSettings::class)->seo_description }}">
        <link rel="icon" href="{{ url('storage/'.app(\App\Settings\SiteSettings::class)->favicon_path) }}">

        
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link rel="stylesheet" href="{{ config('ez.default_font_url') }}">

        
        <link rel="stylesheet" href="{{ asset('vendor/primeicons/primeicons.css') }}">
        <link rel="stylesheet" href="{{ asset('vendor/nprogress/nprogress.css') }}">
        <link rel="stylesheet" href="{{ asset('vendor/katex/katex.min.css') }}">
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">
        <link rel="stylesheet" href="{{ asset('css/rationalization.css') }}">
        <style>
            :root {
                /* Custom Theme Configuration */
                --custom-font: "{{ config('ez.default_font') }}";
                --primary-color: {{ '#'.app(\App\Settings\ThemeSettings::class)->primary_color }};
                --secondary-color: {{ '#'.app(\App\Settings\ThemeSettings::class)->secondary_color }};
            }
        </style>

        
        @routes
        <script>
            window.CKEditorURL = "{{ asset('vendor/ckeditor/ckeditor.js') }}";
        </script>
        <script src="{{ asset('vendor/katex/katex.min.js') }}"></script>
        <script src="{{ asset('vendor/katex/contrib/auto-render.min.js') }}"></script>

        @vite('resources/js/app.js')
    </head>
    <body class="font-sans antialiased bg-gray-100 dark:bg-gray-900">
        @inertia
    </body>
</html>

**Comment by timacdonald** [comment]
@mandudeman Vite does not support the `require` syntax. I can see in your `app.js` you still use that.

```js
require('./bootstrap');
```

You will need to ensure that your application has completely migrations to ESM imports.

https://github.com/laravel/vite-plugin/blob/1.x/UPGRADE.md#vite-compatible-imports
