### ISSUE TITLE
npm run build fail on centos

### ISSUE THREAD

**Issue by Mancera63** [laravel/vite-plugin#289]
### Vite Plugin Version

1.0.0

### Laravel Version

10.10

### Node Version

16.20.2

### NPM Version

8.19.4

### Operating System

Linux

### OS Version

CentOS Linux 7 (DigitalOcean)

### Web browser and version

Safari 17.2.1 (19617.1.17.11.12)

### Running in Sail?

No

### Description

My laravel project works fine locally when I run **npm run dev** but i'm trying to deploy on production and when I try to run **npm run build** getting:

![image](https://github.com/laravel/vite-plugin/assets/20950887/9c79130b-cf6e-4754-90ce-886c766ee58f)

### Steps To Reproduce

-- git clone myproyect.git
-- composer install
-- npm install
-- npm run build

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by timacdonald** [comment]
Hi there,

The Vite plugin, and Vite itself, now only supports Node 18 or Node 20+.

You will need to upgrade your Node version from 16 to one of these supported versions.
