### ISSUE TITLE
Plugin compatibility with vite 5.1

### ISSUE THREAD

**Issue by LaTableRouge** [laravel/vite-plugin#291]
Hello,

I've tried to update vite on a new laravel project (as I do on other stacks), and the new version of vite include the manifest.json inside a /.vite folder.

The laravel-vite-plugin is searching for a file that don't exist because the manifest is not at the root of the build folder.
Can you make a little condition that the plugin can search for both cases ?
Like so : 

- /public/build/manifest.json
- /public/build/.vite/manifest.json

Best regards

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by timacdonald** [comment]
@LaTableRouge, the `laravel/vite-plugin` explicitly does not use the `.vite` directory. This was done to ensure upgrading was not a breaking change.

There isn't any need to look elsewhere. If you are using the `vite-plugin` things will just work. If you are using Vite without our plugin you will need to do things manually.
