### ISSUE TITLE
Problem when running `vite build --watch`

### ISSUE THREAD

**Issue by sgtcoder** [laravel/vite-plugin#299]
### Vite Plugin Version

1.0.4

### Laravel Version

11.14.0

### Node Version

v20.5.1

### NPM Version

10.8.1

### Operating System

Linux

### OS Version

Debian 12

### Web browser and version

Google Chrome - Version 126.0.6478.126 (Official Build) (64-bit)

### Running in Sail?

No

### Description

When running `vite build --watch` changing a CSS file will recompile the files, but the file changed doesn't get included in recompiling. It's almost as if the watch polling is much quicker where it compiles before the file finishes saving.

### Steps To Reproduce

1. Run `vite build --watch`
2. Modify some css files
3. Open your URL and you will notice not all files re-compile.

This issue doesn't exist on Vite 4.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
