### ISSUE TITLE
Support Vite 6.x

### ISSUE THREAD

**Issue by gabrielrbarbosa** [laravel/vite-plugin#308]
### Vite Plugin Version

1.0.6

### Laravel Version

11.33.2

### Node Version

22.11.0

### NPM Version

10.9.0

### Operating System

Windows (WSL)

### OS Version

10

### Web browser and version

Chrome

### Running in Sail?

Custom Docker

### Description

npm warn Could not resolve dependency:
npm warn peer vite@"^5.0.0" from laravel-vite-plugin@1.0.6
npm warn node_modules/laravel-vite-plugin
npm warn   dev laravel-vite-plugin@"^1.0.6" from the root project

### Steps To Reproduce

use  "vite": "^6.0"

https://github.com/vitejs/vite/releases/tag/v6.0.0

**Comment by timacdonald** [comment]
Vite 6 support has not yet been released. Please continue to use Vite 5 until we tag a version with Vite 6 support.

**Comment by timacdonald** [comment]
PR open: https://github.com/laravel/vite-plugin/pull/310

**Comment by jimblue** [comment]
> Vite 6 support has not yet been released. Please continue to use Vite 5 until we tag a version with Vite 6 support.

Vite 6 has been released 2 days ago : https://github.com/vitejs/vite/releases/tag/v6.0.0

**Comment by timacdonald** [comment]
Vite 6 support in this repository has not yet been released. Please continue to use Vite 5 until we tag a version with Vite 6 support.
