### ISSUE TITLE
Building an empty CSS file generates JS file and bugged manifest

### ISSUE THREAD

**Issue by jorqensen** [laravel/vite-plugin#33]
- Laravel Vite Plugin Version: 0.2.1
- Laravel Version: 9.19.0
- Node Version: 16.15.1
- NPM Version: 8.11.0

### Description:

When building (`npm run build`) an empty CSS file, it'll generate a `.js` file in it's place, with a manifest that doesn't make sense and throws an error in the application.

Here's my generated manifest:

```json
{
  "resources/css/app.css": {
    "src": "resources/css/app.css",
    "isEntry": true
  },
  "resources/js/app.js": {
    "file": "assets/app.f40b63e3.js",
    "src": "resources/js/app.js",
    "isEntry": true
  }
}
```

And here's the [StackTrace](https://flareapp.io/share/xPQkaJ25#F65).

I am unsure if this is a Vite specific thing. I can obviously leave out the CSS file in the `@vite` directive since an empty CSS file doesn't make sense. But I still believe this is wrong behavior.

### Steps To Reproduce:

- Generate new Laravel app
- Run run build on an empty `.css` file
- Use the `@vite` directive to pull the bundled CSS file (which has become a JS file)

**Comment by HussainEF** [comment]
When we run "npm run build" command, then vite compile all of your css and js files presents in resources directory. Vite ignore all the functions during compiling which are unused. So there is simple fix for this. if your function name "addOptionFunc()" then place following line of code after function declaration.
window.addOptionFunc() = addOptionFunc();
Thanks...
