### ISSUE TITLE
Not working along with @vitejs/legacy-plugin

### ISSUE THREAD

**Issue by mrgodhani** [laravel/vite-plugin#36]
- Laravel Vite Plugin Version: 0.2.1
- Laravel Version: 9.2
- Node Version: 16.5
- NPM Version: 8.5.5

### Description:

@vitejs/legacy-plugin is not working along with vite-plugin from laravel when trying to build production assets.

### Steps To Reproduce:

1) Install the plugin for @vitejs/plugin-legacy 
2) Add the below config

```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import legacy from "@vitejs/plugin-legacy";

export default defineConfig({
    plugins: [
        legacy({
            targets: ['ie >= 11'],
            additionalLegacyPolyfills: ['regenerator-runtime/runtime']
        }),
        laravel([
            'resources/css/app.css',
            'resources/js/app.js',
        ]),
    ],
});
```
3) Run the `build` command. Notice it generates a legacy file but the error output given is around manifest and manifest.json is not getting generated.

Getting following below error for manifest.

<img width="1019" alt="Screen Shot 2022-06-28 at 9 59 26 PM" src="https://user-images.githubusercontent.com/1529009/176334806-0be435ed-8e4c-4616-a890-4b6c01843d75.png">

Note: I encountered similar error in laravel-vite composer plugin as well. Reference: https://github.com/innocenzi/laravel-vite/issues/287

**Comment by jessarcher** [comment]
Hi @mrgodhani, thanks for raising this issue. I've created #38 that solves the error during the legacy bundle step.

I'm not too familiar with the legacy plugin, so I'm not sure whether there's anything else we could/should be doing when this is being used. Feel free to open a PR or another issue if needed.
