### ISSUE TITLE
Artisan command and watcher

### ISSUE THREAD

**Issue by jenky** [laravel/vite-plugin#37]
Regarding artisan command and watcher, they should be similar to this
- https://laravel-vite.dev/configuration/laravel-package.html#commands
- https://laravel-vite.dev/configuration/vite-plugin.html#watch

I'm using `inertia` with `ziggy` so I need to regenerate ziggy routes when the routes change or starting the dev server/building the production assets. Both commands and watcher features allow me to keep the ziggy routes up to date.

**Comment by jessarcher** [comment]
Hi @jenky,

I've tested Inertia with Ziggy, and if I create a new route in `routes/web.php`, I only needed to reload the page in my browser for the new Ziggy route to be injected via Ziggy's `@routes` Blade directive. The `@routes` Blade directive is the recommended way to load Ziggy routes.

There is a Vite plugin that can automatically reload the page for you when you change a PHP file (such as the routes file) https://github.com/ElMassimo/vite-plugin-full-reload and we are considering adding this functionality into this plugin.

At this stage I don't think we'll be supporting the above features from laravel-vite.dev, but you are of course free to continue using that plugin if it fits your workflow better.
