### ISSUE TITLE
Guide users away from attempting to load the dev server url to access site

### ISSUE THREAD

**Issue by hailwood** [laravel/vite-plugin#40]
Right now we're getting a [few](https://github.com/laravel/framework/pull/42785#issuecomment-1169296858) [comments](https://github.com/laravel/framework/pull/42785#issuecomment-1170124217) on the Laravel PR saying users can't load the page.
What's happening is they're attempting to load the devserver url (http://localhost:3000) and expecting it to load the site with HMR enabled.

I suggest we update the output the laravel plugin adds to make it clear that the site should still be loaded via the app url as I imagine for the few people that have logged an issue, many more have run into it without commenting.

I'm also wondering if it's related to the docs note that suggests loading the dev server url to accept the certificate warnings and people getting confused?

I'm not sure of the wording hence doing an issue instead of a PR.
> Open {APP_URL} to enjoy your hot module reloading site powered by vite.

**Comment by jessarcher** [comment]
Thanks for the suggestion @hailwood! I've noticed this as well and was worried about it given how prominently Vite displays that URL. I'd hoped outputting our own Laravel section below, with the APP_URL would make it clearer, but we may need to be more explicit as you've suggested. Mix never output its URL so it avoided the confusion, but I do like being able to see it, especially with Vite's ability to find an available port if the default is in use.

I'll have a chat with the team and see what we can come up with.

**Comment by Koykoy200078** [comment]
same issue :<

**Comment by jessarcher** [comment]
Thanks for recommending this @hailwood! I think #57 addresses this quite nicely. I'm still open to customising the initial console output, but at this stage, I can't think of anything that fits in with the existing Vite output. We will revisit this with Vite 3 as they've tweaked their output a little.

**Comment by ceres-tamle** [comment]
Your backend runs via: 
```
php artisan serve
```
and your frontend runs via: 
```
npm run dev
```
You probably should be running both when developing the app.
https://laravel.io/index.php/forum/laravel-breeze-host-refused-to-connect
