### ISSUE TITLE
Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by EQuimper** [laravel/vite-plugin#48]
- Laravel Vite Plugin Version: 0.2.3
- Laravel Version: 9.19.0
- Node Version: 16.0.0
- NPM Version: 7.18.1

### Description:

When build for prod if a user it's already on one page I will receive this sentry exception when this user change page `Failed to fetch dynamically imported module` Look like it's happening because those files vite create have different name. Do we have a way to trigger I don't know a full refresh or ? Btw I'm using React and Inertiajs

My build command `"build": "vite build && vite build --ssr"`

**Comment by jessarcher** [comment]
Hi @EQuimper, are you using the latest version of `inertiajs/inertia-laravel` (v0.6.3)? It should detect a change in the manifest and force a full page load (see https://github.com/inertiajs/inertia-laravel/pull/399).

**Comment by EQuimper** [comment]
@jessarcher thank you let me try this one and yes I was on version 0.5

**Comment by jessarcher** [comment]
No worries! I'm going to assume this is resolved - feel free to re-open if you're still having issues with the latest version of Inertia.
