### ISSUE TITLE
HMR not working with Laravel Sail in WSL2

### ISSUE THREAD

**Issue by mike-healy** [laravel/vite-plugin#49]
- Laravel Vite Plugin Version: 2.9.13
- Laravel Version: 9.19.0
- Node Version: 16.15.1
- NPM Version: 8.11.0
- Windows 10 with WSL2
- Docker Desktop 4.8.1 (78998) using WSL2 backend

### Description:
Setting up a new Laravel project with Sail on Windows. The app and asset bundling works, but HMR is not triggered when updating resources, or even when manually refreshing the tab.

The blade template calls `@vite(['resources/css/app.css', 'resources/js/app.js'])` in the `<head>` section.
App loads successfully, including styles.
The dev tools console shows both `[vite] connecting...` and `[vite] connected.`
Saving a change to a resource file does not trigger a browser update, and even manually refreshing does not work. (The route loads, but with stale resources).

### Steps To Reproduce:

- Connect to WSL instance in Terminal, and install Laravel via `curl -s https://laravel.build/example-app | bash`
- cd and run `npm install`
- From the WSL connected Terminal `npm run dev`. (I can see ready in 3523ms and my APP_URL)
- Load the app in the browser (e.g. `http://example-app.test`) with a view that uses the @ vite helper
- The page loads as expected, console shows `[vite] connected`
- Changing and saving `resources/css/app.css` does not update the browser. Dev console shows no requests or errors
- Force refreshing shows no changes
- Manually opening the CSS link in a new tab (e.g. `http://127.0.0.1:3000/resources/css/app.css`) shows the updated content. If you save another change to the CSS and refresh this tab the changes will show
- Changing the `<link href>` attribute on the style link in the main tab to append a cache-bust query parameter (e.g. `http://127.0.0.1:3000/resources/css/app.css?v=2`) does trigger the new style
- Apart from manually changing the URL like that I need to stop and restart the `npm run build` server and then reload the tab to see changes.

### Vite Config
Using the default `vite.config.js`
```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel([
            'resources/css/app.css',
            'resources/js/app.js',
        ]),
    ],
});
```

**Comment by jameswong3388** [comment]
Wait for the latest release and there will be a fix for this issue.

refer to https://github.com/laravel/vite-plugin/pull/42#issue-1289410988

and add this in your vite `config`

```
server: {
        hmr: {
            host: 'localhost',
        },
    }
```

**Comment by mike-healy** [comment]
Thanks @jameswong3388!

**Comment by timacdonald** [comment]
Let us know if you have any issues after the next release where this issue should be fixed for you @mike-healy

**Comment by jessarcher** [comment]
Hey @mike-healy, that fix primarily helps when running Vite inside a Docker container that is inside WSL. I don't think it will solve your issue as you are already able to connect to Vite's dev server.

I believe you'll want to set [server.watch.usePolling](https://vitejs.dev/config/#server-watch) in your `vite.config.js` file:

```js
server: {
    watch: {
        usePolling: true,
    }
}
```

**Comment by mike-healy** [comment]
Thanks @jessarcher, I will try that later today.
When you say the previous fix was for running Vite inside a Docker container – should I be doing this another way?
Should I be running the vite dev command from somewhere else?

I'm happy to change my approach if running the dev server from the WSL terminal is non-standard

**Comment by jessarcher** [comment]
Hey @mike-healy, I'm honestly not sure what the best practice is with WSL. We've tried to support running Vite both inside and outside Sail containers, but when you run it inside a Docker container that is inside WSL, the networking seems to get a bit more complicated and requires the extra configuration from #42.

**Comment by bradleybernard** [comment]
Just wanted to comment on this since this solved my issue with Laravel + Vite + Homestead!

**Comment by mike-healy** [comment]
Thanks @bradleybernard and @jessarcher .
I got it working by running the npm dev server outside of WSL (and I did not need that server hmr localhost block once I did either).

So in my case I needed to install nvm and node directly on Windows [using this guide](https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows). (I already had them inside the WSL2 Ubuntu virtual machine) 

Then I started Sail from within WSL, the dev server from outside of WSL2 and the hot reloading worked perfectly :)

**Comment by ChrisRiddell** [comment]
An interesting note on this with MacOS when running `npm run dev` inside a sail container viewing localhost in chrome it can render the assets from 0.0.0.0 but not in Safari. I'm going to assume the fix when it comes out will resolve this behaviour in Safari?

**Comment by mike-healy** [comment]
@timacdonald , @jessarcher FWIW I am having the same issue as before with v0.3.0 of the plugin in WSL.
The initial app response works, including CSS. Changes do not hot reload, even if I refresh the tab. I have to stop and start the dev server too see CSS changes take effect.

I am using this block in the config
```
server: {
        hmr: {
            host: 'localhost'
        },
    },
```

As before if run the dev server from my host machine things work as expected.

**Comment by timacdonald** [comment]
@mike-healy can you visit your site at `http://localhost` instead of `http://example-app.test` and let me know if there is any other errors or functionality working / not working?

**Comment by mike-healy** [comment]
Hey @timacdonald .

- Visiting at `http://localhost` and `http://example-app.test` work the same way for me (same problems & the same parts work).
- I was not using polling before. I just tried it. It very barely kind of works. When I save the CSS file I get an instant message in the console saying `[vite] css hot updated: /resources/css/app.css`, but then it takes a huge amount of time for the request to actually happen (about 15 seconds). The other requests like loading the app take more like 400-1500ms
- I do actually need the `hmr: { host: 'localhost' }` too, otherwise it attempts to load assets from http://0.0.0.0 which fails.

If I open a new tab directly to `http://localhost:5173/resources/css/app.css` and manually refresh it loads in ~30ms.

**Comment by mike-healy** [comment]
The one thing that works flawlessly is running the dev server off the local machine 😉

**Comment by driesvints** [comment]
Hey @mike-healy. Because we've only gotten one report for this I'm going to close this one off. I'm sorry HMR doesn't work for you. Maybe try a support channel to see if anyone can help you out?

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by andrewl64** [comment]
@mike-healy Can I know how you ran npm run dev outside wsl? WHen I tried running that in Powershell, I got `'vite' is not recognized as an internal or external command, operable program or batch file.`

`I got it working by running the npm dev server outside of WSL (and I did not need that server hmr localhost block once I did either).`

**Comment by mike-healy** [comment]
@andrewl64 you'll need to install [npm/nvm directly in Windows](https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows). Then you may need to do the `npm install` command from Windows rather than WSL too.

**Comment by jannndo** [comment]
i am having the same trouble with vite using laravel sail via wsl2 as @mike-healy  . Is there any update regarding the mentioned combination - laravel sail, vite, wsl2 (docker) ?

**Comment by andrewl64** [comment]
@jannndo I somehow managed to make it work by first adding the `server.hmr.host` block as shown above and then:

1. Ran `npm install` on PowerShell
2. In wsl, I started sail
3. Ran `sail npm run dev` in wsl
4. Ran `npm run dev` in Powershell

And now, I can access **`vite`** via `localhost` and **`Laravel`** via `127.0.0.1` lol

Hot reload works fine but with a slight 1sec delay whenever changes are made. Hoping to see a proper fix for this soon but yeah, so far, this weird approach that I found seems to be working for me.

**Comment by jannndo** [comment]
@andrewl64 thanks for the workaround Nevertheless its still somehow unpractical if i want to take advantage of the docker and work only with sail. Hope for proper fix too

**Comment by azaf786** [comment]
> 

Have you found a proper solution for this? If so, please share it with us. I get that you can use nvm to run your vite server but that sort of defeats the purpose of using docker.

**Comment by mike-healy** [comment]
@azaf786 – sorry I was never able to find a solution to building within Docker
