### ISSUE TITLE
cors problem when develop laravel in wsl2 with sail 

### ISSUE THREAD

**Issue by PandaYip** [laravel/vite-plugin#53]
- Laravel Vite Plugin Version: 0.2.1
- Laravel Version: 9.2
- Node Version: 16.15.1
- NPM Version:  8.12.1

### Description:
I develop laraval in wsl2 with laravel sail 
I make a fresh installation laravel 9.2 
Everything goes ok , welcome page showed in browser with url http://localhost
then i install jetStream with this command  'sail php artisan jetstream:install inertia'
after npm install and npm run dev 
I got blank screen and errors with the same url 

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://0.0.0.0:5173/resources/js/app.js. (Reason: CORS request did not succeed). Status code: (null).

but if you run npm run build , the page will show normal , so i think this issue related to vite .
![1656744917845](https://user-images.githubusercontent.com/13165391/176990231-963b0acc-9774-4950-9bb2-d43cac00db06.jpg)
![1656744944243](https://user-images.githubusercontent.com/13165391/176990233-c7bb292d-d6a7-4a08-a4d7-426e66a9d70d.jpg)

### Steps To Reproduce:
fresh installation laravel and jetstream inertia  'sail php artisan jetstream:install inertia'  in wsl2 ,

> sail up -d 
> npm run dev 

then you will get a blank screen and errors in browser with url http://localhost

**Comment by jessarcher** [comment]
Hi @PandaYip, this is an issue with Windows not understanding `0.0.0.0` and has been reported in #28 and fixed in #42.

Once this has been released, you will need an additional configuration option when running in Docker with WSL, as detailed in #42.
