### ISSUE TITLE
Laravel Vite requests to not load on fresh Laravel Install on Homestead

### ISSUE THREAD

**Issue by gradedcatfood** [laravel/vite-plugin#58]
- Laravel Vite Plugin Version: 0.2.1
- Laravel Version: 9.19
- Node Version: v16.15.0
- NPM Version: 8.5.5

### Description:
Created a new laravel project, installed laravel breeze, run npm install and run dev, and JS and CSS files do not load in the browser. Using homestead as my local dev env running PHP 8.1. All requests to the vite dev server get blocked. Not using any SSL, just a local domain configured within the homestead.yaml. I've tried a couple of different config options within the vite.config.js file to specify my custom homestead domain but it did not fix it.

Console with blocked network requests
![image](https://user-images.githubusercontent.com/6394329/177067124-66b5f520-73ae-4b70-aee2-43ec50700080.png)

Styles not loading
![image](https://user-images.githubusercontent.com/6394329/177067283-ece2ba40-e245-446c-b9e6-9b1f417da910.png)

### Steps To Reproduce:
laravel new project
composer require laravel/breeze --dev
php artisan breeze:install
npm install
npm run dev

If I just run PHP artisan serve, styles and js load correctly - only issue while trying to visit a local domain that is running via homestead

**Comment by gradedcatfood** [comment]
I'm sorry but I think I figured it out. Looking through some previous GitHub issues it looks like this is a Brave-specific issue! I turned off the "shield" and now things are working. Sorry for creating this ticket in haste but for anyone else having this issue on Brave this helped me: https://github.com/laravel/vite-plugin/issues/47

**Comment by timacdonald** [comment]
Glad you got it sorted @gradedcatfood For yourself and future visitors, you may also [configure Brave to allow the Vite dev server to run on your specific project URLs](https://github.com/laravel/vite-plugin/issues/47#issuecomment-1173198084).
