### ISSUE TITLE
Laravel vite only show EOF

### ISSUE THREAD

**Issue by Aslam97** [laravel/vite-plugin#61]
- Laravel Vite Plugin Version: ^0.2.4
- Laravel Version: ^9.2
- Node Version: v14.17.0
- NPM Version: 8.13.2

### Description:
Just a couple hours ago Everything goes ok. but after I restarted my laptop and start the project again and it show this.
![Screenshot from 2022-07-05 12-29-00](https://user-images.githubusercontent.com/25027592/177256805-166607c1-6ece-4ece-b666-c307cb7f8356.png)

if i open `slotin.test:8000` on Incognito mode in chrome, it shows me this
![Screenshot from 2022-07-05 12-42-44](https://user-images.githubusercontent.com/25027592/177257823-76bfbc4a-fb85-4b86-8cd7-8867568d0104.png)

### Steps To Reproduce:
![Screenshot from 2022-07-05 12-39-34](https://user-images.githubusercontent.com/25027592/177257251-0b35c873-65f5-48e9-ac35-7cc3a32cd028.png)
![Screenshot from 2022-07-05 12-39-46](https://user-images.githubusercontent.com/25027592/177257261-711e0adb-6fc0-426a-aa83-8f3845a672ce.png)

**vite.config.js**
```js
import laravel from 'laravel-vite-plugin';
import eslintPlugin from 'vite-plugin-eslint';
import { defineConfig } from 'vite';
import { createVuePlugin } from 'vite-plugin-vue2';

export default defineConfig({
  server: {
    host: 'slotin.test'
  },

  plugins: [
    laravel(['resources/css/app.css', 'resources/js/app.js']),
    createVuePlugin(),
    eslintPlugin(),
    {
      name: 'blade',
      handleHotUpdate({ file, server }) {
        if (file.endsWith('.blade.php')) {
          server.ws.send({
            type: 'full-reload',
            path: '*'
          });
        }
      }
    }
  ],

  resolve: {
    alias: {
      vue: 'vue/dist/vue.esm.js',
      '~': '/resources/js',
      '@assets': '/resources/assets',
      '@components': '/resources/js/components',
      '@plugins': '/resources/js/plugins',
      '@store': '/resources/js/store'
    }
  },

  build: {
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes('node_modules')) {
            return 'vendor';
          }
        }
      }
    }
  }
});
```

**Comment by jessarcher** [comment]
Hi @Aslam97, does the same issue happen if you remove the `slotin.test` host from your `vite.config.js` file and from the `php artisan serve` command and then access your site from [http://localhost:8000](http://localhost)?

**Comment by Aslam97** [comment]
@jessarcher removing `slotin.test` from `vite.config.js` and run `php artisan serve` without the `--host=slotin.test` flag as you suggested. Now my project can run normally. the reason i use custom domain on my local is because of laravel subdomain routing `{subdomain}.example.com`. however I tried using localhost `{subdomain}.localhost` and it worked. i guess i just use localhost then.

**Comment by Aslam97** [comment]
Iam adding 
```
127.0.0.1 localhost
127.0.1.1 slotin.test
127.0.1.1 example.slotin.test
```
to `/etc/hosts`. I suspect `slotin.test` and `php artisan serve --host=slotin.test` are not sync. because if I don't run `php artisan serve --host=slotin.test` and go to `slotin.test` it still returns "EOF"

**Comment by jessarcher** [comment]
> ```
> 127.0.0.1 localhost
> 127.0.1.1 slotin.test
> 127.0.1.1 example.slotin.test
> ```

Is there a reason that the last two examples use `127.0.1.1` instead of `127.0.0.1`?

**Comment by Aslam97** [comment]
There is no reason. as long as localhost and vite dev server are pointing with the same ip.
- `php artisan serve --host=slotin.test` is pointing to 127.0.1.1
- vite dev server with config `server: { host: 'slotin.test' }` is also point to 127.0.1.1 which is right.
now i know why iam getting "EOF" is because vpn on chrome is active. so the alias on 127.0.1.1 (slotin.test) does not resolve. but if i open the address `127.0.1.1:8000` (with active vpn) and change `vite.config.js` to `server: { host: 127.0.1.1 }` everything back to work.

**Comment by jessarcher** [comment]
Glad you got it working 👍
