### ISSUE TITLE
CORS request still blocked on Sail/WSL2 after 0.3.0 update, public hot file still loads from 0.0.0.0

### ISSUE THREAD

**Issue by ronfuller** [laravel/vite-plugin#62]
- Laravel Vite Plugin Version: 0.3.0
- Laravel Version: 9.19.0
- Node Version: 16.13.2
- NPM Version: 8.4.1

### Description:
Application fails to load with error:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://0.0.0.0:3002/@vite/client. (Reason: CORS request did not succeed). Status code: (null).

The error can be temporarily fixed by changing the /public/hot file to
https://localhost:3002

Of course running sail npm run dev will rewrite the /public/hot file to 
https://0.0.0.0:3002

Note: 
The result of the npm run dev commands shows:

vite v2.9.13 dev server running at:
> Local: https://localhost:3002/

### Steps To Reproduce:
Load application, screen is blank

Console shows CORS error.

----

vite config:
server: {
        https: true,
        port: 3002,
        hmr: {
            host: "localhost",
        },
    },

docker-compose per new install laravel 9.19.0

VITE_PORT in environment var is set to 3002

**Comment by jessarcher** [comment]
@ronfuller I'm unable to replicate this with `0.3.0`. Can you please confirm you have the correct version by running `npm list | grep laravel-vite-plugin`?

You may need to run `npm install -D laravel-vite-plugin@latest` as the version bump may not meet the requirements in your `package.json`.

**Comment by ronfuller** [comment]
I was able to resolve this issue after running the npm install -D command.
Thank you.
