### ISSUE TITLE
HMR port not being used

### ISSUE THREAD

**Issue by guilheb** [laravel/vite-plugin#64]
- Laravel Vite Plugin Version: 0.3.0
- Laravel Version: 9.19.0
- Node Version: 14.17.5
- NPM Version: 6.14.14

### Description:
When `server.hmr.port` is specified in the `vite.config.js` file, it is not used to generate the `public/hot` file.

I tried a [pull request](https://github.com/laravel/vite-plugin/pull/63), but I'm not familiar with the TypeScript syntax and the checks are failing. Can someone help?

### Steps To Reproduce:
Add this to `vite.config.js`
```
    server: {
        hmr: {
            port: 3081,
        },
    },
```
Run `npm run dev` and open the `public/hot` file. The port number will be the one from `server.port` (3000 by default).

**Comment by jessarcher** [comment]
Let's continue the discussion on #63
