### ISSUE TITLE
Configuration "resources/js/app.js" does not exist.

### ISSUE THREAD

**Issue by JD456976** [laravel/vite-plugin#65]
- Laravel Vite Plugin Version: 0.2.0
- Laravel Version: 9.19.0
- Node Version: 18.4.0
- NPM Version: 8.12.1
- Inertia Version: 0.6.3

### Description:
Upon running ```npm run dev``` Laravel throws:

```
Configuration "resources/js/app.js" does not exist.
```

### Steps To Reproduce:
1. Follow the official Laravel docs
2. Replace 'mix' directive with 'vite' directive in app.blade.php 

Went so far as to make changes in the vite.config file with no success. Also used an absolute URL for the resources and error persists.  

Dumped composer and cleared Laravel and browser cache with no success. 

There is a post on Stackoverflow with a similar issue:  https://stackoverflow.com/questions/72799267/why-laravel-vite-directive-not-working-in-my-project

**Comment by timacdonald** [comment]
Hi @JD456976, can you confirm you have followed all the steps in order from the [official upgrade guide](https://github.com/laravel/vite-plugin/blob/main/UPGRADE.md)?

**Comment by timacdonald** [comment]
Can you please share you `vite.config.js`?

**Comment by JD456976** [comment]
Certainly! And thank you for taking a look:

```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue';

export default defineConfig({
    plugins: [
        laravel([
            'resources/css/app.css',
            'resources/js/app.js',
        ]),
         vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false,
                },
            },
         }),
    ],
});
```

**Comment by timacdonald** [comment]
This looks good. Could you also share the @vite directive you are using in your views?

**Comment by JD456976** [comment]
The below threw an error stating it had to be a string, not an array:

```
@vite(['resources/css/app.css', 'resources/js/app.js'])
```

So I changed mine to:
```
@vite( 'resources/js/app.js')
```

and got the error. 

I also tried:

``` @vite( '/resources/js/app.js') ``` and an absolute url:  ```@vite( 'http://dev.test/resources/js/app.js')```

I'm using Valet hence the .test domain.

**Comment by timacdonald** [comment]
This should be the correct version. Can you make sure you have this in the view before moving forward.

```
@vite(['resources/css/app.css', 'resources/js/app.js'])
```

Can you confirm you have a file at the path `"resources/js/app.js"` in your project ?

**Comment by JD456976** [comment]
Yes, the app.js file exists and is in the correct location. Hmm.. I get an htmlspecial characters error and indicating it has to be a string. 

Let me revert back to mix and then migrate again over to Vite to see if anything gets resolved.

**Comment by timacdonald** [comment]
Let me know how you go.

**Comment by JD456976** [comment]
Will do and additionally, I even tried the automated process with Laravel Shift and got the same exact error.  

I'll let you know shortly.

**Comment by JD456976** [comment]
Re-installed everything, ```npm run dev``` :

```
htmlspecialchars(): Argument #1 ($string) must be of type string, array given
```

```
@vite(['resources/css/app.css', 'resources/js/app.js'])
```

**Comment by timacdonald** [comment]
Can you provide the full stack trace, please?

**Comment by JD456976** [comment]
Certainly:

[https://flareapp.io/share/dmkx2glP#F65](url)

**Comment by timacdonald** [comment]
Can you please provide you `package.json` dependencies?

**Comment by timacdonald** [comment]
Can you please a copy of your `composer.json` dependencies? Both "require" and "require-dev"?

**Comment by JD456976** [comment]
```
 "require": {
        "php": "^8.1",
        "algolia/algoliasearch-client-php": "^3.2",
        "algolia/scout-extended": "^2.0",
        "awssat/laravel-visits": "^3.0",
        "cviebrock/eloquent-sluggable": "^9.0",
        "cviebrock/eloquent-taggable": "^9.0",
        "fruitcake/laravel-cors": "^2.0.5",
        "guzzlehttp/guzzle": "^7.2",
        "inertiajs/inertia-laravel": "^0.6.3",
        "innocenzi/laravel-vite": "^0.2.0",
        "laravel-notification-channels/discord": "^1.3",
        "laravel/fortify": "^1.10",
        "laravel/framework": "^9.19.0",
        "laravel/sanctum": "^2.14",
        "laravel/scout": "^9.4",
        "laravel/socialite": "^5.5",
        "laravel/tinker": "^2.7",
        "laravelcollective/html": "^6.3",
        "qcod/laravel-settings": "^1.1",
        "rahulhaque/laravel-filepond": "^v1.8.10",
        "santigarcor/laratrust": "^7.0",
        "socialiteproviders/discord": "^4.1",
        "spatie/laravel-medialibrary": "^10.0.0",
        "stechstudio/laravel-php-cs-fixer": "^3.1",
        "tightenco/ziggy": "^1.4",
        "venturecraft/revisionable": "1.*",
        "willvincent/laravel-rateable": "^3.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.6",
        "fakerphp/faker": "^1.9.1",
        "laravel-shift/blueprint": "^2.3",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0",
        "friendsofphp/php-cs-fixer": "^3.8.0",
        "phpmd/phpmd": "@stable",
        "squizlabs/php_codesniffer": "4.0.x-dev"
    },
```

**Comment by JD456976** [comment]
package.json

```
 "scripts": {
        "build": "vite build",
        "dev": "vite"
    },
    "devDependencies": {
        "@vitejs/plugin-vue": "^2.3.3",
        "@vue/compiler-sfc": "^3.2.33",
        "axios": "^0.25.0",
        "laravel-file-uploader": "^2.4.0",
        "laravel-vite-plugin": "^0.3.0",
        "lodash": "^4.17.19",
        "postcss": "^8.1.14",
        "prettier": "^2.5.1",
        "resolve-url-loader": "^5.0.0",
        "sass": "^1.51.0",
        "sass-loader": "^13.0.0",
        "vfonts": "^0.0.3",
        "vite": "^2.9.13",
        "vite-plugin-laravel": "^0.2.0-beta.24",
        "vue-loader": "^17.0.0",
        "webpack": "^5.72.1"
    },
    "dependencies": {
        "@codinglabs/laravel-asset": "^1.0.3",
        "@inertiajs/inertia": "^0.11.0",
        "@inertiajs/inertia-vue3": "^0.6.0",
        "@inertiajs/progress": "^0.2.7",
        "@vuelidate/core": "^2.0.0-alpha.41",
        "@vuelidate/validators": "^2.0.0-alpha.29",
        "algoliasearch": "^4.13.1",
        "chart.js": "^3.8.0",
        "filepond": "^4.30.3",
        "filepond-plugin-file-encode": "^2.1.10",
        "filepond-plugin-file-validate-size": "^2.2.7",
        "filepond-plugin-file-validate-type": "^1.2.8",
        "filepond-plugin-image-crop": "^2.0.6",
        "filepond-plugin-image-preview": "^4.6.11",
        "instantsearch.css": "^7.4.5",
        "primeflex": "^3.2.1",
        "primeicons": "^5.0.0",
        "primevue": "^3.12.6",
        "quill": "^1.3.7",
        "vue": "^3.2.31",
        "vue-filepond": "^7.0.3",
        "vue-instantsearch": "^4.3.3",
        "ziggy": "^2.4.0"
    }
```

**Comment by timacdonald** [comment]
Thank you for sharing these. I can now see the issue you are facing.

You currently have the community Vite plugin and the Laravel plugin active, and they are conflicting with each other.

The PHP package `"innocenzi/laravel-vite"` along with the NPM package `"vite-plugin-laravel"` are part of the [fantastic community Vite plugin](https://github.com/innocenzi/laravel-vite).

This is a great plugin that has many features and you may wish to continue using it. If you do want to use the community plugin, I recommend uninstalling the `"laravel-vite-plugin"` NPM package.

Then you should refer to the documentation: https://laravel-vite.dev/

Alternatively, if you would like to use framework version, you should uninstall the `"innocenzi/laravel-vite"` composer package and additionally uninstall the `"vite-plugin-laravel"` NPM package.

Ensure that you have only followed the steps in the [official upgrade guide](https://github.com/laravel/vite-plugin/blob/main/UPGRADE.md).

Finally, if you are still having issues, you may need to run:

```
php artisan view:clear
```

to bust the view cache. I hope that gets you back on track.

**Comment by JD456976** [comment]
*facepalm* Thank you for solving that!! 

Removed the innocenzi and vite-plugin laravel. Installed the official package, cleared the cache, but now have  a white screen. It does however look like the @vite directive is working properly.

**Comment by JD456976** [comment]
> APP_URL: http://toast.test

and tried http://localhost:3000/

**Comment by timacdonald** [comment]
That is the URL of the Vite server. You still need to server your site with `php artisan serve`, Valet, or Sail and visit the web server URL like you used to.

If you are using Valet and your project directory is called "toast", you should still visit `toast.test` in the browser.

**Comment by JD456976** [comment]
I'm using Valet and that's the url I'm visiting. I can actually see the page source which all looks fine....

**Comment by JD456976** [comment]
I figured it out. I was importing a component without using .vue. 

THANK YOU again for all of your help and time!!

**Comment by timacdonald** [comment]
perfect! glad to hear you got it sorted 😀

**Comment by ThisIsPuzzle** [comment]
Hehe, i just got the error on the developement project - same code as the one on production , which was live for a few months now - and i couldn't understand why. 

After i made the upgrade from webpack to vite, i forgot to delete the generated views from blade ( php artisan view:clear ) which was using the app.js from public folder...

The **@vite()** accepts as a paramter the config name from configs/vite.php file - so it is not correct to use **@vite('resources/js/app.js')** but instead use **@vite('default')** or just **@vite()** - since in the code of Innocenzi / Vite you will find this line: **$name ??= config('vite.default');** - so if you don't set a name it will get the vite.default confing by default.

So when you migrate from webpack to vite on InertiaJS - just clear your views generate by laravel ( php artisan view:clear - or manually delete the storage/framework/views folder )

**Comment by dev-yagnik** [comment]
.
