### ISSUE TITLE
Still not working through WSL2 and sail even with 0.3.0

### ISSUE THREAD

**Issue by gorbit99** [laravel/vite-plugin#66]
- Laravel Vite Plugin Version: 0.3.0
- Laravel Version: 9.19
- Node Version: 16.15.1
- NPM Version: 8.13.2

### Description:
I'm trying to run my project through wsl2 and sail, but I'm only getting a blank screen saying:
```
@viteReactRefresh @vite(['resources/css/app.scss', 'resources/js/index.jsx'])
```
instead of the site loading. I have version 0.3.0 installed with laravel 9.19, and I have the server.hmr.host set to "localhost" in vite.config.js.
The resources can be accessed if I do `https://localhost:5173/resources/js/index.jsx`, but it seems like the client just doesn't load.

**Comment by timacdonald** [comment]
Would you mind sharing your vite config and also your docker compose file?

**Comment by jessarcher** [comment]
If the blade directives are being output to the screen and you're on Laravel 9.19, then you probably loaded the directives prior to 9.19 and it will have cached them as not existing. Try `php artisan view:clear`.

**Comment by gorbit99** [comment]
This solved the issue, thank you very much!
