### ISSUE TITLE
Add a command flag to generate new project directly with Laravel Mix configuration instead of Vite

### ISSUE THREAD

**Issue by nyshire** [laravel/vite-plugin#67]
Hello, Laravel team. I just wanted to suggest an improvement. I find the update from mix to vite very cool but I think that there are many simple projects that uses Laravel Mix and basic SSR even though modern web app are built with SPA tech stack. I think we can have a command flag like `laravel new project --mix` to generate a project with mix instead of vite config because it can be annoying to modify, create a lot of file just to initialize a project...

**Comment by jessarcher** [comment]
Hi @nyshire, is there something in particular you're missing in Vite? I've been loving it on all my projects, including simple SSR ones.

**Comment by goodnewso** [comment]
So many issues with wsl2 on windows dev server

**Comment by goodnewso** [comment]
Windows WSL2 not working with vite dev server

**Comment by nyshire** [comment]
Hi @jessarcher. No, not at all. Vite is a cool but i'm just saying that it can be interesting to have possibility to use laravel mix. It could be more easy to use for people who already have experience with webpack if maybe they don't knwo vite...

**Comment by shakeel2717** [comment]
yes, i also wish, there's a command in laravel laravel new project --mix
Please allow us to choice the Vite or Mix

**Comment by innocenzi** [comment]
For anyone here preferring Mix over Vite, I suggest you write a [preset](https://preset.dev/) instead, with your own opinionated modifications. I think having an official Vite *and* Mix scaffolding would be too much to maintain and quite unnecessary.

**Comment by nyshire** [comment]
Ok, thanks @innocenzi.
