### ISSUE TITLE
hot reload is not work on valet with ssl

### ISSUE THREAD

**Issue by simonwong1985hk** [laravel/vite-plugin#71]
<img width="1280" alt="Screen Shot 2022-07-07 at 22 17 27" src="https://user-images.githubusercontent.com/18599865/177796454-b72a22ca-b422-417b-8f9e-097d975546d1.png">

**Comment by clementmas** [comment]
I had the same issue. I fixed it by specifyinig the `hmr` `host`. I'm not sure why that's not a default.

```
server: {
    https: true,
    host: 'localhost',
    hmr: {
        host: 'localhost',
    },
}
```

**Comment by rvalenzuelaferrada** [comment]
I have the same problem with laravel homestead.

**Comment by simonwong1985hk** [comment]
Before @clementmas, I find a solution https://github.com/simonwong1985hk/live/commit/555f21ceda37f1759bb21075c1bea6968f7ab5df which from https://dev.to/paulocastellano/how-to-make-vite-valet-and-ssl-works-together-5hbb, after try the solution from @clementmas, it also works for me and better cleaner coding, thank you so much!

**Comment by timacdonald** [comment]
Hey folks,

Glad you have this sorted and sorry you ran into troubles. For future readers, the documentation has instructions on working with a secure server (remember you need to accept the certs as outline) and we are actively looking at improving the experience with secure local servers.


![Screen Shot 2022-07-08 at 11 12 16 am](https://user-images.githubusercontent.com/24803032/177896801-236eec13-afa0-4619-908e-270763aaac0a.png)


See: https://laravel.com/docs/9.x/vite#working-with-a-secure-development-server
