### ISSUE TITLE
public to public_html

### ISSUE THREAD

**Issue by zdarin** [laravel/vite-plugin#74]
Hello,

Can some one explain what im doing wrong
Im working with shared hosting and when public folder renamed for public_html writes error can someone explain how correctly change without errors? Or its seems to be fixed ??

By npm run dev throws errors but seems working
Or i need public folder exist too for laravel vite to work and public_html for host ?

<img width="1131" alt="check" src="https://user-images.githubusercontent.com/42121280/178477657-7e9d2664-8f1a-448a-b06f-027f0b12c74c.png">

**Comment by timacdonald** [comment]
You should not use Vite's publicDir config, as that has a different purpose. Instead you may set the `publicDirectory` for the Laravel Plugin.

```
// ...

laravel({
    input: "resources/js/app.js",
    publicDirectory: "public_html",
}),

// ...
```

**Comment by zdarin** [comment]
Thx its fixed this with public error but in browser i have error 

```Failed to load resource: the server responded with a status of 500 ()```

I think somthing with manifest / assests it should be ??

**Comment by timacdonald** [comment]
With that information I'm not sure what the issue is or if it is related to the vite plugin or not.

**Comment by zdarin** [comment]
delete config file on Hosting server from 

```bootstrap\cache\config.php```

**Comment by zdarin** [comment]
here as should be published to hosting server

<img width="348" alt="Screenshot 2022-07-15 at 20 09 00" src="https://user-images.githubusercontent.com/42121280/179274662-3dc27f15-873a-4c87-bde4-75887ebc4214.png">

<img width="348" alt="Screenshot 2022-07-15 at 20 08 51" src="https://user-images.githubusercontent.com/42121280/179274779-f824eb65-1904-40ce-a700-82e4218501d3.png">


<img width="1072" alt="Screenshot 2022-07-15 at 20 09 13" src="https://user-images.githubusercontent.com/42121280/179274569-5a05682c-56d0-459a-9475-da8c81bbfdde.png">

**Comment by Rage-coder69** [comment]
idk why mine doesn't work, The Vite.php file is looking in the public folder of the laravel(folder structure that is in development)

**Comment by jessarcher** [comment]
@Rage-coder69, you need to tell Laravel where your new public directory is. You can do this in the `register` method of a service provider:

```php
$this->app->bind('path.public', function () {
    return base_path('public_html');
});
```

**Comment by Rage-coder69** [comment]
> @Rage-coder69, you need to tell Laravel where your new public directory is. You can do this in the `register` method of a service provider:
> 
> ```
> $this->app->bind('path.public', function () {
>     return base_path('public_html');
> });
> ```

yes thank you for your reply, i had to tell laravel my new public directory and had to update the code in the core files, and after that tweaking, the website starting working.

**Comment by timacdonald** [comment]
Hey folks, I just removed some comments here as they were exposing your servers file structure and it could be a potential security risk.

Just better to be safe than sorry 🔐
