### ISSUE TITLE
Vite 3.0 support?

### ISSUE THREAD

**Issue by bcorcoran** [laravel/vite-plugin#75]
Vite 3.0.0 was released today, is it possible that this plugin could be updated to support that?

It appears that the plugin works just fine with vite 3.0.0 but the dependency just needs to be updated to include ^3.0

**Comment by timacdonald** [comment]
@bcorcoran we will absolutely be support Vite 3 - but as it only shipped today we need to test it with the plugin. Support will likely be in the next release.
