### ISSUE TITLE
Can't change base url for ping pong

### ISSUE THREAD

**Issue by asolopovas** [laravel/vite-plugin#78]
Hi, 

I am using my own nginx server to run laravel application. The problem that I cannot change base_url/__vite_ping. It tries to request https://server.test/__vite_ping rather than https://localhost:3000/__vite_ping. Here is my vite.config.js 

```js
import {defineConfig} from 'vite';
import fs from 'fs';
import laravel from 'laravel-vite-plugin';

const ASSET_URL = process.env.ASSET_URL || '';

export default defineConfig({
    base: `${ASSET_URL}`,
    server: {
        https: {
            key: fs.readFileSync('resources/ssl/localhost.key'),
            cert: fs.readFileSync('resources/ssl/localhost.crt'),
        },
        host: 'localhost',
    },
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
            ],
            refresh: true,
        }),
    ],
});
```

When I run vite -d, the config base does not change it seems like laravel plugin overrides it, is there a way to change `base_url` ?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by timacdonald** [comment]
@asolopovas I believe you will want to set the `server.hmr.host` to `"localhost"`. See: https://v2.vitejs.dev/config/#server-hmr

**Comment by jessarcher** [comment]
Vite 2 has a known issue with its ping URL and backend integrations like Laravel's. There's no way to customise where it makes the request as it just hits `/__vite_ping` which means the browser makes the request to the backend server instead of the Vite server.

This has been fixed in Vite 3 and this plugin will support Vite 3 very soon (See #77)
