### ISSUE TITLE
Issue with installing Vue with Laravel Vite

### ISSUE THREAD

**Issue by MoaaidJamal** [laravel/vite-plugin#80]
- Laravel Vite Plugin Version: 2.9.14
- Laravel Version: 9.20.0
- Node Version: 18.5.0
- NPM Version: 8.14.0
- Host operating system: macOS 12.4
- Web Browser & Version: Edge 103.0.1264.51
- Running in Sail / Docker: No (Just Valet)

### Description:
I tried to install @vitejs/plugin-vue in a fresh Laravel application with version 9.20.0 and I faced the issue that the current version of @vitejs/plugin-vue is 3.0.0 and it requires Laravel Vite with version 3.0.0

And when I tried to upgrade Laravel Vite to version 3.0.0 I faced another issue. It is not compatible with ("laravel-vite-plugin": "^0.4.0")

Notes: 
1. I got the configurations from [https://laravel.com/docs/9.x/vite#configuring-vite](https://laravel.com/docs/9.x/vite#configuring-vite)
2. I submitted an issue related to Inertia and someone answered me that the support of Laravel Vite 3.0.0 will be in the next version of Laravel as I understood. But what should I do to fix this issue in the current version?

### Steps To Reproduce:
1. run: `laravel new vite`
2. run: `cd vite`
3. run: `npm install`
4. run: `npm install vue@next vue-loader@next` (Optional)
5. run: `npm i @vitejs/plugin-vue`

**Comment by driesvints** [comment]
Also see https://github.com/laravel/vite-plugin/pull/76
