### ISSUE TITLE
Blade @vite directive not detecting public/build Folder

### ISSUE THREAD

**Issue by haleyngonadi** [laravel/vite-plugin#81]
- Laravel Vite Plugin Version: ^0.4.0
- Laravel Version: ^9.19.0
- Node Version: 18.6.0
- NPM Version: 8.13.2
- Host operating system: macOS 10.15.7
- Web Browser & Version: Chrome 104.0.5112.48
- Running in Sail / Docker: No

### Description: Running npm run dev works well but when I run npm run build, the build folder is created as expected in public/build but the @vite direction in blade isn't picking up the build folder at all. It keeps looking for @vite/client even though it is no longer in dev mode.
![Screen Shot 2022-07-15 at 3 02 26 PM](https://user-images.githubusercontent.com/6877114/179293540-7b24a838-4ba8-4536-969f-f2bb2989e7eb.png)

### Steps To Reproduce:

1. Run `npm run build` after installing all the packages.
2. In the main blade entry file, add `@vite(['resources/js/app.js'])` (I tried adding the build directory too `@vite(['resources/js/app.js'], 'build')` and that didn't work)
3. Visit the site in the browser and it should fail showing an net::ERR_CONNECTION_REFUSED in console.

This is my vite.config.js file:
```
import { defineConfig } from "vite";
import fs from "fs";
import { homedir } from "os";
import laravel from "laravel-vite-plugin";
import { resolve } from "path";
import vue from "@vitejs/plugin-vue";

let host = "stats.test";
export default defineConfig({
    plugins: [
        laravel("resources/js/app.js"),
        vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false,
                },
            },
        }),
    ],
    resolve: {
        alias: {
            src: resolve(__dirname, "resources/js"),
            modules: resolve(__dirname, "resources/js/components/modules"),
            frontend: resolve(__dirname, "resources/js/components/frontend"),
            vendor: resolve(__dirname, "resources/js/vendor"),
            lang: resolve(__dirname, "resources/languages"),
        },
    },
    server: detectServerConfig(host),
});

function detectServerConfig(host) {
    let keyPath = resolve(homedir(), `.config/valet/Certificates/${host}.key`);
    let certPath = resolve(homedir(), `.config/valet/Certificates/${host}.crt`);

    if (!fs.existsSync(keyPath)) {
        return {};
    }

    if (!fs.existsSync(certPath)) {
        return {};
    }

    return {
        hmr: { host },
        host,
        https: {
            key: fs.readFileSync(keyPath),
            cert: fs.readFileSync(certPath),
        },
    };
}
```

**Comment by timacdonald** [comment]
This will happen if the `public/hot` file still exists.

check that you haven’t accidentally committed this file to the project repository. If it exists, delete it.

The plug-in should automatically delete it when it shuts down the HMR server, but potentially you committed the file while it was running.

If that isn’t the case, let us know.

**Comment by haleyngonadi** [comment]
That was indeed the case. Because I was not canceling the process properly, the hot file wasn't being deleted. Thank you so much!

**Comment by jessarcher** [comment]
@haleyngonadi How were you cancelling it out of interest? We've tried to detect the various ways the process will stop so we can hook in and delete the file.

**Comment by haleyngonadi** [comment]
> @haleyngonadi How were you cancelling it out of interest? We've tried to detect the various ways the process will stop so we can hook in and delete the file.

@jessarcher I was just killing terminal (hitting the trash button on VS code):
![Screen Shot 2022-07-16 at 01 29 05](https://user-images.githubusercontent.com/6877114/179341262-0f48bfc8-6213-4e37-ae38-65ec372089f3.png)

Could a solution be to auto-delete the hot file as soon as `vite build` is run as opposed to depending on canceling the dev process? 👀

**Comment by jessarcher** [comment]
Thanks @haleyngonadi, I'll see if we can hook into closing the terminal in that way.

My only concern with deleting the hot file on build is that someone may want to run the build while the HMR server is also running :woman_shrugging:

**Comment by timacdonald** [comment]
another good idea is to make sure the hot file is ignored in your projects `.gitignore` file. Then it should not be able to be committed unintentionally.

**Comment by haleyngonadi** [comment]
@timacdonald It's in my `.gitignore` file for sure (from my laravel mix days) but I usually run build locally and push build files to my prod server.

**Comment by rrpadilla** [comment]
hi @jessarcher, how / when the "public/hot" file gets delete? If I use "Command + C" to cancel the process "npm run dev" the hot file is not deleted. It is a good idea to delete the hot file on build.
