### ISSUE TITLE
Bad Url for Vite in Safari, page not loading

### ISSUE THREAD

**Issue by nezaboravi** [laravel/vite-plugin#82]
- Laravel Vite Plugin Version:  vite v2.9.14 
- Laravel Version: Laravel v9.20.0
- Node Version: v16.16.0
- NPM Version: 8.14.0
- Host operating system: macOS Monterey, MacBook Pro 16" M1 Pro
- Web Browser & Version: Safari 15.5
- Running in Sail / Docker: Sail

### Description:
Default laravel page is not loading on Safari due an error:
```
[Error] Failed to load resource: bad URL (client, line 0) http://0.0.0.0:5173/@vite/client
[Error] Failed to load resource: bad URL (client, line 0) http://0.0.0.0:5173/resources/app.js
```
However, it works properly in firefox.

This happens only when you run sail npm run dev.

Running sail npm run build, everything works fine.

### Steps To Reproduce:
Install fresh laravel app with sail
`curl -s "https://laravel.build/test" | bash`

Add laravel jetstream into it
`composer require laravel/jetstream`

Add Inertia
`sail php artisan jetstream:install livewire`

Run migrations
`sail artisan migrate`

Run NPM
`sail npm run install`
`sail npm run dev`

Visit http://localhost

<img width="1720" alt="Screenshot 2022-07-16 at 12 53 53" src="https://user-images.githubusercontent.com/1515172/179352225-1ece05f5-abb6-4247-8d0b-47624096c3f1.png">

**Comment by jessarcher** [comment]
@timacdonald have you seen this one?

**Comment by driesvints** [comment]
Works fine for me in Safari:

<img width="1964" alt="Screenshot 2022-07-19 at 14 07 45" src="https://user-images.githubusercontent.com/594614/179746572-29c0f8e3-f745-4958-8b62-dc9d36ba5a73.png>

Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by nezaboravi** [comment]
Thanks @driesvints seems it works for you.

**Comment by ArcaneDrift** [comment]
@nezaboravi  I just came to post this haha, I'm seeing the same issue on a M1 MacBook Pro,  works fine in Chrome and Firefox but it seem Safari is ignoring 0.0.0.0 with the error "Bad URL"
![Screen Shot 2022-07-23 at 2 30 35 am](https://user-images.githubusercontent.com/109709314/180489619-cddc238f-4dcd-4f38-a961-1dc9c882f72b.jpg)

**Comment by njpanderson** [comment]
Getting the same thing myself here. Anyone figure out a workaround and/or cause?
