### ISSUE TITLE
The Vite server should not be accessed directly.

### ISSUE THREAD

**Issue by bcorcoran** [laravel/vite-plugin#84]
- Laravel Vite Plugin Version: 0.4.0
- Laravel Version: 9.19.0
- Node Version: 18.6.0
- NPM Version: 8.13.2
- PNPM Version: 7.5.2
- Host operating system: macOS 12.4
- Web Browser & Version: Edge 103.0.1264.62 (Official build) (arm64)
- Running in Sail / Docker: No

### Description:
When running pnpm/npm run dev, I get the following output:

```
➜  pnpm run dev

> @ dev /Users/xxx/Sites/xxxx
> vite


  vite v2.9.14 dev server running at:

  > Local:    https://xxxx.test:3000/
  > Network:  https://10.0.0.56:3000/
  > Network:  https://10.0.0.76:3000/

  ready in 419ms.


  Laravel v9.19.0

  > APP_URL: https://xxxx.test

The Vite server should not be accessed directly. Your Laravel application's configured APP_URL is: https://xxxx.test (xNN)
```

### Steps To Reproduce:

run `pnpm run dev`

### Question:

Is this normal? or is there something wrong with my install? I used the instructions at [freek.dev ](https://freek.dev/2276-making-vite-and-valet-play-nice-together) to get vite working valet with my local hostname on https, but that's the only non-standard customization I've done as far as I understand.

**Comment by jessarcher** [comment]
Have you navigated to `https://xxxx.test:3000/` in your browser? This warning should only show up when making requests to the index page of the Vite dev server.

Could you please provide your `vite.config.js` and your usage of the `@vite` directive?

**Comment by driesvints** [comment]
@bcorcoran yes this is expected. Please don't access the local url directly. Feel free to answer @jessarcher' questions.

**Comment by bcorcoran** [comment]
> Have you navigated to `https://xxxx.test:3000/` in your browser? This warning should only show up when making requests to the index page of the Vite dev server.
> 
> Could you please provide your `vite.config.js` and your usage of the `@vite` directive?

vite.config.js
```js
import fs from 'fs'
import { homedir } from 'os'
import { resolve } from 'path'
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue';

let host = 'xxxx.test'

export default defineConfig({
  plugins: [
    laravel([
      'resources/js/app.js',
    ]),
    vue({
        template: {
            transformAssetUrls: {
                base: null,
                includeAbsolute: false,
            },
        },
    }),
  ],
  resolve: {
    alias: {
      '@': '/resources/js',
    },
  },
  server: detectServerConfig(host),
});

function detectServerConfig(host) {
  let keyPath = resolve(homedir(), `.config/valet/Certificates/${host}.key`)
  let certificatePath = resolve(homedir(), `.config/valet/Certificates/${host}.crt`)

  if (!fs.existsSync(keyPath)) {
    return {}
  }

  if (!fs.existsSync(certificatePath)) {
    return {}
  }

  return {
    hmr: {host},
    host,
    https: {
      key: fs.readFileSync(keyPath),
      cert: fs.readFileSync(certificatePath),
    },
  }
}

```

And my usage of the @vite directive:

`@vite('resources/js/app.js')` as the last item in <head>

**Comment by bcorcoran** [comment]
@jessarcher It appears my 404s (from missing ".vue" on SFC imports) were triggering the message. Once I added the extension to all relevant imports, the message went away.
