### ISSUE TITLE
Use Valet certificates automatically for Vite SSL

### ISSUE THREAD

**Issue by kurucu** [laravel/vite-plugin#85]
I have started using the code in this blog post by Freek to (almost) automatically set up SSL with Vite for Valet.

https://freek.dev/2276-making-vite-and-valet-play-nice-together

I'm wondering if this could be added to vite-plugin as an option `valet: true`; and somehow detecting `host` automatically e.g. from the APP_URL environment variable?

Edit: Valet generates the "host" from the current working dir + Valet's TLD, so maybe this is harder than I thought.

**Comment by driesvints** [comment]
I don't think we have plans for this right now. Thanks
