### ISSUE TITLE
Ability to omit paths from refresh

### ISSUE THREAD

**Issue by willvincent** [laravel/vite-plugin#88]
It's super straightforward to _include_ paths to look at for triggering a refresh, but it would be really helpful to be able to also define paths to _exclude_. The use case for me is that I'd like to omit `resources/views/livewire/**` and instead let the [vite-livewire-plugin](https://github.com/def-studio/vite-livewire-plugin) handle hot-reloading when those files change.

I was able to cobble together something that works based on the old workaround to get full page refresh working when blade files change by explicitly ensuring the triggering file(s) don't include `/livewire/` in their path name.

But it would be much nicer to, instead of this:

```
{
  name: 'blade',
  handleHotUpdate({ file, server }) {
    if ((file.includes('routes/') || file.endsWith('.blade.php')) && !file.includes('/livewire/')) {
      server.ws.send({
        type: 'full-reload',
        path: '*',
      })
    }
  },
}
```

Simply be able to do something like this:
```
{
  laravel({
    // ...
    refresh: ['resources/views/**'],
    omit: ['resources/views/livewire/**'],
  }),
}
```

**Comment by driesvints** [comment]
Feel free to attempt a PR, thanks 👍

**Comment by timacdonald** [comment]
@willvincent you can create a glob pattern to match your requirements. Under the hood, picomatch is used, so the following should work for your needs...

```js
{
  laravel({
    // ...
    refresh: ['resources/views/!(livewire)**'],
  }),
}
```

You can learn more in the picomatch documentation: https://github.com/micromatch/picomatch#advanced-globbing

**Comment by willvincent** [comment]
Oooo! I didn't know about the ability to negate specific path parts, that's fantastic!

Thanks @timacdonald that's super helpful.

**Comment by timacdonald** [comment]
no troubles at all!

**Comment by willvincent** [comment]
Unfortunately that doesn't seem to be working, but I'll keep digging. Appreciate the point in the right direction

**Comment by timacdonald** [comment]
Might be. I just tried this on a fresh app and it worked as expected. Hopefully you can get it going 😀

**Comment by willvincent** [comment]
Just downgraded to vite 2.9 and it's all good!

🎉🤘
