### ISSUE TITLE
Consider not hardcoding `ASSET_URL` into the base path for production builds

### ISSUE THREAD

**Issue by localpath** [laravel/vite-plugin#89]
Introduce a way to override the base path used for production builds. In some instance the asset_url may be assigned to a different CDN or location than where the build assets need to be ie (a different CDN or the app server itself).

https://github.com/laravel/vite-plugin/blob/d0b8894b7fa8e4086d8c0d274b7cb26a7b93a5c1/src/index.ts#L100

https://github.com/laravel/vite-plugin/blob/d0b8894b7fa8e4086d8c0d274b7cb26a7b93a5c1/src/index.ts#L316

**Comment by localpath** [comment]
Hello. Thanks for the quick response. So for instance the `ASSET_URL` is using a cdn for known static files but the build pipeline is not "building" the SPA/JS/LESS and then copying it over to a bucket to be picked up by the cdn for instance.

I like ur idea of the build step env var. That would work perfectly. My point was just that it forces the entire deployment to use or not use the native laravel asset helper as the base URL and I made a new temporary helper called `secure_cdn($path)` for instance.

I'll give the env at build step a shot next time unless we can merge on that variable in the laravel-vite plugin

**Comment by driesvints** [comment]
It seems you sent in a PR for this, thanks. Let's continue the discussion there: https://github.com/laravel/vite-plugin/pull/91
