### ISSUE TITLE
Upgrade to new ViteJS major version V3

### ISSUE THREAD

**Issue by jimblue** [laravel/vite-plugin#90]
Hey,
ViteJS V3 has been release 🎉... It could be nice to upgrade Laravel Vite plugin to use it 🙏🏼 
Cheers

**Comment by jbraband** [comment]
I believe I read in a comment from Dries that the update for laravel/vite-plugin is being tagged tomorrow.

**Comment by jessarcher** [comment]
There is already a PR for this: #77
