### ISSUE TITLE
Assets url on subdirectory of server causes duplicate app name

### ISSUE THREAD

**Issue by Rubens10010** [laravel/vite-plugin#92]
- Laravel Vite Plugin Version: 0.4.0
- Laravel Version: 9.2.0
- Node Version: 16,16
- NPM Version: 8.11.0
- Host operating system: Ubuntu 20.4
- Web Browser & Version: Chrome
- Running in Sail / Docker: No

### Description:
I have a brand new installation of laravel with inertia and vite I installed this on my server running php8.1 and nginx serving serveral other apps. I have several blocks of locations in nginx config file like this:

```
location /test {
        alias /var/www/html/test/public;
        try_files $uri $uri/ /index.php?$query_string;
        client_max_body_size 10M;

        location ~ \.php$ {
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $request_filename;
                fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
        }
}
```

I've added `ASSET_URL=https://mydomain.is/test` to .env file since I'm not serving from root server directory
Whenever I run `npm run build` assets are deployed successfully and I can navigate to https://mydomain.is/test but for some reason the app name is duplicated as soon as page is loaded (no refreshing the page) like so: https://mydomain.is/test/test and therefore all links are broken

What is happening? Do I need to configure something special to make this work as expected? Could you provide more info about deploying on your documentation?

### Steps To Reproduce:
- Install new laravel project
- Add inertia + vue
- Configure nginx server to serve from subdirectories
- Add ASSET_URL to .env file
- build the assets and go to app url
- app name is duplicated in the last part of app url

**Comment by driesvints** [comment]
We don't support Laravel apps in subdirectory. Please don't do that as this is dangerous.

**Comment by lucraraujo** [comment]
This is a problem with recente versions os Inertia. There are some issues open at their repository and some workarounds. Check them out there.

**Comment by Azmeer-crescent** [comment]
> We don't support Laravel apps in subdirectory. Please don't do that as this is dangerous.

Are you saying vite doesn't support Laravel on sub directories? I too have a genuine reason to run from a sub directory.

**Comment by fathonir** [comment]
> We don't support Laravel apps in subdirectory. Please don't do that as this is dangerous.

Is there any plan to support this in the future ?
